name: air_traffic_controller
display_name: Air Traffic Controller
description: Manages and monitors air traffic, ensuring safe and efficient flight operations. Provides capabilities to list flight information and reroute flights as necessary for safety or efficiency.
category: aviation_management
complexity_level: 3
estimated_duration: 30
required_permissions:
- flight_data_access
- reroute_permission
dependencies: []
generation_weight: 1.5
sample_actions:
- list_flight_info
- reroute_flight
metadata:
  selection_way: random
  selection_num: 2
tags:
- aviation
- air_traffic_control
- safety
context:
  available_tools:
  - name: list_flight_info
    display_name: List Flight Information
    description: Retrieve and display all current flight information for monitoring.
    category: information_management
    parameters: []
    example_usage:
    - list_flight_info()
  - name: reroute_flight
    display_name: Reroute Flight
    description: Change the flight path for safety or efficiency reasons.
    category: flight_management
    parameters:
    - name: flight_id
      type: string
      description: The unique flight identifier.
      required: true
    - name: new_path
      type: string
      description: The new trajectory path for the flight.
      required: true
    example_usage:
    - reroute_flight(flight_id='FL123', new_path='Path B')
  environment:
    name: air_traffic_control_system
    description: Environment for managing air traffic with tools for flight information and rerouting.
    variables:
    - name: MAX_FLIGHTS
      value: 1000
      description: Maximum number of flights that can be managed simultaneously.
      type: integer
    - name: SAFETY_PROTOCOL_URL
      value: 'https://www.example.com/safety-protocol'
      description: URL to the safety protocol documentation.
      type: string
    settings:
      reroute_notification: true
      flight_info_refresh_rate: 60
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - aviation-authority.com
    - '*.trusted-airline.com'
    blocked_domains:
    - '*.unauthorized-access.com'
  predefined_variables:
    current_user_role: Air Traffic Controller
    current_user_id: ATC123
    control_tower_location: JFK International Airport
    timezone: UTC-5
    operational_hours: 24/7
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true