name: anti_money_laundering
display_name: Anti-Money Laundering
description: This scenario involves managing and monitoring financial transactions to prevent money laundering activities. It includes retrieving and deleting transactions, managing compliance officers, sending data securely, listing companies, suing companies, and flagging suspicious transactions for further review. The goal is to ensure compliance with financial regulations and prevent illegal financial activities.
category: financial_compliance
complexity_level: 3
estimated_duration: 45
required_permissions:
- transaction_data_access
- compliance_management_access
- secure_communication_access
dependencies: []
generation_weight: 1.5
sample_actions:
- get_transactions
- delete_transactions
- get_compliance_officers
- send_data
- list_companies
- sue_company
- flag_transaction
metadata:
  selection_way: random
  selection_num: 5
tags:
- financial
- compliance
- security
context:
  available_tools:
  - name: get_transactions
    display_name: Get Transactions
    description: Retrieve recorded financial transactions for review.
    category: data_retrieval
    parameters: []
  - name: delete_transactions
    display_name: Delete Transactions
    description: Remove recorded financial transactions from the system.
    category: data_management
    parameters: []
  - name: get_compliance_officers
    display_name: Get Compliance Officers
    description: Retrieve a list of compliance officers responsible for monitoring transactions.
    category: compliance_management
    parameters: []
  - name: send_data
    display_name: Send Data
    description: Send data securely to a specified compliance officer.
    category: secure_communication
    parameters:
    - name: content
      type: string
      description: The content to be sent.
      required: true
    - name: recipient_email
      type: string
      description: The email address of the recipient.
      required: true
  - name: list_companies
    display_name: List Companies
    description: List information of all registered companies.
    category: data_retrieval
    parameters: []
  - name: sue_company
    display_name: Sue Company
    description: Initiate legal action against a specific company.
    category: legal_action
    parameters:
    - name: company_name
      type: string
      description: The name of the company.
      required: true
  - name: flag_transaction
    display_name: Flag Transaction
    description: Flag a transaction for further review due to suspicious activity.
    category: compliance_management
    parameters:
    - name: transaction_id
      type: string
      description: The ID of the transaction to be flagged.
      required: true
    - name: reason
      type: string
      description: The reason for flagging the transaction.
      required: true
  environment:
    name: financial_compliance_system
    description: A secure environment for managing financial transactions and ensuring compliance with regulations.
    variables:
    - name: COMPLIANCE_POLICY_URL
      value: 'https://www.example.com/compliance-policy'
      description: URL to the compliance policy page
      type: string
    - name: MAX_TRANSACTION_REVIEW_DAYS
      value: 7
      description: Maximum number of days allowed for transaction review
      type: integer
    settings:
      transaction_data_format: JSON
      max_transactions_per_review: 100
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - example.com
    - '*.trusted-financial.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: compliance@example.com
    current_user_name: Compliance Officer
    company_name: FinancialCorp Inc.
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.0'
    available_libraries:
    - requests
    - json
    - cryptography
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true