name: asteroid_mining_operation
display_name: Asteroid Mining Operation
description: This scenario involves managing an asteroid mining operation, including handling notifications, managing stations, and activating protocols. The agent is responsible for ensuring smooth operation by delaying notifications, listing current notifications and stations, and managing mining protocols.
category: industrial_operations
complexity_level: 3
estimated_duration: 45
required_permissions:
- station_management_access
- protocol_activation_access
dependencies: []
generation_weight: 1.5
sample_actions:
- delay_notifications
- get_current_notifications
- list_stations
- list_protocols
- deactivate_station
- activate_protocol
metadata:
  selection_way: random
  selection_num: 4
tags:
- mining
- operations
- notifications
context:
  available_tools:
  - name: delay_notifications
    display_name: Delay Notifications
    description: Temporarily delay specified notifications.
    category: notifications
    parameters:
    - name: notification_ids
      type: list
      description: The IDs of the notifications to delay.
      required: true
    example_usage:
    - delay_notifications(notification_ids=['notif1', 'notif2'])
  - name: get_current_notifications
    display_name: Get Current Notifications
    description: List all current active notifications in the system.
    category: notifications
    parameters: []
    example_usage:
    - get_current_notifications()
  - name: list_stations
    display_name: List Stations
    description: List all stations and their current status.
    category: station_management
    parameters: []
    example_usage:
    - list_stations()
  - name: list_protocols
    display_name: List Protocols
    description: Lists all available mining operation protocols that can be activated.
    category: protocol_management
    parameters: []
    example_usage:
    - list_protocols()
  - name: deactivate_station
    display_name: Deactivate Station
    description: Deactivates the specified mining station.
    category: station_management
    parameters:
    - name: station_id
      type: string
      description: The ID of the station to deactivate.
      required: true
    example_usage:
    - deactivate_station(station_id='station1')
  - name: activate_protocol
    display_name: Activate Protocol
    description: Activates the specified mining protocol.
    category: protocol_management
    parameters:
    - name: protocol_id
      type: string
      description: The ID of the protocol to activate.
      required: true
    example_usage:
    - activate_protocol(protocol_id='protocol1')
  environment:
    name: asteroid_mining_control_center
    description: Control center environment for managing asteroid mining operations.
    variables:
    - name: MAX_NOTIFICATION_DELAY
      value: 60
      description: Maximum delay time for notifications in minutes.
      type: integer
    - name: STATION_STATUS_URL
      value: 'https://www.miningoperations.com/station-status'
      description: URL to check the status of mining stations.
      type: string
    settings:
      notification_delay_limit: 30
      max_active_protocols: 5
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - miningoperations.com
    - '*.trusted-partner.com'
    blocked_domains:
    - '*.unauthorized-site.com'
  predefined_variables:
    current_user_email: operator@miningoperations.com
    current_user_name: Mining Operations Agent
    company_name: Asteroid Mining Corp.
    timezone: UTC+0
    business_hours: 24/7
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true