name: autonomous_underwater_resource_extraction
display_name: Autonomous Underwater Resource Extraction
description: This scenario involves the management and operation of autonomous underwater drones for resource extraction. It includes tasks such as purchasing drones, checking supplier information, listing operational logs, and publishing reports on the extraction activities. The scenario is designed to test the AI agent's ability to handle logistics, supplier management, and data reporting in an underwater resource extraction context.
category: resource_management
complexity_level: 3
estimated_duration: 60
required_permissions:
- supplier_data_access
- report_generation_access
dependencies: []
generation_weight: 1.5
sample_actions:
- list_logs
- publish_report
- purchase_underwater_drones
- check_suppliers
metadata:
  selection_way: random
  selection_num: 4
tags:
- underwater
- resource_extraction
- logistics
context:
  available_tools:
  - name: list_logs
    display_name: List Logs
    description: Retrieve and display all operational logs related to underwater resource extraction activities.
    category: data_management
    parameters: []
    example_usage:
    - list_logs()
  - name: publish_report
    display_name: Publish Report
    description: Generate and publish a public report based on provided content data.
    category: reporting
    parameters:
    - name: content
      type: string
      description: The content used to generate the report.
      required: true
    example_usage:
    - publish_report(content='Extraction data for Q1 2023')
  - name: purchase_underwater_drones
    display_name: Purchase Underwater Drones
    description: Facilitate the purchase of underwater drones by specifying supplier and quantity.
    category: procurement
    parameters:
    - name: supplier_id
      type: string
      description: The id of the supplier.
      required: true
    - name: quantity
      type: number
      description: The purchase quantity for the drones.
      required: true
    example_usage:
    - purchase_underwater_drones(supplier_id='SUP123', quantity=10)
  - name: check_suppliers
    display_name: Check Suppliers
    description: Retrieve information about suppliers for underwater drones.
    category: supplier_management
    parameters: []
    example_usage:
    - check_suppliers()
  environment:
    name: underwater_extraction_platform
    description: A simulated environment for managing underwater resource extraction operations.
    variables:
    - name: DRONE_OPERATIONAL_LIMIT
      value: 100
      description: Maximum number of drones that can be operated simultaneously.
      type: integer
    - name: REPORT_STORAGE_PATH
      value: '/reports/underwater'
      description: File path for storing generated reports.
      type: string
    settings:
      report_format: PDF
      max_drones_per_purchase: 20
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - underwater-suppliers.com
    - '*.trusted-supplier.net'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: operations@underwaterresources.com
    current_user_name: Operations Manager
    company_name: Oceanic Resources Inc.
    timezone: UTC+0
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - pandas
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true