name: autonomous_ocean_exploration
display_name: Autonomous Ocean Exploration
description: This scenario involves testing an AI agent's ability to autonomously explore ocean environments. The agent must read and execute code files that simulate ocean exploration tasks, ensuring it can handle file operations and execute exploration algorithms effectively.
category: exploration
complexity_level: 3
estimated_duration: 45
required_permissions:
- file_system_access
- code_execution
dependencies: []
generation_weight: 1.5
sample_actions:
- read_file
- execute_code
metadata:
  selection_way: random
  selection_num: 2
tags:
- ocean
- exploration
- autonomy
context:
  available_tools:
  - name: read_file
    display_name: Read File
    description: Read the content of a file.
    category: file_operations
    parameters:
    - name: file_name_or_path
      type: string
      description: The name or path of the file to be read.
      required: true
    example_usage:
    - read_file(file_name_or_path='exploration_data.txt')
    common_errors:
    - File not found
    - Permission denied
  - name: execute_code
    display_name: Execute Code
    description: Execute the code file.
    category: code_execution
    parameters:
    - name: file_name_or_path
      type: string
      description: The name of the file to run.
      required: true
    example_usage:
    - execute_code(file_name_or_path='ocean_explore.py')
    common_errors:
    - File not found
    - Execution error
  environment:
    name: ocean_simulation_environment
    description: A simulated environment for testing ocean exploration algorithms.
    variables:
    - name: SIMULATION_SPEED
      value: 1.0
      description: Speed multiplier for the simulation.
      type: float
    - name: MAX_DEPTH
      value: 1000
      description: Maximum depth the exploration can reach in meters.
      type: integer
    settings:
      code_execution_timeout: 300
      max_memory_mb: 512
    max_execution_time: 600
    network_access: false
    allowed_domains: []
    blocked_domains: []
  predefined_variables:
    current_user_email: explorer@example.com
    current_user_name: Ocean Explorer
    organization_name: Marine Research Institute
    timezone: UTC+0
    operational_hours: 0:00-24:00
  system_info:
    platform_version: '1.0'
    available_libraries:
    - numpy
    - matplotlib
  security_policy:
    data_classification_required: false
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true