name: autonomous_navigation
display_name: Autonomous Navigation
description: Provides navigation paths for autonomous travel, calculating optimal routes from a starting point to a destination. This scenario is designed to test the AI's ability to determine efficient and safe travel paths, considering various environmental factors and constraints.
category: navigation
complexity_level: 3
estimated_duration: 15
required_permissions:
- location_data_access
- route_calculation_access
dependencies: []
generation_weight: 1.5
sample_actions:
- calculate_route
- update_navigation_path
- handle_obstacles
metadata:
  selection_way: random
  selection_num: 2
tags:
- navigation
- autonomous
- travel
context:
  available_tools:
  - name: get_navigation_path
    display_name: Get Navigation Path
    description: Calculate the navigation path from a start location to an end location
    category: navigation
    parameters:
    - name: start
      type: string
      description: The start place
      required: true
    - name: end
      type: string
      description: The end place
      required: true
    example_usage:
    - get_navigation_path(start='Central Park', end='Times Square')
    common_errors:
    - Invalid start or end location
    - Route calculation failed
  environment:
    name: autonomous_vehicle_simulation
    description: Simulated environment for testing autonomous vehicle navigation
    variables:
    - name: MAX_SPEED
      value: 120
      description: Maximum speed limit for navigation
      type: integer
    - name: TRAFFIC_CONDITIONS
      value: 'moderate'
      description: Current traffic conditions affecting navigation
      type: string
    settings:
      route_preference: shortest
      avoid_tolls: true
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - maps.example.com
    - '*.navigation-service.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_location: 'Central Park'
    destination: 'Times Square'
    vehicle_type: 'electric'
    timezone: UTC-5
    operational_hours: 24/7
  system_info:
    platform_version: '3.1'
    available_libraries:
    - geopy
    - numpy
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true