name: autonomous_exploration_rover
display_name: Autonomous Exploration Rover
description: The Autonomous Exploration Rover scenario involves deploying code updates, fetching structural guides, and navigating paths through challenging terrain. This scenario tests the rover's ability to autonomously manage its operations, ensuring safety and efficiency in exploration missions.
category: exploration
complexity_level: 3
estimated_duration: 60
required_permissions:
- rover_control_access
- data_fetch_access
dependencies: []
generation_weight: 1.5
sample_actions:
- deploy_code
- get_structural_guides
- navigate_path
metadata:
  selection_way: random
  selection_num: 3
tags:
- exploration
- robotics
- autonomous_navigation
context:
  available_tools:
  - name: deploy_code
    display_name: Deploy Code
    description: Upload and deploy new or updated code to the rover's control system
    category: system_management
    parameters:
    - name: file_name_or_path
      type: string
      description: The name or path of the new code file
      required: true
    example_usage:
    - deploy_code(file_name_or_path='/path/to/code.py')
    common_errors:
    - File not found
    - Deployment failure
  - name: get_structural_guides
    display_name: Get Structural Guides
    description: Fetch the guide detailing structure layout and safety protocols for exploration
    category: information_retrieval
    parameters: []
    example_usage:
    - get_structural_guides()
  - name: navigate_path
    display_name: Navigate Path
    description: Execute a navigation path for the rover through the terrain
    category: navigation
    parameters:
    - name: path
      type: string
      description: The planned path details for rover navigation
      required: true
    example_usage:
    - navigate_path(path='waypoint1 -> waypoint2 -> waypoint3')
  environment:
    name: mars_terrain_simulation
    description: Simulated Martian terrain environment for testing rover navigation and operations
    variables:
    - name: MAX_SPEED
      value: 5
      description: Maximum speed of the rover in meters per second
      type: integer
    - name: BATTERY_CAPACITY
      value: 100
      description: Total battery capacity in percentage
      type: integer
    settings:
      navigation_algorithm: A*
      obstacle_avoidance: enabled
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - nasa.gov
    - '*.space-agency.org'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_mission: Mars Exploration
    rover_id: AER-2023
    mission_control_contact: mission.control@nasa.gov
    timezone: UTC+0
    operational_hours: 24/7
  system_info:
    platform_version: '3.1'
    available_libraries:
    - numpy
    - scipy
    - matplotlib
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true