name: automated_driving
display_name: Automated Driving System
description: This scenario involves the management and optimization of autonomous vehicle operations, focusing on route planning, speed adjustments, and sensor calibration. The goal is to ensure efficient and safe navigation by dynamically adjusting to traffic conditions and maintaining up-to-date vehicle calibrations.
category: autonomous_vehicles
complexity_level: 3
estimated_duration: 30
required_permissions:
- vehicle_data_access
- route_management_access
dependencies: []
generation_weight: 1.5
sample_actions:
- get_alternate_routes
- adjust_vehicle_route
- update_calibration
- list_vehicles
- get_calibration_data
- get_route_settings
- adjust_route_settings
- check_speed_policy
- modify_speed
metadata:
  selection_way: random
  selection_num: 5
tags:
- autonomous_driving
- route_optimization
- vehicle_management
context:
  available_tools:
  - name: get_alternate_routes
    display_name: Get Alternate Routes
    description: Search for alternate routes based on traffic conditions and restrictions.
    category: navigation
    parameters: []
    example_usage:
    - get_alternate_routes()
  - name: adjust_vehicle_route
    display_name: Adjust Vehicle Route
    description: Modify vehicle route based on traffic conditions and restrictions.
    category: navigation
    parameters:
    - name: route_name
      type: string
      description: Name of the alternative route for vehicles to take.
      required: true
    example_usage:
    - adjust_vehicle_route(route_name='Route 66')
  - name: update_calibration
    display_name: Update Calibration
    description: Update the vehicle's sensor calibration to the latest version.
    category: maintenance
    parameters:
    - name: vehicle_id
      type: string
      description: The ID of the vehicle to update.
      required: true
    example_usage:
    - update_calibration(vehicle_id='V12345')
  - name: modify_speed
    display_name: Modify Speed
    description: Modify the driving speed of the vehicle.
    category: navigation
    parameters:
    - name: new_speed
      type: string
      description: The new driving speed of the vehicle.
      required: true
    example_usage:
    - modify_speed(new_speed='60 mph')
  environment:
    name: autonomous_vehicle_network
    description: A network environment for managing autonomous vehicles with real-time data access and control capabilities.
    variables:
    - name: TRAFFIC_API_URL
      value: 'https://api.trafficinfo.com'
      description: URL to access real-time traffic information
      type: string
    - name: MAX_SPEED_LIMIT
      value: 120
      description: Maximum speed limit for autonomous vehicles
      type: integer
    settings:
      route_update_interval: 5
      max_vehicles_per_fleet: 100
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - trafficinfo.com
    - '*.vehicledata.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    fleet_manager_email: fleet.manager@autodrive.com
    fleet_manager_name: Fleet Manager
    company_name: AutoDrive Inc.
    timezone: UTC
    business_hours: 24/7
  system_info:
    platform_version: '3.0'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true