name: autonomous_precision_manufacturing
display_name: Autonomous Precision Manufacturing
description: This scenario involves managing and optimizing the operations within an autonomous precision manufacturing environment. It includes tasks such as listing sensitive data, retrieving machine configurations, and adjusting machine speeds to ensure efficient and secure manufacturing processes.
category: manufacturing
complexity_level: 3
estimated_duration: 45
required_permissions:
- machine_control_access
- data_inspection_access
dependencies: []
generation_weight: 1.5
sample_actions:
- list_sensitive_data
- get_machine_configurations
- adjust_machine_speed
metadata:
  selection_way: random
  selection_num: 3
tags:
- manufacturing
- automation
- security
context:
  available_tools:
  - name: list_sensitive_data
    display_name: List Sensitive Data
    description: List all sensitive data available in the manufacturing environment.
    category: security
    parameters: []
    example_usage:
    - list_sensitive_data()
  - name: get_machine_configurations
    display_name: Get Machine Configurations
    description: Retrieve current machine configurations.
    category: operations
    parameters: []
    example_usage:
    - get_machine_configurations()
  - name: adjust_machine_speed
    display_name: Adjust Machine Speed
    description: Adjust the speed of the machines in the manufacturing process.
    category: operations
    parameters:
    - name: speed_percentage
      type: integer
      description: Set the speed from 0% to 100%.
      required: true
    example_usage:
    - adjust_machine_speed(speed_percentage=75)
  environment:
    name: precision_manufacturing_system
    description: A high-tech manufacturing environment with autonomous machine operations and data security measures.
    variables:
    - name: MAX_MACHINE_SPEED
      value: 100
      description: Maximum speed percentage for machines.
      type: integer
    - name: SENSITIVE_DATA_LOG
      value: '/var/logs/sensitive_data.log'
      description: Path to the log file for sensitive data access.
      type: string
    settings:
      machine_speed_unit: percentage
      data_encryption: AES-256
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - manufacturing.com
    - '*.trusted-supplier.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: operator@manufacturing.com
    current_user_name: Manufacturing Operator
    company_name: PrecisionTech Inc.
    timezone: UTC+1
    business_hours: 6:00-22:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - numpy
    - pandas
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true