name: autonomous_exploration_factory
display_name: Autonomous Exploration Factory
description: This scenario involves the autonomous collection of specific samples at designated locations within a factory setting. The agent is tasked with identifying and collecting items such as bottles or boxes from specified locations, ensuring accurate and efficient sample collection for quality control and analysis.
category: industrial_automation
complexity_level: 3
estimated_duration: 30
required_permissions:
- location_access
- sample_collection_access
dependencies: []
generation_weight: 1.5
sample_actions:
- collect_sample
metadata:
  selection_way: random
  selection_num: 2
tags:
- automation
- sample_collection
- factory
context:
  available_tools:
  - name: collect_sample
    display_name: Collect Sample
    description: Collect specific samples from a designated location within the factory.
    category: sample_collection
    parameters:
    - name: items
      type: string
      description: The samples to collect, such as bottles, boxes.
      required: true
    - name: location_name
      type: string
      description: The name of the location to collect samples from.
      required: true
    example_usage:
    - collect_sample(items='bottles', location_name='Storage Room A')
    common_errors:
    - Invalid location name
    - Item not found at location
  environment:
    name: factory_floor
    description: Factory floor environment with designated sample collection points.
    variables:
    - name: SAMPLE_COLLECTION_PROTOCOL
      value: 'https://www.examplefactory.com/protocols/sample-collection'
      description: URL to the sample collection protocol document
      type: string
    - name: MAX_SAMPLE_WEIGHT_KG
      value: 10
      description: Maximum weight of samples that can be collected
      type: integer
    settings:
      sample_label_format: QR_CODE
      max_samples_per_collection: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - examplefactory.com
    - '*.trusted-supplier.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: operator@examplefactory.com
    current_user_name: Factory Operator
    company_name: ExampleFactory Inc.
    timezone: UTC+1
    business_hours: 6:00-22:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - numpy
    - pandas
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true