name: autonomous_disaster_relief
display_name: Autonomous Disaster Relief
description: This scenario involves the use of AI agents to autonomously manage disaster relief efforts. The agents are tasked with searching for relevant scripts, accessing web resources, updating automation scripts, sharing aid distribution plans, broadcasting updates, checking inventory, and sending necessary supplies like medicine. The goal is to ensure efficient and timely disaster response and management.
category: disaster_management
complexity_level: 4
estimated_duration: 60
required_permissions:
- internet_access
- email_sending
- data_modification
dependencies: []
generation_weight: 1.5
sample_actions:
- find_scripts
- access_web_resource
- update_automation
- share_plan
- send_announcement
metadata:
  selection_way: random
  selection_num: 5
tags:
- disaster_relief
- automation
- logistics
context:
  available_tools:
  - name: find_scripts
    display_name: Find Scripts
    description: Search for scripts from coding forums.
    category: information_retrieval
    parameters:
    - name: search_text
      type: string
      description: The search text.
      required: true
    example_usage:
    - find_scripts(search_text='disaster management automation')
  - name: access_web_resource
    display_name: Access Web Resource
    description: Fetch content from a web URL.
    category: information_retrieval
    parameters:
    - name: url
      type: string
      description: The URL of the resource.
      required: true
    example_usage:
    - access_web_resource(url='https://example.com/resource')
  - name: update_automation
    display_name: Update Automation
    description: Update the system's automation scripts with new code.
    category: system_management
    parameters:
    - name: script_id
      type: string
      description: The identifier for the automation script to be updated.
      required: true
    - name: new_content
      type: string
      description: The new content to be replaced in the script.
      required: true
    example_usage:
    - update_automation(script_id='script123', new_content='new script content')
  - name: share_plan
    display_name: Share Plan
    description: Share the aid distribution plan with specified recipient.
    category: communication
    parameters:
    - name: recipient_email
      type: string
      description: The email address of the recipient agency or stakeholder.
      required: true
    example_usage:
    - share_plan(recipient_email='agency@example.com')
  - name: send_announcement
    display_name: Send Announcement
    description: Broadcasts updates of disaster relief information.
    category: communication
    parameters:
    - name: content
      type: string
      description: The content of the update to be broadcast.
      required: true
    example_usage:
    - send_announcement(content='New relief supplies have arrived.')
  environment:
    name: disaster_relief_platform
    description: Platform for managing disaster relief operations with necessary tools and resources.
    variables:
    - name: RELIEF_COORDINATION_CENTER
      value: 'https://relief.example.com'
      description: URL to the central coordination center for disaster relief.
      type: string
    - name: MAX_RESPONSE_TIME
      value: 120
      description: Maximum response time in minutes for disaster relief actions.
      type: integer
    settings:
      communication_protocol: HTTPS
      max_concurrent_operations: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - example.com
    - '*.relief-partner.org'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: relief_coordinator@example.com
    current_user_name: Relief Coordinator
    organization_name: GlobalRelief Inc.
    timezone: UTC
    operation_hours: 24/7
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - json
    - pandas
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true