name: autonomous_asteroid_deflection
display_name: Autonomous Asteroid Deflection
description: This scenario involves managing and controlling an autonomous asteroid deflection system. The system is designed to monitor asteroid trajectories and perform necessary interventions to alter their paths, ensuring they do not pose a threat to Earth. The scenario includes tasks such as retrieving system status, performing manual interventions, adjusting energy outputs, and toggling deflection modes.
category: space_operations
complexity_level: 4
estimated_duration: 60
required_permissions:
- system_control_access
- energy_management_access
dependencies: []
generation_weight: 1.5
sample_actions:
- get_system_status
- perform_intervention
- adjust_energy_output
- toggle_deflection_mode
metadata:
  selection_way: random
  selection_num: 5
tags:
- asteroid_deflection
- space_operations
- energy_management
context:
  available_tools:
  - name: get_system_status
    display_name: Get System Status
    description: Retrieves current status and scheduled interventions for the system.
    category: monitoring
    parameters: []
    example_usage:
    - get_system_status()
  - name: perform_intervention
    display_name: Perform Intervention
    description: Perform a manual intervention in the deflection system.
    category: operations
    parameters:
    - name: intervention_id
      type: string
      description: The ID of the intervention to be scheduled.
      required: true
    example_usage:
    - perform_intervention(intervention_id='INT123')
  - name: adjust_energy_output
    display_name: Adjust Energy Output
    description: Adjust the energy output of various power sources specifying which source and target output.
    category: energy_management
    parameters:
    - name: source
      type: string
      description: The power source to adjust (e.g., solar_panels, nuclear_reactors, etc.).
      required: true
    - name: output
      type: integer
      description: Target energy output for the specified source.
      required: true
    example_usage:
    - adjust_energy_output(source='solar_panels', output=500)
  - name: toggle_deflection_mode
    display_name: Toggle Deflection Mode
    description: Enable or disable the asteroid deflection system.
    category: operations
    parameters:
    - name: activate
      type: boolean
      description: Set to true to activate the deflection mode, false to deactivate.
      required: true
    example_usage:
    - toggle_deflection_mode(activate=true)
  environment:
    name: space_deflection_control_center
    description: A control center environment for managing asteroid deflection operations with real-time monitoring and energy management capabilities.
    variables:
    - name: DEFLECTION_PROTOCOL_URL
      value: 'https://www.spaceagency.gov/deflection-protocol'
      description: URL to the official deflection protocol documentation
      type: string
    - name: MAX_ENERGY_OUTPUT
      value: 1000
      description: Maximum allowable energy output for power sources
      type: integer
    settings:
      energy_output_unit: MW
      intervention_response_time: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - spaceagency.gov
    - '*.trusted-space-partner.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_operator_email: operator@spaceagency.gov
    current_operator_name: Space Operations Specialist
    agency_name: Space Agency
    timezone: UTC+0
    mission_hours: 24/7
  system_info:
    platform_version: '3.0'
    available_libraries:
    - numpy
    - scipy
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true