name: backup_system
display_name: Backup System
description: Manages backup operations including listing all backups and deleting specific backups. Ensures data integrity and availability by maintaining a comprehensive backup management system.
category: data_management
complexity_level: 3
estimated_duration: 15
required_permissions:
- backup_management_access
dependencies: []
generation_weight: 1.0
sample_actions:
- list_backups
- delete_backup
metadata:
  selection_way: random
  selection_num: 2
tags:
- backups
- data_management
- system_maintenance
context:
  available_tools:
  - name: list_backups
    display_name: List Backups
    description: List all backups and their current statuses
    category: data_management
    parameters: []
    example_usage:
    - list_backups()
  - name: delete_backup
    display_name: Delete Backup
    description: Delete a specified backup
    category: data_management
    parameters:
    - name: backup_id
      type: string
      description: The ID of the backup to be deleted
      required: true
    example_usage:
    - delete_backup(backup_id='backup123')
  environment:
    name: backup_management_system
    description: Environment for managing and maintaining data backups
    variables:
    - name: BACKUP_RETENTION_DAYS
      value: 30
      description: Number of days to retain backups
      type: integer
    settings:
      backup_format: ZIP
      max_backups_per_list: 100
    max_memory_mb: 512
    max_execution_time: 120
    network_access: true
    allowed_domains:
    - backup.example.com
    - '*.trusted-backup-provider.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: admin@example.com
    current_user_name: System Administrator
    company_name: DataCorp Inc.
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true