name: biocontainment_facility
display_name: Biocontainment Facility Protocol Management
description: This scenario involves managing and accessing critical documents within a biocontainment facility. The agent is responsible for retrieving and reading specified documents, as well as downloading copies of emergency protocols. This ensures that all necessary information is readily available for maintaining safety and compliance within the facility.
category: facility_management
complexity_level: 3
estimated_duration: 30
required_permissions:
- document_access
- protocol_download_access
dependencies: []
generation_weight: 1.5
sample_actions:
- read_document
- download_protocol
metadata:
  selection_way: random
  selection_num: 2
tags:
- biocontainment
- safety
- document_management
context:
  available_tools:
  - name: read_document
    display_name: Read Document
    description: Retrieve and read the content of a specified document
    category: document_management
    parameters:
    - name: title
      type: string
      description: The title of the document to read
      required: true
    example_usage:
    - read_document(title='Safety Guidelines')
  - name: download_protocol
    display_name: Download Protocol
    description: Download a copy of the emergency protocol
    category: document_management
    parameters:
    - name: doc_title
      type: string
      description: The title of the document to be downloaded
      required: true
    example_usage:
    - download_protocol(doc_title='Emergency Evacuation Plan')
  environment:
    name: biocontainment_facility_system
    description: Secure environment for managing biocontainment facility documents
    variables:
    - name: DOCUMENT_STORAGE_URL
      value: 'https://secure.biocontainment.org/documents'
      description: URL to the document storage system
      type: string
    - name: EMERGENCY_CONTACT
      value: 'emergency@biocontainment.org'
      description: Contact email for emergencies
      type: string
    settings:
      document_format: PDF
      max_document_size_mb: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - biocontainment.org
    - '*.trusted-partner.org'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: admin@biocontainment.org
    current_user_name: Facility Administrator
    facility_name: Biocontainment Facility
    timezone: UTC
    business_hours: 24/7
  system_info:
    platform_version: '3.0'
    available_libraries:
    - requests
    - yaml
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true