name: biodiversity_optimizer
display_name: Biodiversity Optimizer
description: This scenario involves optimizing biodiversity through pest management and biological control measures. It includes obtaining pest reports, performing specific biological control actions, and listing available bio control measures to maintain ecological balance.
category: environmental_management
complexity_level: 3
estimated_duration: 45
required_permissions:
- environmental_data_access
- bio_control_execution
dependencies: []
generation_weight: 1.5
sample_actions:
- get_pest_report
- perform_bio_control
- list_bio_controls
metadata:
  selection_way: random
  selection_num: 2
tags:
- biodiversity
- pest_management
- ecological_balance
context:
  available_tools:
  - name: get_pest_report
    display_name: Get Pest Report
    description: Retrieve detailed reports on pest populations and their impact on biodiversity.
    category: data_analysis
    parameters: []
    example_usage:
    - get_pest_report()
    common_errors:
    - No data available
  - name: perform_bio_control
    display_name: Perform Biological Control
    description: Execute a specific biological control measure to manage pest populations.
    category: action_execution
    parameters:
    - name: name
      type: string
      description: The name of the biological control.
      required: true
    example_usage:
    - perform_bio_control(name='ladybug_release')
    common_errors:
    - Invalid control name
  - name: list_bio_controls
    display_name: List Biological Controls
    description: List all available biological control measures for pest management.
    category: information_retrieval
    parameters: []
    example_usage:
    - list_bio_controls()
  environment:
    name: biodiversity_management_system
    description: A system designed to manage and optimize biodiversity through pest control and ecological balance strategies.
    variables:
    - name: PEST_DATA_API_URL
      value: 'https://api.biodiversity.org/pest-data'
      description: API endpoint for accessing pest data
      type: string
    - name: MAX_CONTROL_MEASURES
      value: 10
      description: Maximum number of control measures that can be executed simultaneously
      type: integer
    settings:
      report_format: JSON
      max_pest_report_age_days: 7
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - biodiversity.org
    - '*.trusted-environmental-partner.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: ecologist@example.com
    current_user_name: Environmental Scientist
    organization_name: EcoBalance Institute
    timezone: UTC+0
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - numpy
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true