name: bioelectric_field_generator
display_name: Bioelectric Field Generator
description: This scenario involves managing and configuring a Bioelectric Field Generator device. It includes fetching calibration instructions and updating device settings such as power level and frequency. The goal is to ensure the device operates within optimal parameters for safety and efficiency.
category: device_management
complexity_level: 3
estimated_duration: 30
required_permissions:
- device_control_access
- calibration_data_access
dependencies: []
generation_weight: 1.5
sample_actions:
- get_calibration_instructions
- set_device_settings
metadata:
  selection_way: random
  selection_num: 2
tags:
- bioelectric
- device_configuration
- calibration
context:
  available_tools:
  - name: get_calibration_instructions
    display_name: Get Calibration Instructions
    description: Fetch the instructions stored in the system for device calibration.
    category: calibration
    parameters: []
    example_usage:
    - get_calibration_instructions()
  - name: set_device_settings
    display_name: Set Device Settings
    description: Update the device settings for the Bioelectric Field Generator.
    category: device_management
    parameters:
    - name: power_level
      type: integer
      description: Power level setting, ranging from 1 to 10.
      required: true
    - name: frequency
      type: number
      description: Frequency setting in Hz.
      required: true
    example_usage:
    - set_device_settings(power_level=5, frequency=60.0)
  environment:
    name: bioelectric_lab
    description: Laboratory environment equipped with tools for managing bioelectric devices.
    variables:
    - name: DEVICE_MANUAL_URL
      value: 'https://www.example.com/device-manual'
      description: URL to the device manual.
      type: string
    - name: MAX_POWER_LEVEL
      value: 10
      description: Maximum power level setting for the device.
      type: integer
    settings:
      calibration_mode: automatic
      default_frequency: 50.0
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - example.com
    - '*.trusted-device.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: technician@example.com
    current_user_name: Device Technician
    company_name: BioTech Solutions Inc.
    timezone: UTC+1
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - numpy
    - scipy
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true