name: bioelectricity_harvester
display_name: Bioelectricity Harvester
description: Manages and optimizes the operation of bioelectricity harvesting systems. This includes connecting to devices, adjusting settings, listing reports and modules, and managing module operations. Ensures efficient energy management and system configuration.
category: energy_management
complexity_level: 3
estimated_duration: 30
required_permissions:
- device_control_access
- system_configuration_access
dependencies: []
generation_weight: 1.5
sample_actions:
- connect_device
- adjust_settings
- list_reports
- configure_settings
- list_modules
- disable_module
- deactivate_module
metadata:
  selection_way: random
  selection_num: 3
tags:
- energy
- device_management
- system_configuration
context:
  available_tools:
  - name: connect_device
    display_name: Connect Device
    description: Connect to the existing devices.
    category: device_management
    parameters: []
    example_usage:
    - connect_device()
  - name: adjust_settings
    display_name: Adjust Settings
    description: Adjust the settings of the connected home energy device.
    category: system_configuration
    parameters:
    - name: setting
      type: string
      description: The setting to adjust, such as 'energy_saving_mode'.
      required: true
    - name: value
      type: string
      description: The value to set, such as 'true' or 'false'.
      required: true
    example_usage:
    - adjust_settings(setting='energy_saving_mode', value='true')
  - name: list_reports
    display_name: List Reports
    description: List recent reports.
    category: reporting
    parameters: []
    example_usage:
    - list_reports()
  - name: configure_settings
    display_name: Configure Settings
    description: Configure the settings of electricity management systems.
    category: system_configuration
    parameters:
    - name: system_url
      type: string
      description: The URL of the electricity management system.
      required: true
    - name: settings_mode
      type: string
      description: The mode to set the system to. Example modes include 'HighDiversionMode'.
      required: true
    example_usage:
    - configure_settings(system_url='http://example.com', settings_mode='HighDiversionMode')
  - name: list_modules
    display_name: List Modules
    description: List all available modules in the Bioelectricity Harvester.
    category: module_management
    parameters: []
    example_usage:
    - list_modules()
  - name: disable_module
    display_name: Disable Module
    description: Disables the specified module to cease its operation.
    category: module_management
    parameters:
    - name: module_id
      type: string
      description: The ID of the module to disable.
      required: true
    example_usage:
    - disable_module(module_id='mod123')
  - name: deactivate_module
    display_name: Deactivate Module
    description: Deactivate a specified module.
    category: module_management
    parameters:
    - name: module_name
      type: string
      description: The name of the module.
      required: true
    example_usage:
    - deactivate_module(module_name='ModuleA')
  environment:
    name: bioelectricity_management_system
    description: Environment for managing bioelectricity harvesting and energy systems.
    variables:
    - name: SYSTEM_API_URL
      value: 'https://api.bioharvester.com'
      description: Base URL for the system API
      type: string
    - name: MAX_MODULES
      value: 10
      description: Maximum number of modules that can be managed simultaneously
      type: integer
    settings:
      report_format: JSON
      max_connections: 5
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - bioharvester.com
    - '*.trusted-energy.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: admin@bioharvester.com
    current_user_name: System Administrator
    company_name: BioHarvester Inc.
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '1.0'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true