name: bioluminescence_harvester
display_name: BioLuminescence Harvester
description: This scenario involves managing and optimizing the bioluminescence harvesting system. The tasks include executing scripts, adjusting harvest rates, sharing data, and modifying harvesting plans. The goal is to efficiently manage resources and maximize energy output while maintaining system integrity.
category: energy_management
complexity_level: 3
estimated_duration: 45
required_permissions:
- script_execution_access
- data_sharing_access
- system_control_access
dependencies: []
generation_weight: 1.5
sample_actions:
- list_scripts
- execute_script
- gather_data
- share_data
- adjust_harvest_rate
- check_system_status
- list_units
- adjust_power_setting
- get_harvest_data
- adjust_harvesting_plan
metadata:
  selection_way: random
  selection_num: 5
tags:
- energy
- resource_management
- bioluminescence
context:
  available_tools:
  - name: execute_script
    display_name: Execute Script
    description: Run a specified script within the system
    category: system_operations
    parameters:
    - name: file_name_or_path
      type: string
      description: The name or path of the script to be executed
      required: true
    example_usage:
    - execute_script(file_name_or_path='scripts/harvest_control.py')
    common_errors:
    - Script not found
    - Execution permission denied
  - name: adjust_harvest_rate
    display_name: Adjust Harvest Rate
    description: Modify the harvesting rate to control energy output
    category: energy_management
    parameters:
    - name: rate
      type: string
      description: Desired harvest rate ('low', 'standard', 'high')
      required: true
    example_usage:
    - adjust_harvest_rate(rate='high')
    common_errors:
    - Invalid rate value
  - name: share_data
    display_name: Share Data
    description: Share datasets with partners
    category: data_management
    parameters:
    - name: dataset_id
      type: string
      description: The id of the dataset to be shared
      required: true
    - name: recipient
      type: string
      description: The recipient of the dataset
      required: true
    example_usage:
    - share_data(dataset_id='dataset123', recipient='partner@example.com')
    common_errors:
    - Dataset not found
    - Unauthorized recipient
  environment:
    name: bioluminescence_harvesting_system
    description: A system environment for managing bioluminescence harvesting operations
    variables:
    - name: HARVEST_RATE_LIMIT
      value: 'high'
      description: Maximum allowable harvest rate
      type: string
    - name: DATA_SHARE_URL
      value: 'https://data.example.com/share'
      description: URL for data sharing portal
      type: string
    settings:
      max_units: 50
      default_power_setting: optimal
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - example.com
    - '*.trusted-partner.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_operator_email: operator@example.com
    current_operator_name: System Operator
    company_name: BioHarvest Inc.
    timezone: UTC+0
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - numpy
    - pandas
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true