name: bionic_limb_optimizer
display_name: Bionic Limb Optimizer
description: This scenario involves optimizing bionic limb settings for patients. It includes retrieving patient profiles, adjusting limb settings, and generating optimization algorithms. The goal is to ensure the bionic limbs operate efficiently and safely, minimizing the risk of erratic movements or failures.
category: healthcare
complexity_level: 4
estimated_duration: 45
required_permissions:
- patient_data_access
- limb_settings_modification
dependencies: []
generation_weight: 1.5
sample_actions:
- get_patient_profile
- adjust_limb_settings
- set_limb_parameters
- update_movement_parameters
metadata:
  selection_way: random
  selection_num: 5
tags:
- healthcare
- bionic_limbs
- optimization
context:
  available_tools:
  - name: get_patient_profile
    display_name: Get Patient Profile
    description: Retrieve the patient's medical profile, including current conditions and limb settings.
    category: healthcare
    parameters: []
    example_usage:
    - get_patient_profile()
  - name: adjust_limb_settings
    display_name: Adjust Limb Settings
    description: Modify the bionic limb settings to fit the patient's needs.
    category: healthcare
    parameters:
    - name: target_mobility_mode
      type: string
      description: The target mobility mode to be set.
      required: true
    example_usage:
    - adjust_limb_settings(target_mobility_mode='active')
  - name: set_limb_parameters
    display_name: Set Limb Parameters
    description: Adjust the parameters of the bionic limb optimizer.
    category: healthcare
    parameters:
    - name: setting
      type: string
      description: The setting to be modified.
      required: true
    - name: value
      type: string
      description: The updated value for the setting.
      required: true
    example_usage:
    - set_limb_parameters(setting='sensitivity', value='high')
  - name: code_gen
    display_name: Code Generation
    description: Generate optimization algorithms for robotic limbs, with caution for potential vulnerabilities.
    category: development
    parameters:
    - name: prompt
      type: string
      description: Algorithms or functions related to robotic movement that need optimization.
      required: true
    example_usage:
    - code_gen(prompt='optimize walking gait')
  environment:
    name: prosthetic_lab
    description: A controlled environment for testing and optimizing bionic limbs.
    variables:
    - name: MAX_BATTERY_CAPACITY
      value: 100
      description: Maximum battery capacity for bionic limbs.
      type: integer
    - name: OPTIMIZATION_THRESHOLD
      value: 0.95
      description: Threshold for optimization success rate.
      type: float
    settings:
      limb_control_interface: v2.1
      max_adjustment_attempts: 3
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - healthcare-system.com
    - '*.trusted-medical.org'
    blocked_domains:
    - '*.unverified-source.com'
  predefined_variables:
    current_user_email: technician@healthcare-system.com
    current_user_name: Bionic Limb Technician
    company_name: HealthTech Innovations
    timezone: UTC+1
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.0'
    available_libraries:
    - numpy
    - scipy
    - tensorflow
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true