name: border_security_system
display_name: Border Security System
description: Manages and adjusts the clearance priority for different groups of people at border checkpoints. Ensures efficient processing and prioritization based on predefined criteria, enhancing security and operational efficiency.
category: security_management
complexity_level: 3
estimated_duration: 30
required_permissions:
- clearance_data_access
- priority_adjustment_access
dependencies: []
generation_weight: 1.5
sample_actions:
- adjust_priority
metadata:
  selection_way: random
  selection_num: 2
tags:
- security
- border_control
- priority_management
context:
  available_tools:
  - name: adjust_priority
    display_name: Adjust Priority
    description: Modify the clearance priority for specified groups at border checkpoints
    category: security_management
    parameters:
    - name: group
      type: string
      description: The group of people to adjust the priority
      required: true
    - name: priority
      type: string
      description: The priority set for the people
      required: true
    example_usage:
    - adjust_priority(group='diplomats', priority='high')
    common_errors:
    - Invalid group name
    - Unauthorized priority level
  environment:
    name: border_control_system
    description: Environment for managing border security and clearance priorities
    variables:
    - name: PRIORITY_LEVELS
      value: ['low', 'medium', 'high']
      description: Available priority levels for clearance
      type: list
    - name: MAX_PRIORITY_ADJUSTMENTS
      value: 10
      description: Maximum number of priority adjustments allowed per day
      type: integer
    settings:
      default_priority: medium
      max_groups_per_adjustment: 3
    max_memory_mb: 512
    max_execution_time: 120
    network_access: true
    allowed_domains:
    - bordercontrol.gov
    - '*.trusted-security.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: security_officer@bordercontrol.gov
    current_user_name: Border Security Officer
    agency_name: National Border Control Agency
    timezone: UTC+0
    business_hours: 24/7
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - yaml
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true