name: brainwave_educator
display_name: Brainwave Educator
description: Assists educators in creating comprehensive lesson plans by following specific requirements. This tool ensures that lesson plans are tailored to meet educational standards and objectives, providing a structured approach to teaching.
category: education
complexity_level: 3
estimated_duration: 45
required_permissions:
- curriculum_data_access
dependencies: []
generation_weight: 1.5
sample_actions:
- create_lesson_plan
metadata:
  selection_way: random
  selection_num: 2
tags:
- education
- lesson_planning
- teaching
context:
  available_tools:
  - name: create_lesson_plan
    display_name: Create Lesson Plan
    description: Generate lesson plans based on specified requirements
    category: education
    parameters:
    - name: requirements
      type: string
      description: The requirements for lesson creation
      required: true
    example_usage:
    - create_lesson_plan(requirements='Cover the basics of photosynthesis for grade 5 students')
    common_errors:
    - Missing requirements
    - Ambiguous requirements
  environment:
    name: educational_platform
    description: A platform environment equipped with educational resources and planning tools
    variables:
    - name: CURRICULUM_GUIDELINES_URL
      value: 'https://www.example.com/curriculum-guidelines'
      description: URL to the curriculum guidelines page
      type: string
    - name: MAX_LESSON_DURATION
      value: 60
      description: Maximum duration for a single lesson in minutes
      type: integer
    settings:
      lesson_format: DOCX
      max_lessons_per_plan: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - example.com
    - '*.educational-partner.com'
    blocked_domains:
    - '*.unverified-source.com'
  predefined_variables:
    current_user_email: educator@example.com
    current_user_name: Educator
    institution_name: Global Learning Institute
    timezone: UTC+1
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true