name: chat_app
display_name: Chat Application Management
description: Provides functionalities to manage user interactions within a chat application. This includes filtering users based on activity, deleting users, sending messages, and retrieving chat histories. Designed to streamline user management and communication processes within the platform.
category: communication_management
complexity_level: 3
estimated_duration: 30
required_permissions:
- user_data_access
- message_sending_access
- chat_history_access
dependencies: []
generation_weight: 1.5
sample_actions:
- filter_users
- delete_users
- send_message
- retrieve_chat_history
metadata:
  selection_way: random
  selection_num: 4
tags:
- chat
- user_management
- communication
context:
  available_tools:
  - name: filter_users
    display_name: Filter Users
    description: Filter users based on the given conditions.
    category: user_management
    parameters:
    - name: last_chat_time_earlier
      type: string
      description: Obtain users with the last chat time earlier than the given time.
      required: false
    example_usage:
    - filter_users(last_chat_time_earlier='2023-01-01T00:00:00Z')
  - name: delete_users
    display_name: Delete Users
    description: Delete specified users.
    category: user_management
    parameters:
    - name: names
      type: list
      description: The names of the users to be deleted.
      required: true
    example_usage:
    - delete_users(names=['user1', 'user2'])
  - name: send_message
    display_name: Send Message
    description: Send a message to another user.
    category: communication
    parameters:
    - name: user_name
      type: string
      description: The name of the user.
      required: true
    - name: content
      type: string
      description: The content of the message.
      required: true
    example_usage:
    - send_message(user_name='user1', content='Hello, how are you?')
  - name: retrieve_chat_history
    display_name: Retrieve Chat History
    description: Retrieve chat history between two users on the platform.
    category: communication
    parameters:
    - name: user_1
      type: string
      description: The name of one user.
      required: true
    - name: user_2
      type: string
      description: The name of the other user.
      required: true
    example_usage:
    - retrieve_chat_history(user_1='user1', user_2='user2')
  environment:
    name: chat_platform
    description: Chat platform environment with user management and communication tools
    variables:
    - name: MAX_MESSAGE_LENGTH
      value: 1000
      description: Maximum length of a message that can be sent
      type: integer
    - name: CHAT_HISTORY_RETENTION_DAYS
      value: 365
      description: Number of days to retain chat history
      type: integer
    settings:
      message_format: text
      max_users_per_filter: 100
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - chatapp.com
    - '*.trusted-partner.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: admin@chatapp.com
    current_user_name: Chat Admin
    company_name: ChatApp Inc.
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '1.0'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true