name: cloud_ionizer
display_name: Cloud Ionizer
description: Provides tools to manage and organize files within a cloud storage environment. This includes listing all files, cleaning up unnecessary files, and deleting specific files as needed. Ensures efficient storage management and organization.
category: cloud_management
complexity_level: 3
estimated_duration: 15
required_permissions:
- cloud_storage_access
- file_management_access
dependencies: []
generation_weight: 1.0
sample_actions:
- list_files
- clean_up_file
- delete_file
metadata:
  selection_way: random
  selection_num: 3
tags:
- cloud
- storage
- file_management
context:
  available_tools:
  - name: list_files
    display_name: List Files
    description: List all files in the cloud storage
    category: cloud_management
    parameters: []
    example_usage:
    - list_files()
  - name: clean_up_file
    display_name: Clean Up File
    description: Clean up all files from the cloud storage
    category: cloud_management
    parameters: []
    example_usage:
    - clean_up_file()
  - name: delete_file
    display_name: Delete File
    description: Delete the specified file from the cloud storage
    category: cloud_management
    parameters:
    - name: file_name
      type: string
      description: The name of the file to be deleted
      required: true
    example_usage:
    - delete_file(file_name='document.txt')
  environment:
    name: cloud_storage_environment
    description: Cloud storage environment with file management capabilities
    variables:
    - name: STORAGE_API_URL
      value: 'https://api.cloudstorage.com'
      description: Base URL for the cloud storage API
      type: string
    - name: MAX_STORAGE_CAPACITY_GB
      value: 1000
      description: Maximum storage capacity in gigabytes
      type: integer
    settings:
      file_retention_policy: 30_days
      max_file_size_mb: 100
    max_memory_mb: 512
    max_execution_time: 120
    network_access: true
    allowed_domains:
    - cloudstorage.com
    - '*.trusted-cloud.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: admin@cloudstorage.com
    current_user_name: Cloud Admin
    company_name: CloudStorage Inc.
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '1.0'
    available_libraries:
    - boto3
    - os
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true