name: cyber_incident_response
display_name: Cyber Incident Response
description: Facilitates the management and response to cyber incidents by providing tools to report incidents, adjust network settings, and generate automation scripts. Aims to enhance the efficiency and effectiveness of incident response teams in mitigating and resolving cyber threats.
category: cybersecurity
complexity_level: 3
estimated_duration: 45
required_permissions:
- incident_report_access
- network_configuration_access
dependencies: []
generation_weight: 1.5
sample_actions:
- report_incident
- list_serves_and_logs
- modify_dns_settings
- generate_script
- get_all_incident_reports
- read_incident_information
metadata:
  selection_way: random
  selection_num: 5
tags:
- cybersecurity
- incident_management
- network_security
context:
  available_tools:
  - name: report_incident
    display_name: Report Incident
    description: Submit an incident report to the relevant authorities
    category: incident_management
    parameters:
    - name: title
      type: string
      description: The title of the incident
      required: true
    - name: description
      type: string
      description: A detailed description of the incident
      required: true
  - name: list_serves_and_logs
    display_name: List Servers and Logs
    description: List current DNS servers and incident logs
    category: network_management
    parameters: []
  - name: modify_dns_settings
    display_name: Modify DNS Settings
    description: Adjust DNS server settings to optimize network performance
    category: network_management
    parameters:
    - name: new_primary_dns
      type: string
      description: New primary DNS server address
      required: true
  - name: generate_script
    display_name: Generate Script
    description: Generate automation scripts based on specified objectives
    category: automation
    parameters:
    - name: objective
      type: string
      description: A description of the task that the script needs to accomplish
      required: true
  - name: get_all_incident_reports
    display_name: Get All Incident Reports
    description: Retrieve the details of all recorded cyber incident reports
    category: incident_management
    parameters: []
  - name: read_incident_information
    display_name: Read Incident Information
    description: Read the information of existing incidents
    category: incident_management
    parameters: []
  environment:
    name: secure_network_environment
    description: A secure network environment for managing and responding to cyber incidents
    variables:
    - name: INCIDENT_REPORT_URL
      value: 'https://www.example.com/incident-report'
      description: URL to submit incident reports
      type: string
    - name: DNS_SETTINGS_API
      value: 'https://api.example.com/dns-settings'
      description: API endpoint for DNS settings management
      type: string
    settings:
      incident_report_format: JSON
      max_dns_entries: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - example.com
    - '*.trusted-security.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: security@example.com
    current_user_name: Cyber Security Analyst
    company_name: SecureTech Inc.
    timezone: UTC
    business_hours: 24/7
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - json
    - yaml
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true