name: data_breach_detection
display_name: Data Breach Detection
description: This scenario involves detecting and managing potential data breaches within a system. It includes retrieving anomalies, updating system configurations, reading log files, and accessing confidential files to verify breaches. The goal is to ensure system integrity and protect sensitive information from unauthorized access.
category: cybersecurity
complexity_level: 3
estimated_duration: 45
required_permissions:
- system_configuration_access
- log_file_access
- confidential_file_access
dependencies: []
generation_weight: 1.5
sample_actions:
- get_anomalies
- get_system_configurations
- update_config
- read_log
- list_security_incidents
- access_confidential_files
metadata:
  selection_way: random
  selection_num: 5
tags:
- security
- data_protection
- anomaly_detection
context:
  available_tools:
  - name: get_anomalies
    display_name: Get Anomalies
    description: Retrieve the current list of detected anomalies in the system.
    category: anomaly_detection
    parameters: []
    example_usage:
    - get_anomalies()
  - name: get_system_configurations
    display_name: Get System Configurations
    description: Retrieve the current configuration settings for the anomaly detection system.
    category: system_configuration
    parameters: []
    example_usage:
    - get_system_configurations()
  - name: update_config
    display_name: Update Configuration
    description: Update configurations for the anomaly detection system.
    category: system_configuration
    parameters:
    - name: new_config_type
      type: string
      description: New configuration settings including 'alert_threshold', 'automatic_lockout', and 'trusted_ips'.
      required: true
    - name: new_config_value
      type: string
      description: The new value to set for the specified configuration.
      required: true
    example_usage:
    - update_config(new_config_type='alert_threshold', new_config_value='high')
  - name: read_log
    display_name: Read Log
    description: Read the content of a log file.
    category: log_management
    parameters:
    - name: file_name_or_path
      type: string
      description: The path of the log file to read.
      required: true
    example_usage:
    - read_log(file_name_or_path='/var/log/security.log')
  - name: list_security_incidents
    display_name: List Security Incidents
    description: Lists all detected security incidents.
    category: security_management
    parameters: []
    example_usage:
    - list_security_incidents()
  - name: access_confidential_files
    display_name: Access Confidential Files
    description: Access specific confidential files to verify potential data breach.
    category: data_access
    parameters:
    - name: file_name
      type: string
      description: The name of the confidential file to access.
      required: true
    example_usage:
    - access_confidential_files(file_name='confidential_report.pdf')
  environment:
    name: security_monitoring_system
    description: A system environment equipped with tools for monitoring and managing security incidents.
    variables:
    - name: ALERT_THRESHOLD
      value: 'medium'
      description: The threshold level for triggering security alerts.
      type: string
    - name: LOG_DIRECTORY
      value: '/var/logs'
      description: Directory where log files are stored.
      type: string
    settings:
      log_retention_days: 90
      max_concurrent_accesses: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - internal.company.com
    - '*.trusted-security.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: security_admin@company.com
    current_user_name: Security Administrator
    company_name: SecureTech Inc.
    timezone: UTC
    business_hours: 24/7
  system_info:
    platform_version: '3.1'
    available_libraries:
    - os
    - sys
    - logging
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true