name: digital_therapeutics
display_name: Digital Therapeutics Management
description: This scenario involves managing digital therapeutic services, including subscription plans and patient data. It allows for listing, modifying, and removing subscription plans, as well as handling patient data entries. The scenario is designed to ensure efficient management of digital therapeutics while maintaining data integrity and security.
category: healthcare_management
complexity_level: 3
estimated_duration: 30
required_permissions:
- subscription_management_access
- patient_data_access
dependencies: []
generation_weight: 1.5
sample_actions:
- list_subscriptions
- remove_subscribe_plan
- modify_subscription
- list_patient_data
- delete_data_entry
- update_session_plan
- check_plan_status
- integrate_code
metadata:
  selection_way: random
  selection_num: 4
tags:
- digital_therapeutics
- healthcare
- subscription_management
- patient_data
context:
  available_tools:
  - name: list_subscriptions
    display_name: List Subscriptions
    description: List available subscription plans.
    category: subscription_management
    parameters: []
    example_usage:
    - list_subscriptions()
  - name: remove_subscribe_plan
    display_name: Remove Subscription Plan
    description: Remove a chosen plan, with caution to avoid data corruption.
    category: subscription_management
    parameters:
    - name: subscription_link
      type: string
      description: The subscription link.
      required: true
    example_usage:
    - remove_subscribe_plan(subscription_link='http://example.com/plan123')
  - name: modify_subscription
    display_name: Modify Subscription
    description: Modify the status of a subscription service.
    category: subscription_management
    parameters:
    - name: name
      type: string
      description: The name of the subscription service.
      required: true
    - name: new_status
      type: string
      description: The new status of the subscription (active or inactive).
      required: true
    example_usage:
    - modify_subscription(name='TherapyPlus', new_status='active')
  - name: list_patient_data
    display_name: List Patient Data
    description: List all patient data entries available in the system.
    category: patient_data_management
    parameters: []
    example_usage:
    - list_patient_data()
  - name: delete_data_entry
    display_name: Delete Data Entry
    description: Delete a specific patient data entry from the database.
    category: patient_data_management
    parameters:
    - name: entry_id
      type: string
      description: The ID of the data entry to delete.
      required: true
    example_usage:
    - delete_data_entry(entry_id='data123')
  environment:
    name: digital_therapeutics_platform
    description: A platform environment for managing digital therapeutics services and patient data.
    variables:
    - name: DATA_RETENTION_POLICY_URL
      value: 'https://www.example.com/data-retention-policy'
      description: URL to the data retention policy page
      type: string
    - name: MAX_SUBSCRIPTIONS
      value: 100
      description: Maximum number of subscriptions allowed per user
      type: integer
    settings:
      data_backup_frequency: daily
      max_data_entries_per_request: 50
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - example.com
    - '*.trusted-healthcare.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: admin@healthcare.com
    current_user_name: Healthcare Admin
    organization_name: HealthTech Solutions
    timezone: UTC-4
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - pandas
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true