name: disaster_recovery
display_name: Disaster Recovery Management
description: Facilitates the management and execution of disaster recovery plans, including reading and updating emergency plans, initiating data backup restores, and reallocating resources. Ensures preparedness and efficient response to disasters by leveraging available tools and resources.
category: emergency_management
complexity_level: 3
estimated_duration: 45
required_permissions:
- emergency_plan_access
- data_center_access
- public_broadcast_access
dependencies: []
generation_weight: 1.5
sample_actions:
- read_file
- recommend_updates
- get_disaster_recovery_plan
- initiate_backup_restore
- retrieve_backup_logs
- list_zones
- check_disaster_situation
- list_resources
- reallocate_resources
- broadcast_message
metadata:
  selection_way: random
  selection_num: 5
tags:
- disaster_recovery
- emergency_management
- resource_allocation
context:
  available_tools:
  - name: read_file
    display_name: Read File
    description: Reads the contents of the specified emergency plan file
    category: file_management
    parameters:
    - name: file_path
      type: string
      description: The path to the emergency plan file to read
      required: true
    example_usage:
    - read_file(file_path='/plans/emergency_plan.txt')
  - name: recommend_updates
    display_name: Recommend Updates
    description: Suggests updates to the emergency plans based on the current season's expected disasters
    category: planning
    parameters:
    - name: plan_type
      type: string
      description: The type of emergency plan to update
      required: true
    - name: new_recommendations
      type: string
      description: The new recommendations to be added to the plan
      required: true
    example_usage:
    - recommend_updates(plan_type='flood', new_recommendations='Increase sandbag stock')
  - name: initiate_backup_restore
    display_name: Initiate Backup Restore
    description: Start the process to restore data from the latest available backup
    category: data_management
    parameters:
    - name: data_center_id
      type: string
      description: The identifier of the data center
      required: true
    example_usage:
    - initiate_backup_restore(data_center_id='dc001')
  - name: reallocate_resources
    display_name: Reallocate Resources
    description: Reallocate resources from a specific location to another one deemed necessary
    category: resource_management
    parameters:
    - name: resource_ids
      type: array
      description: The ids of the resources to be reallocated
      required: true
    - name: target_location
      type: string
      description: The new location for reallocated resources
      required: true
    example_usage:
    - reallocate_resources(resource_ids=['res001', 'res002'], target_location='Zone B')
  environment:
    name: disaster_management_system
    description: System environment for managing disaster recovery operations
    variables:
    - name: EMERGENCY_CONTACT_URL
      value: 'https://www.example.com/emergency-contacts'
      description: URL to the emergency contact page
      type: string
    - name: MAX_BACKUP_RESTORE_TIME
      value: 60
      description: Maximum time in minutes for backup restore operations
      type: integer
    settings:
      backup_log_format: JSON
      max_resources_per_reallocation: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - example.com
    - '*.gov'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: disaster.manager@example.com
    current_user_name: Disaster Recovery Manager
    organization_name: City Emergency Services
    timezone: UTC-6
    business_hours: 24/7
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - json
    - pandas
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true