name: ec
display_name: Economic and Health Tools
description: A comprehensive suite of tools designed to provide economic and health-related information and calculations. This includes fetching financial data, weather forecasts, health metrics, and more, to assist users in making informed decisions.
category: information_services
complexity_level: 3
estimated_duration: 30
required_permissions:
- financial_data_access
- health_data_access
dependencies: []
generation_weight: 1.5
sample_actions:
- fetch_latest_nav
- forecast_weather
- calculate_bmi
- get_stock_time_series
metadata:
  selection_way: random
  selection_num: 5
tags:
- finance
- health
- weather
- data_analysis
context:
  available_tools:
  - name: fetch_latest_nav
    display_name: Fetch Latest NAV
    description: Provides the latest NAV information of all mutual funds in India from AMFI.
    category: finance
    parameters: []
    example_usage:
    - fetch_latest_nav()
  - name: forecast_weather
    display_name: Forecast Weather
    description: Returns weather forecasts and alerts for up to 14 days.
    category: weather
    parameters:
    - name: q
      type: string
      description: Query parameter for location (e.g., city name, coordinates)
      required: true
    - name: days
      type: string
      description: Number of days for the forecast (1-14)
      required: true
    example_usage:
    - forecast_weather(q='Paris', days='5')
  - name: calculator
    display_name: Calculator
    description: Calculates the result of a mathematical expression.
    category: utilities
    parameters:
    - name: input_query
      type: string
      description: The mathematical expression to evaluate
      required: true
    example_usage:
    - calculator(input_query='What is 2 + 2?')
  - name: get_bmi
    display_name: Get BMI
    description: Calculates the Body Mass Index of a person.
    category: health
    parameters:
    - name: age
      type: string
      description: Age of the person
      required: true
    - name: height
      type: string
      description: Height of the person
      required: true
    - name: weight
      type: string
      description: Weight of the person
      required: true
    example_usage:
    - get_bmi(age='30', height='175', weight='70')
  environment:
    name: economic_health_platform
    description: A platform providing tools for economic and health data analysis.
    variables:
    - name: API_KEY
      value: 'your_api_key_here'
      description: API key for accessing external data services
      type: string
    settings:
      data_format: JSON
      max_requests_per_minute: 60
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - financeapi.com
    - weatherapi.com
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: user@example.com
    current_user_name: Data Analyst
    company_name: DataCorp Inc.
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '1.0'
    available_libraries:
    - requests
    - numpy
    - pandas
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true