name: emergency_alert
display_name: Emergency Alert System
description: This scenario involves managing an emergency alert system, including listing available systems, activating alerts, retrieving alert details, sending alert messages, and updating alert statuses. It is designed to ensure that emergency alerts are handled efficiently and accurately, providing timely information to relevant parties.
category: emergency_management
complexity_level: 3
estimated_duration: 30
required_permissions:
- alert_management_access
- message_sending_access
dependencies: []
generation_weight: 1.5
sample_actions:
- list_alert_systems
- activate_alert_system
- retrieve_alert
- send_alert_message
- get_current_alerts
- list_alerts
- update_alert_status
- delete_alert_entry
metadata:
  selection_way: random
  selection_num: 4
tags:
- emergency
- alerts
- communication
context:
  available_tools:
  - name: list_alert_systems
    display_name: List Alert Systems
    description: Retrieve a list of available alert systems and their activation status.
    category: system_management
    parameters: []
    example_usage:
    - list_alert_systems()
  - name: activate_alert_system
    display_name: Activate Alert System
    description: Activate a given alert system using its activation code.
    category: system_management
    parameters:
    - name: system_name
      type: string
      description: Name of the alert system to be activated.
      required: true
    - name: activation_code
      type: string
      description: Activation code for the alert system.
      required: true
    example_usage:
    - activate_alert_system(system_name='FireAlarm', activation_code='12345')
  - name: retrieve_alert
    display_name: Retrieve Alert
    description: Retrieve detailed information about a specific alert given its ID.
    category: information_retrieval
    parameters:
    - name: alert_id
      type: string
      description: The ID of the alert to retrieve.
      required: true
    example_usage:
    - retrieve_alert(alert_id='alert123')
  - name: send_alert_message
    display_name: Send Alert Message
    description: Send a text message alert to a specified contact.
    category: communication
    parameters:
    - name: contact
      type: string
      description: The name of the contact to send the alert to.
      required: true
    - name: message
      type: string
      description: The alert message to be sent.
      required: true
    example_usage:
    - send_alert_message(contact='John Doe', message='Emergency evacuation required.')
  environment:
    name: alert_management_platform
    description: Platform for managing and disseminating emergency alerts.
    variables:
    - name: ALERT_API_ENDPOINT
      value: 'https://api.alertsystem.com'
      description: API endpoint for alert management
      type: string
    - name: MAX_ALERT_DURATION
      value: 24
      description: Maximum duration for an alert in hours
      type: integer
    settings:
      alert_message_format: SMS
      max_alerts_per_hour: 100
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - alertsystem.com
    - '*.trusted-alerts.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: alertmanager@example.com
    current_user_name: Alert Manager
    organization_name: City Emergency Services
    timezone: UTC-6
    business_hours: 24/7
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true