name: emergency_language_translation
display_name: Emergency Language Translation
description: Facilitates the translation of emergency messages and highlights critical keywords to ensure effective communication in crisis situations. This scenario is designed to support emergency response teams by providing accurate translations and emphasizing important information in multilingual contexts.
category: emergency_response
complexity_level: 3
estimated_duration: 30
required_permissions:
- translation_service_access
- keyword_extraction_access
dependencies: []
generation_weight: 1.5
sample_actions:
- translate_messages
- filter_critical_keywords
metadata:
  selection_way: random
  selection_num: 2
tags:
- translation
- emergency
- communication
context:
  available_tools:
  - name: translate_messages
    display_name: Translate Messages
    description: Translate all messages in the system to the desired language
    category: language_services
    parameters: []
    example_usage:
    - translate_messages()
    common_errors:
    - Unsupported language
    - Network failure
  - name: filter_critical_keywords
    display_name: Filter Critical Keywords
    description: Extract critical keywords that need to be highlighted in translations from all messages in the system
    category: language_services
    parameters: []
    example_usage:
    - filter_critical_keywords()
    common_errors:
    - No keywords found
  environment:
    name: emergency_communication_platform
    description: Platform for managing and translating emergency communications
    variables:
    - name: TRANSLATION_API_URL
      value: 'https://api.translation-service.com'
      description: URL for the translation API
      type: string
    - name: SUPPORTED_LANGUAGES
      value: ['en', 'es', 'fr', 'de', 'zh']
      description: List of supported languages for translation
      type: list
    settings:
      max_translation_length: 5000
      highlight_color: red
    max_memory_mb: 512
    max_execution_time: 120
    network_access: true
    allowed_domains:
    - translation-service.com
    - '*.gov'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_role: Emergency Coordinator
    organization_name: Global Crisis Response
    timezone: UTC
    emergency_contact_email: emergency@crisisresponse.org
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - nltk
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true