name: exoplanet_colonization_mission
display_name: Exoplanet Colonization Mission
description: This scenario involves managing the logistics and operations of a mission to colonize an exoplanet. Tasks include communication among crew members, managing power and resources, and handling landing procedures. The agent must ensure efficient operation and safety of the mission by coordinating various activities and maintaining optimal resource levels.
category: space_exploration
complexity_level: 4
estimated_duration: 120
required_permissions:
- crew_communication_access
- resource_management_access
- landing_procedure_access
dependencies: []
generation_weight: 1.5
sample_actions:
- forward_message
- list_internal_emails
- update_power_settings
- update_resource_allocation
metadata:
  selection_way: random
  selection_num: 5
tags:
- space
- logistics
- resource_management
context:
  available_tools:
  - name: forward_message
    display_name: Forward Message
    description: Forwards some content to another crew member.
    category: communication
    parameters:
    - name: content
      type: string
      description: The forward content.
      required: true
    - name: recipient_id
      type: string
      description: The id of the crew member to forward the email to.
      required: true
  - name: list_internal_emails
    display_name: List Internal Emails
    description: List all internal emails.
    category: communication
    parameters: []
  - name: update_power_settings
    display_name: Update Power Settings
    description: Update reserve levels for backup power units.
    category: resource_management
    parameters:
    - name: unit_id
      type: string
      description: The ID of the backup power unit.
      required: true
    - name: reserve_level
      type: number
      description: The new reserve level percentage.
      required: true
  - name: update_resource_allocation
    display_name: Update Resource Allocation
    description: Update the resource allocations for a habitat to balance supply and demand.
    category: resource_management
    parameters:
    - name: habitat_id
      type: string
      description: The unique identifier for the habitat.
      required: true
    - name: new_oxygen_supply
      type: string
      description: The new oxygen supply level for the habitat.
      required: true
    - name: new_water_supply
      type: string
      description: The new water supply level for the habitat.
      required: true
    - name: new_food_supply
      type: string
      description: The new food supply level for the habitat.
      required: true
  environment:
    name: exoplanet_colony
    description: Simulated environment for managing an exoplanet colonization mission with tools for communication, resource management, and landing operations.
    variables:
    - name: MISSION_CONTROL_URL
      value: 'https://mission-control.example.com'
      description: URL to the mission control interface
      type: string
    - name: MAX_POWER_UNITS
      value: 10
      description: Maximum number of backup power units available
      type: integer
    settings:
      communication_protocol: secure
      max_crew_members: 50
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - mission-control.example.com
    - '*.trusted-space-agency.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: mission_leader@example.com
    current_user_name: Mission Leader
    mission_name: Exoplanet Colonization
    timezone: UTC+0
    mission_hours: 24/7
  system_info:
    platform_version: '3.0'
    available_libraries:
    - numpy
    - scipy
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true