name: exoskeleton_controller
display_name: Exoskeleton Controller
description: Manages and optimizes walking patterns for an exoskeleton to enhance mobility and energy efficiency. Provides functionalities to list available walking patterns and update them for improved performance.
category: robotics
complexity_level: 3
estimated_duration: 30
required_permissions:
- pattern_management_access
- energy_modulation_access
dependencies: []
generation_weight: 1.5
sample_actions:
- list_walking_patterns
- update_walking_pattern
metadata:
  selection_way: random
  selection_num: 2
tags:
- robotics
- mobility
- energy_efficiency
context:
  available_tools:
  - name: list_walking_patterns
    display_name: List Walking Patterns
    description: List all available walking patterns for the exoskeleton
    category: mobility
    parameters: []
    example_usage:
    - list_walking_patterns()
  - name: update_walking_pattern
    display_name: Update Walking Pattern
    description: Update the walking pattern for energy efficiency
    category: energy_management
    parameters:
    - name: pattern_id
      type: string
      description: The ID of the walking pattern to update
      required: true
    - name: energy_modulation
      type: string
      description: The modulation parameters to adjust energy consumption
      required: true
    example_usage:
    - update_walking_pattern(pattern_id='pattern123', energy_modulation='low_power')
  environment:
    name: exoskeleton_control_system
    description: Environment for managing and optimizing exoskeleton walking patterns
    variables:
    - name: MAX_ENERGY_CONSUMPTION
      value: 1000
      description: Maximum energy consumption allowed for walking patterns
      type: integer
    - name: PATTERN_UPDATE_URL
      value: 'https://api.exoskeleton.com/update-pattern'
      description: API endpoint for updating walking patterns
      type: string
    settings:
      pattern_update_format: JSON
      max_patterns_listed: 10
    max_memory_mb: 512
    max_execution_time: 120
    network_access: true
    allowed_domains:
    - exoskeleton.com
    - '*.trusted-partner.com'
    blocked_domains:
    - '*.unauthorized-site.com'
  predefined_variables:
    current_user_email: engineer@exoskeleton.com
    current_user_name: Exoskeleton Engineer
    company_name: ExoTech Inc.
    timezone: UTC+1
    business_hours: 9:00-17:00
  system_info:
    platform_version: '1.0'
    available_libraries:
    - numpy
    - scipy
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true