name: file_processor
display_name: File Processor
description: Processes files to extract content, specifically focusing on extracting text from PDF files. This scenario involves reading a PDF file and retrieving its textual content for further analysis or processing.
category: document_processing
complexity_level: 1
estimated_duration: 10
required_permissions:
- file_read_access
dependencies: []
generation_weight: 1.0
sample_actions:
- extract_pdf_content
metadata:
  selection_way: random
  selection_num: 1
tags:
- pdf
- content_extraction
- document_processing
context:
  available_tools:
  - name: extract_pdf_content
    display_name: Extract PDF Content
    description: Extract the content of a PDF file.
    category: document_processing
    parameters:
    - name: file_name_or_path
      type: string
      description: The name or path of the PDF file.
      required: true
    example_usage:
    - extract_pdf_content(file_name_or_path='document.pdf')
    common_errors:
    - File not found
    - Unsupported file format
  environment:
    name: document_processing_environment
    description: Environment configured for processing and extracting content from documents.
    variables:
    - name: SUPPORTED_FORMATS
      value: ['pdf']
      description: List of supported document formats for extraction.
      type: list
    settings:
      max_file_size_mb: 50
    max_memory_mb: 128
    max_execution_time: 60
    network_access: false
  predefined_variables:
    current_user_email: processor@example.com
    current_user_name: Document Processor
    company_name: DocuCorp Inc.
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '1.0'
    available_libraries:
    - PyPDF2
    - os
  security_policy:
    data_classification_required: false
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true