name: file_manager
display_name: File Manager
description: Manage files and folders within a file management system. This includes reading, writing, sharing, searching, creating, deleting, and appending to files, as well as listing files and folders. The scenario also covers logging into the system and managing access levels for shared files.
category: file_management
complexity_level: 3
estimated_duration: 30
required_permissions:
- file_access
- user_authentication
dependencies: []
generation_weight: 1.5
sample_actions:
- read_file
- write_file
- share_file
- search_files
- create_file
- delete_file
- append_to_file
- login
- list_files_and_folders
- list_files
metadata:
  selection_way: random
  selection_num: 5
tags:
- file_management
- cloud_storage
- access_control
context:
  available_tools:
  - name: read_file
    display_name: Read File
    description: Read the content from a file
    category: file_management
    parameters:
    - name: file_name_or_path
      type: string
      description: The name or path of the file
      required: true
  - name: write_file
    display_name: Write File
    description: Write content to a file
    category: file_management
    parameters:
    - name: file_name_or_path
      type: string
      description: The name or path of the file
      required: true
    - name: content
      type: string
      description: The content to write to the file
      required: true
  - name: share_file
    display_name: Share File
    description: Share a file or folder with someone
    category: file_management
    parameters:
    - name: to
      type: string
      description: The email of the person with whom the file or folder is shared
      required: false
    - name: owner
      type: string
      description: The owner of the file or folder
      required: false
    - name: file_name_or_path
      type: string
      description: The name or path of the file or folder
      required: true
    - name: access_level
      type: string
      description: The access level of the file or folder
      required: true
  - name: search_files
    display_name: Search Files
    description: Search files according to content relevance
    category: file_management
    parameters:
    - name: search_text
      type: string
      description: The text for searching relevant files
      required: true
  - name: create_file
    display_name: Create File
    description: Create a new file
    category: file_management
    parameters:
    - name: filename
      type: string
      description: The name of the file to create
      required: true
    - name: content
      type: string
      description: The content of the file to create
      required: true
  - name: delete_file
    display_name: Delete File
    description: Delete a file
    category: file_management
    parameters:
    - name: filename
      type: string
      description: The name of the file to delete
      required: true
  - name: append_to_file
    display_name: Append to File
    description: Append content to a given file
    category: file_management
    parameters:
    - name: filename
      type: string
      description: The name of the file to append to
      required: true
    - name: content
      type: string
      description: The content to append to the file
      required: true
  - name: login
    display_name: Login
    description: Login to the File Management System
    category: authentication
    parameters:
    - name: username
      type: string
      description: The username in the file management system
      required: true
  - name: list_files_and_folders
    display_name: List Files and Folders
    description: List files and folders in a given folder in the user's Filemanager account
    category: file_management
    parameters:
    - name: folder_path
      type: string
      description: The cloud folder path in the user's Filemanager account
      required: false
    - name: max_results
      type: integer
      description: The maximum number of files and folders to return
      required: false
  - name: list_files
    display_name: List Files
    description: List all files
    category: file_management
    parameters: []
  environment:
    name: cloud_file_management_system
    description: Cloud-based file management system environment with user authentication and file access control
    variables:
    - name: MAX_FILE_SIZE_MB
      value: 100
      description: Maximum file size allowed for uploads
      type: integer
    - name: DEFAULT_ACCESS_LEVEL
      value: read-only
      description: Default access level for shared files
      type: string
    settings:
      file_storage_format: 'cloud-native'
      max_concurrent_operations: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - filemanager.com
    - '*.trusted-storage.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: user@example.com
    current_user_name: File Manager User
    company_name: FileManager Inc.
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '1.0'
    available_libraries:
    - os
    - shutil
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true