name: financial_manager
display_name: Financial Manager
description: Manages financial operations including user identity verification, money transfers, and retrieval of financial data. Ensures secure and efficient handling of financial transactions and data access.
category: finance_management
complexity_level: 3
estimated_duration: 30
required_permissions:
- financial_data_access
- transaction_execution
dependencies: []
generation_weight: 1.5
sample_actions:
- verify_user_identity
- transfer_money
- retrieve_financial_data
metadata:
  selection_way: random
  selection_num: 3
tags:
- finance
- transactions
- data_management
context:
  available_tools:
  - name: verify_user_identity
    display_name: Verify User Identity
    description: Verify the user's identity with specific user id
    category: security
    parameters:
    - name: user_id
      type: string
      description: The ID of the user to authenticate
      required: true
    example_usage:
    - verify_user_identity(user_id='user123')
  - name: transfer_money
    display_name: Transfer Money
    description: Transfer a specific amount of money between two accounts
    category: transactions
    parameters:
    - name: src_account
      type: string
      description: The source account of the transfer
      required: true
    - name: dst_account
      type: string
      description: The destination account of the transfer
      required: true
    - name: amount
      type: string
      description: The amount of money to be transferred
      required: true
    example_usage:
    - transfer_money(src_account='accountA', dst_account='accountB', amount='100.00')
  - name: retrieve_financial_data
    display_name: Retrieve Financial Data
    description: Retrieve existing financial data
    category: data_management
    parameters: []
    example_usage:
    - retrieve_financial_data()
  environment:
    name: banking_system
    description: Secure banking system environment with financial transaction capabilities
    variables:
    - name: TRANSACTION_LIMIT
      value: 10000
      description: Maximum transaction limit per operation
      type: integer
    - name: DATA_RETENTION_POLICY
      value: 'https://www.examplebank.com/data-retention-policy'
      description: URL to the data retention policy page
      type: string
    settings:
      transaction_format: JSON
      max_concurrent_transactions: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - examplebank.com
    - '*.trusted-financial.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: finance_manager@examplebank.com
    current_user_name: Finance Manager
    company_name: Example Bank Inc.
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.0'
    available_libraries:
    - requests
    - json
    - cryptography
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true