name: food_safety_inspection
display_name: Food Safety Inspection
description: Facilitates the management of food safety inspections for restaurants, including listing recent reports, fetching detailed inspection data, and scheduling follow-up inspections. Ensures compliance with health regulations and promotes public health safety.
category: public_health
complexity_level: 3
estimated_duration: 30
required_permissions:
- inspection_data_access
- scheduling_access
dependencies: []
generation_weight: 1.5
sample_actions:
- list_reports
- fetch_inspection_data
- schedule_inspection
metadata:
  selection_way: random
  selection_num: 3
tags:
- food_safety
- inspections
- public_health
context:
  available_tools:
  - name: list_reports
    display_name: List Reports
    description: List recent inspection reports for different restaurants
    category: reporting
    parameters: []
    example_usage:
    - list_reports()
  - name: fetch_inspection_data
    display_name: Fetch Inspection Data
    description: Fetch detailed inspection data for the specified restaurant
    category: data_retrieval
    parameters: []
    example_usage:
    - fetch_inspection_data(restaurant_name='The Great Eatery')
  - name: schedule_inspection
    display_name: Schedule Inspection
    description: Schedule a follow-up inspection for a specified restaurant
    category: scheduling
    parameters:
    - name: restaurant_name
      type: string
      description: The name of the restaurant to schedule an inspection for
      required: true
    - name: date
      type: string
      description: The date to schedule the inspection on (YYYYMMDD)
      required: true
    example_usage:
    - schedule_inspection(restaurant_name='The Great Eatery', date='20231015')
  environment:
    name: health_inspection_system
    description: System for managing and scheduling restaurant health inspections
    variables:
    - name: INSPECTION_POLICY_URL
      value: 'https://www.example.com/inspection-policy'
      description: URL to the inspection policy page
      type: string
    - name: MAX_SCHEDULE_DAYS
      value: 60
      description: Maximum number of days in advance an inspection can be scheduled
      type: integer
    settings:
      report_format: PDF
      max_reports_per_request: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - example.com
    - '*.gov'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: inspector@example.com
    current_user_name: Health Inspector
    agency_name: Food Safety Agency
    timezone: UTC-6
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.0'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true