name: genetic_engineering
display_name: Genetic Engineering Inventory Management
description: This scenario involves managing the inventory of enzymes used in genetic engineering processes. It includes reviewing current stock levels, updating inventory with new stock information, reading data from files, and executing scripts within the genetic engineering environment. The goal is to ensure accurate tracking and management of enzyme resources to support ongoing research and development activities.
category: laboratory_management
complexity_level: 3
estimated_duration: 30
required_permissions:
- inventory_access
- file_system_access
dependencies: []
generation_weight: 1.5
sample_actions:
- review_inventory
- update_inventory
- read_file
- execute_script
metadata:
  selection_way: random
  selection_num: 4
tags:
- genetic_engineering
- inventory_management
- laboratory
context:
  available_tools:
  - name: review_inventory
    display_name: Review Inventory
    description: Review enzymes in the inventory.
    category: inventory_management
    parameters: []
    example_usage:
    - review_inventory()
  - name: update_inventory
    display_name: Update Inventory
    description: Update the stock level of an enzyme.
    category: inventory_management
    parameters:
    - name: enzyme_id
      type: string
      description: The ID of the enzyme.
      required: true
    - name: new_units
      type: number
      description: The new number of units for the enzyme.
      required: true
    example_usage:
    - update_inventory(enzyme_id='E123', new_units=50)
  - name: read_file
    display_name: Read File
    description: Read the content from a file.
    category: file_management
    parameters: []
    example_usage:
    - read_file()
  - name: execute_script
    display_name: Execute Script
    description: Execute a script file in the genetic engineering environment.
    category: script_execution
    parameters:
    - name: file_name_or_path
      type: string
      description: The path of the script file to execute.
      required: true
    example_usage:
    - execute_script(file_name_or_path='scripts/analyze_data.py')
  environment:
    name: genetic_lab_environment
    description: Laboratory environment equipped with tools for genetic engineering and inventory management.
    variables:
    - name: INVENTORY_DB_URL
      value: 'https://lab.example.com/inventory'
      description: URL to the inventory database
      type: string
    - name: SCRIPT_EXECUTION_TIMEOUT
      value: 120
      description: Maximum time allowed for script execution in seconds
      type: integer
    settings:
      script_execution_format: Python
      max_units_per_update: 100
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - lab.example.com
    - '*.trusted-lab-partner.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: researcher@lab.example.com
    current_user_name: Lab Researcher
    company_name: BioTech Labs Inc.
    timezone: UTC-6
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - numpy
    - pandas
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true