name: github
display_name: GitHub Repository Management
description: Provides a suite of tools for managing GitHub repositories, including adding/removing collaborators, searching issues, creating and deleting repositories, and retrieving user and repository details. Designed to assist users in efficiently managing their GitHub projects and collaborations.
category: developer_tools
complexity_level: 3
estimated_duration: 30
required_permissions:
- repository_access
- user_data_access
dependencies: []
generation_weight: 1.5
sample_actions:
- manage_collaborator
- search_issues
- create_repository
- delete_repository
metadata:
  selection_way: random
  selection_num: 3
tags:
- github
- repository_management
- collaboration
context:
  available_tools:
  - name: manage_collaborator
    display_name: Manage Collaborator
    description: Add or remove repository collaborators. Only valid if the user owns the repository.
    category: collaboration
    parameters:
    - name: repo_id
      type: string
      description: The unique identifier of the repository.
      required: true
    - name: action
      type: string
      description: The action to perform. Can be 'add' or 'remove'.
      required: true
    - name: collaborator_username
      type: string
      description: The username of the collaborator.
      required: true
    example_usage:
    - manage_collaborator(repo_id='repo123', action='add', collaborator_username='user456')
  - name: search_issues
    display_name: Search Issues
    description: Search relevant issues from a given repository.
    category: issue_tracking
    parameters:
    - name: repository_name
      type: string
      description: The name of the Github repository.
      required: true
    - name: search_text
      type: string
      description: The text for search.
      required: true
    example_usage:
    - search_issues(repository_name='my-repo', search_text='bug')
  environment:
    name: github_platform
    description: GitHub platform environment with repository management tools
    variables:
    - name: API_BASE_URL
      value: 'https://api.github.com'
      description: Base URL for GitHub API
      type: string
    - name: MAX_RESULTS
      value: 10
      description: Maximum number of results to return for searches
      type: integer
    settings:
      default_visibility: public
      max_collaborators: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - github.com
    - '*.githubusercontent.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: dev@example.com
    current_user_name: Developer
    organization_name: DevOrg Inc.
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '1.0'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true