name: hazardous_material_management
display_name: Hazardous Material Management
description: Manages the lifecycle of hazardous materials, including disposal, relocation, and transportation. Ensures compliance with safety regulations and guidelines for handling hazardous materials, while optimizing logistics and resource allocation.
category: logistics
complexity_level: 3
estimated_duration: 45
required_permissions:
- material_data_access
- logistics_management_access
dependencies: []
generation_weight: 1.5
sample_actions:
- throw_away
- list_materials
- relocate_material
- assign_transport_vehicle
metadata:
  selection_way: random
  selection_num: 4
tags:
- hazardous_materials
- logistics
- safety
- compliance
context:
  available_tools:
  - name: throw_away
    display_name: Throw Away Material
    description: Dispose of a specific hazardous material safely
    category: disposal
    parameters:
    - name: material_name
      type: string
      description: The name of the material
      required: true
    example_usage:
    - throw_away(material_name='Chemical X')
  - name: relocate_material
    display_name: Relocate Material
    description: Move materials to a different storage location
    category: logistics
    parameters:
    - name: material_id
      type: string
      description: The ID of the material to be relocated
      required: true
    - name: new_location
      type: string
      description: The new location for the material
      required: true
    example_usage:
    - relocate_material(material_id='123', new_location='Warehouse B')
  - name: assign_transport_vehicle
    display_name: Assign Transport Vehicle
    description: Assign a vehicle for transporting hazardous materials
    category: transportation
    parameters:
    - name: vehicle_id
      type: string
      description: The id of the vehicle
      required: true
    - name: material_id
      type: string
      description: The id of the material to be transported
      required: true
    example_usage:
    - assign_transport_vehicle(vehicle_id='V001', material_id='M001')
  environment:
    name: hazardous_material_management_system
    description: System for managing hazardous materials with tools for disposal, relocation, and transportation
    variables:
    - name: SAFETY_GUIDELINES_URL
      value: 'https://www.example.com/safety-guidelines'
      description: URL to the safety guidelines page
      type: string
    - name: MAX_STORAGE_CAPACITY
      value: 1000
      description: Maximum storage capacity for hazardous materials
      type: integer
    settings:
      disposal_method: incineration
      max_transport_distance_km: 500
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - example.com
    - '*.trusted-logistics.com'
    blocked_domains:
    - '*.unverified-source.com'
  predefined_variables:
    current_user_email: logistics_manager@example.com
    current_user_name: Logistics Manager
    company_name: SafeTransport Inc.
    timezone: UTC-6
    business_hours: 7:00-19:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - yaml
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true