name: hf
display_name: Host and File Interaction
description: This scenario involves interacting with various data sources, including reading files from disk, retrieving website data, querying databases, and generating random data. It is designed to test an AI agent's ability to handle diverse data retrieval and manipulation tasks, ensuring robust performance across different environments.
category: data_interaction
complexity_level: 3
estimated_duration: 30
required_permissions:
- file_system_access
- internet_access
- database_access
dependencies: []
generation_weight: 1.5
sample_actions:
- read_file
- retrieve_website
- select_database_data
- generate_string
metadata:
  selection_way: random
  selection_num: 5
tags:
- data_retrieval
- file_management
- database_query
- random_generation
context:
  available_tools:
  - name: read_file
    display_name: Read File
    description: Read file from a given path on disk
    category: file_management
    parameters:
    - name: file_path
      type: string
      description: The given path to read file
      required: true
    example_usage:
    - read_file(file_path='/path/to/file.txt')
    common_errors:
    - File not found
    - Permission denied
  - name: retrieve_website
    display_name: Retrieve Website
    description: Retrieve the results of an existing website
    category: web_interaction
    parameters:
    - name: website
      type: string
      description: The host name of the website you want to retrieve
      required: true
    example_usage:
    - retrieve_website(website='example.com')
  - name: select_database_data
    display_name: Select Database Data
    description: Read the data stored in a database based on the SQL query
    category: database_query
    parameters:
    - name: query
      type: string
      description: A string that represents the SQL query
      required: true
    example_usage:
    - select_database_data(query='SELECT * FROM users')
  - name: generate_string
    display_name: Generate String
    description: Return a random string
    category: data_generation
    parameters:
    - name: len
      type: string
      description: The length of the string
      required: false
    - name: cnt
      type: string
      description: The number of strings to return
      required: false
    example_usage:
    - generate_string(len='10', cnt='5')
  environment:
    name: data_interaction_environment
    description: Environment for testing data interaction capabilities
    variables:
    - name: DATABASE_URL
      value: 'postgres://user:password@localhost:5432/mydatabase'
      description: URL to connect to the database
      type: string
    - name: MAX_RETRIES
      value: 3
      description: Maximum number of retries for network requests
      type: integer
    settings:
      file_read_timeout: 60
      max_query_results: 100
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - example.com
    - '*.trusted-source.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: data.agent@example.com
    current_user_name: Data Interaction Agent
    company_name: DataCorp Inc.
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.0'
    available_libraries:
    - requests
    - psycopg2
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true