name: holographic_surgery_guide
display_name: Holographic Surgery Guide
description: Provides a comprehensive guide for managing surgical instruments and patient data in a holographic surgery environment. This includes listing and updating surgical instruments, managing patient records, and handling surgical firmware updates to ensure a seamless and efficient surgical process.
category: healthcare_management
complexity_level: 3
estimated_duration: 45
required_permissions:
- instrument_management_access
- patient_data_access
- firmware_update_access
dependencies: []
generation_weight: 1.5
sample_actions:
- list_instruments
- update_instrument_availability
- delete_patient_data
- list_patient_data
- list_firmwares
- update_firmware
metadata:
  selection_way: random
  selection_num: 4
tags:
- healthcare
- surgery
- data_management
context:
  available_tools:
  - name: list_instruments
    display_name: List Instruments
    description: List available surgical instruments.
    category: inventory_management
    parameters: []
    example_usage:
    - list_instruments()
  - name: update_instrument_availability
    display_name: Update Instrument Availability
    description: Update the number of available units of a specific instrument.
    category: inventory_management
    parameters:
    - name: instrument_id
      type: string
      description: The ID of the instrument.
      required: true
    - name: availability
      type: number
      description: The new availability of the instrument.
      required: true
    example_usage:
    - update_instrument_availability(instrument_id='instr123', availability=10)
  - name: delete_patient_data
    display_name: Delete Patient Data
    description: Remove any non-essential patient records from the system without compromising ongoing surgery information.
    category: data_management
    parameters:
    - name: record_id
      type: string
      description: The ID of the patient record to delete.
      required: true
    example_usage:
    - delete_patient_data(record_id='rec456')
  - name: list_patient_data
    display_name: List Patient Data
    description: List all patient records stored in the system.
    category: data_management
    parameters: []
    example_usage:
    - list_patient_data()
  - name: list_firmwares
    display_name: List Firmwares
    description: Retrieve a list of available surgical firmwares and their status.
    category: firmware_management
    parameters: []
    example_usage:
    - list_firmwares()
  - name: update_firmware
    display_name: Update Firmware
    description: Apply an update package to a given surgical firmware.
    category: firmware_management
    parameters:
    - name: firmware_name
      type: string
      description: Name of the firmware to update.
      required: true
    - name: update_package
      type: string
      description: The update package file for the firmware.
      required: true
    example_usage:
    - update_firmware(firmware_name='firmware_v1', update_package='update_pkg.zip')
  environment:
    name: surgical_holographic_environment
    description: A holographic environment for managing surgical operations, including instrument and patient data management.
    variables:
    - name: DATA_RETENTION_POLICY
      value: 'https://www.hospital.com/data-retention-policy'
      description: URL to the data retention policy page
      type: string
    - name: MAX_INSTRUMENTS
      value: 100
      description: Maximum number of instruments that can be managed
      type: integer
    settings:
      firmware_update_format: ZIP
      max_patient_records: 1000
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - hospital.com
    - '*.trusted-medical.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: surgeon@hospital.com
    current_user_name: Dr. Alex Smith
    hospital_name: City Hospital
    timezone: UTC-6
    business_hours: 7:00-19:00
  system_info:
    platform_version: '3.0'
    available_libraries:
    - numpy
    - pandas
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true