name: home_assistant
display_name: Home Assistant
description: A comprehensive home management system that allows users to control access, manage guests, monitor devices, and ensure security. It provides functionalities such as unlocking doors, adding or removing guests, checking lock status, viewing access history, and controlling devices. This system aims to enhance home security and convenience through automation and remote access capabilities.
category: home_automation
complexity_level: 3
estimated_duration: 30
required_permissions:
- device_control
- guest_management
- security_access
dependencies: []
generation_weight: 1.5
sample_actions:
- unlock_door
- add_guest
- delete_guest
- check_lock_status
- view_access_history
metadata:
  selection_way: random
  selection_num: 5
tags:
- home_security
- automation
- guest_management
- device_control
context:
  available_tools:
  - name: unlock_door
    display_name: Unlock Door
    description: Unlocks the door.
    category: security
    parameters: []
    example_usage:
    - unlock_door()
  - name: add_guest
    display_name: Add Guest
    description: Adds a guest to the system.
    category: guest_management
    parameters:
    - name: guest_name
      type: string
      description: Name of the guest to add.
      required: true
    - name: guest_email
      type: string
      description: Email address of the guest to add.
      required: true
    example_usage:
    - add_guest(guest_name='John Doe', guest_email='john.doe@example.com')
  - name: delete_guest
    display_name: Delete Guest
    description: Deletes a guest from the system.
    category: guest_management
    parameters:
    - name: guest_ids
      type: list
      description: An array of guest IDs to delete.
      required: true
    example_usage:
    - delete_guest(guest_ids=['guest1', 'guest2'])
  - name: check_lock_status
    display_name: Check Lock Status
    description: Retrieves the current lock status of the door.
    category: security
    parameters: []
    example_usage:
    - check_lock_status()
  - name: view_access_history
    display_name: View Access History
    description: Retrieves access history.
    category: security
    parameters:
    - name: start_time
      type: string
      description: Start time of the history period in YYYY-MM-DD HH:mm format.
      required: false
    - name: end_time
      type: string
      description: End time of the history period in YYYY-MM-DD HH:mm format.
      required: false
    example_usage:
    - view_access_history(start_time='2023-01-01 00:00', end_time='2023-01-31 23:59')
  environment:
    name: smart_home_environment
    description: A smart home environment equipped with IoT devices for security and automation.
    variables:
    - name: SECURITY_ALERT_EMAIL
      value: 'alerts@homeassistant.com'
      description: Email address for security alerts.
      type: string
    - name: MAX_GUESTS
      value: 50
      description: Maximum number of guests that can be managed.
      type: integer
    settings:
      lock_status_check_interval: 5
      max_device_control_attempts: 3
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - homeassistant.com
    - '*.trusted-device.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: admin@homeassistant.com
    current_user_name: Home Admin
    company_name: SmartHome Inc.
    timezone: UTC-5
    business_hours: 0:00-23:59
  system_info:
    platform_version: '3.0'
    available_libraries:
    - requests
    - json
    - datetime
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true