name: info_repository
display_name: Information Repository
description: This scenario involves accessing web-based sources to gather information on specified topics. It is designed to test the agent's ability to retrieve and process data from online resources efficiently and securely.
category: information_retrieval
complexity_level: 3
estimated_duration: 15
required_permissions:
- internet_access
dependencies: []
generation_weight: 1.0
sample_actions:
- access_web_sources
metadata:
  selection_way: random
  selection_num: 1
tags:
- web_access
- information_gathering
- data_processing
context:
  available_tools:
  - name: access_web_sources
    display_name: Access Web Sources
    description: Access web-based sources to gather information on specified topics
    category: information_retrieval
    parameters:
    - name: url
      type: string
      description: The URL of the web resource to access
      required: true
    example_usage:
    - access_web_sources(url='https://www.example.com')
    common_errors:
    - Invalid URL
    - Network timeout
  environment:
    name: web_access_environment
    description: Environment configured for accessing and retrieving data from web sources
    variables:
    - name: USER_AGENT
      value: 'Mozilla/5.0 (compatible; InfoBot/1.0)'
      description: User agent string for web requests
      type: string
    - name: MAX_RETRIES
      value: 3
      description: Maximum number of retries for web requests
      type: integer
    settings:
      request_timeout: 10
      max_concurrent_requests: 5
    max_memory_mb: 128
    max_execution_time: 120
    network_access: true
    allowed_domains:
    - '*.example.com'
    - '*.trusted-source.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: infoagent@example.com
    current_user_name: Information Agent
    company_name: DataCorp Inc.
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '1.0'
    available_libraries:
    - requests
    - beautifulsoup4
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true