name: internal_messaging
display_name: Internal Messaging
description: Facilitates communication within teams by allowing users to send messages with content and attachments to specified teams. Ensures efficient and organized internal communication.
category: communication
complexity_level: 1
estimated_duration: 10
required_permissions:
- messaging_access
- file_attachment_access
dependencies: []
generation_weight: 1.0
sample_actions:
- send_team_message
metadata:
  selection_way: random
  selection_num: 1
tags:
- messaging
- internal_communication
- team_collaboration
context:
  available_tools:
  - name: send_team_message
    display_name: Send Team Message
    description: Send a message to the specified team with the given content and optional file attachment.
    category: communication
    parameters:
    - name: team
      type: string
      description: The team to send the message to.
      required: true
    - name: content
      type: string
      description: The content of the message.
      required: true
    - name: file_name_or_path
      type: string
      description: The name or path of the file to be attached.
      required: true
    example_usage:
    - send_team_message(team='Marketing', content='Please review the attached document.', file_name_or_path='/docs/marketing_plan.pdf')
    common_errors:
    - Invalid team name
    - File not found
  environment:
    name: corporate_messaging_platform
    description: Internal messaging platform for team communication and collaboration.
    variables:
    - name: MAX_MESSAGE_LENGTH
      value: 1000
      description: Maximum number of characters allowed in a message.
      type: integer
    - name: ALLOWED_FILE_TYPES
      value: ['pdf', 'docx', 'xlsx']
      description: List of file types allowed for attachments.
      type: list
    settings:
      message_format: plain_text
      max_attachments_per_message: 3
    max_memory_mb: 128
    max_execution_time: 60
    network_access: true
    allowed_domains:
    - internal.company.com
    - '*.trusted-partner.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: user@company.com
    current_user_name: Team Member
    company_name: TechCorp Inc.
    timezone: UTC-4
    business_hours: 9:00-17:00
  system_info:
    platform_version: '1.0'
    available_libraries:
    - requests
    - os
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true