name: intelligent_agricultural_forecasting
display_name: Intelligent Agricultural Forecasting
description: This scenario involves utilizing AI tools to forecast agricultural yields based on crop data and regional parameters. The agent will generate forecasts, update yield parameters, adjust forecast settings, and manage datasets to optimize agricultural planning and decision-making.
category: agriculture
complexity_level: 3
estimated_duration: 30
required_permissions:
- data_management_access
- forecasting_tool_access
dependencies: []
generation_weight: 1.5
sample_actions:
- generate_forecast
- generate_yield_forecast
- update_yield_parameters
- adjust_forecast_settings
- list_datasets
- delete_data
metadata:
  selection_way: random
  selection_num: 5
tags:
- agriculture
- forecasting
- data_management
context:
  available_tools:
  - name: generate_forecast
    display_name: Generate Forecast
    description: Utilize the forecasting tool by entering crop data and region
    category: forecasting
    parameters:
    - name: crop_type
      type: string
      description: Type of crop for which forecast is needed
      required: true
    - name: region
      type: string
      description: Region for which yield forecast is required
      required: true
    example_usage:
    - generate_forecast(crop_type='wheat', region='Midwest')
  - name: update_yield_parameters
    display_name: Update Yield Parameters
    description: Update parameters affecting crop yield forecasts
    category: data_management
    parameters:
    - name: parameter_name
      type: string
      description: The name of the parameter to update, e.g., rainfall, soil_quality
      required: true
    - name: value
      type: number
      description: The new value of the parameter
      required: true
    example_usage:
    - update_yield_parameters(parameter_name='rainfall', value=120.5)
  - name: adjust_forecast_settings
    display_name: Adjust Forecast Settings
    description: Adjust the forecast settings for a crop
    category: forecasting
    parameters:
    - name: crop_id
      type: string
      description: The ID of the crop
      required: true
    - name: forecast_accuracy
      type: number
      description: The revised forecast accuracy percentage
      required: true
    example_usage:
    - adjust_forecast_settings(crop_id='crop123', forecast_accuracy=95.0)
  environment:
    name: agricultural_forecasting_platform
    description: Platform environment for managing agricultural data and forecasts
    variables:
    - name: FORECAST_API_URL
      value: 'https://api.agriculture-forecast.com'
      description: URL to the forecasting API
      type: string
    - name: MAX_DATASETS
      value: 100
      description: Maximum number of datasets allowed
      type: integer
    settings:
      forecast_output_format: JSON
      max_forecast_days: 365
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - agriculture-forecast.com
    - '*.trusted-agri-partner.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: analyst@agriculture.com
    current_user_name: Agricultural Data Analyst
    company_name: AgriTech Solutions Inc.
    timezone: UTC+2
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - numpy
    - pandas
    - requests
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true