name: loan_approval_system
display_name: Loan Approval System
description: This scenario involves announcing a reduction in interest rates for loans. The agent is responsible for declaring the new reduced interest rate percentage to customers, ensuring clear communication and understanding of the new terms.
category: financial_services
complexity_level: 1
estimated_duration: 10
required_permissions:
- financial_data_access
dependencies: []
generation_weight: 1.0
sample_actions:
- announce_rate_reduce
metadata:
  selection_way: random
  selection_num: 1
tags:
- finance
- loans
- interest_rates
context:
  available_tools:
  - name: announce_rate_reduce
    display_name: Announce Rate Reduction
    description: Declare the new reduced interest rate to customers
    category: communication
    parameters:
    - name: reduced_ratio
      type: number
      description: The reduced ratio (%) of the interest rate
      required: true
    example_usage:
    - announce_rate_reduce(reduced_ratio=2.5)
  environment:
    name: financial_platform
    description: Financial platform environment with tools for managing loan interest rates
    variables:
    - name: INTEREST_RATE_POLICY_URL
      value: 'https://www.examplebank.com/interest-rate-policy'
      description: URL to the interest rate policy page
      type: string
    settings:
      announcement_format: email
      max_announcements_per_day: 100
    max_memory_mb: 128
    max_execution_time: 60
    network_access: true
    allowed_domains:
    - examplebank.com
    - '*.trusted-financial-partner.com'
    blocked_domains:
    - '*.untrusted-site.com'
  predefined_variables:
    current_user_email: agent@examplebank.com
    current_user_name: Loan Officer
    company_name: Example Bank Inc.
    timezone: UTC-4
    business_hours: 9:00-17:00
  system_info:
    platform_version: '1.0'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true