name: medical_diagnosis
display_name: Medical Diagnosis Assistant
description: Assists healthcare professionals by analyzing test results, adjusting medications, retrieving patient information, and managing appointments. Aims to improve patient care through efficient data handling and decision support.
category: healthcare
complexity_level: 3
estimated_duration: 30
required_permissions:
- patient_data_access
- appointment_management_access
dependencies: []
generation_weight: 1.5
sample_actions:
- analyze_test_results
- adjust_medication
- suggest_medication
- reschedule_appointment
metadata:
  selection_way: random
  selection_num: 4
tags:
- healthcare
- patient_management
- diagnostics
context:
  available_tools:
  - name: analyze_test_results
    display_name: Analyze Test Results
    description: Analyze the provided test results to identify potential health issues
    category: diagnostics
    parameters:
    - name: cholesterol
      type: string
      description: The cholesterol value in test results to be analyzed
      required: true
    - name: blood_sugar
      type: string
      description: The blood sugar value in test results to be analyzed
      required: true
    - name: thyroid_level
      type: string
      description: The thyroid level value in test results to be analyzed
      required: true
    example_usage:
    - analyze_test_results(cholesterol='200', blood_sugar='90', thyroid_level='1.5')
    common_errors:
    - Missing required test result values
    - Data integrity issues due to outdated tool
  - name: adjust_medication
    display_name: Adjust Medication
    description: Adjust the medication based on new test results analysis
    category: treatment
    parameters:
    - name: medication_adjustments
      type: string
      description: The details of medication adjustments to be made
      required: false
    example_usage:
    - adjust_medication(medication_adjustments='Increase dosage of medication X by 10mg')
  - name: get_patient_info
    display_name: Get Patient Information
    description: Retrieve the patient's information
    category: patient_management
    parameters: []
    example_usage:
    - get_patient_info()
  - name: reschedule_appointment
    display_name: Reschedule Appointment
    description: Adjust the timing of a patient's appointment
    category: scheduling
    parameters:
    - name: patient_id
      type: string
      description: ID of the patient whose appointment needs to be rescheduled
      required: true
    - name: new_time
      type: string
      description: New time for the appointment (e.g., '11:30 AM')
      required: true
    - name: new_day
      type: string
      description: New day for the appointment (e.g., 'Thursday')
      required: true
    example_usage:
    - reschedule_appointment(patient_id='12345', new_time='11:30 AM', new_day='Thursday')
  environment:
    name: healthcare_system
    description: Healthcare system environment with patient management and diagnostic tools
    variables:
    - name: PATIENT_DATA_API
      value: 'https://api.healthcare-system.com/patient-data'
      description: API endpoint for accessing patient data
      type: string
    - name: MAX_APPOINTMENT_RESCHEDULES
      value: 3
      description: Maximum number of times an appointment can be rescheduled
      type: integer
    settings:
      data_analysis_tool_version: '1.0'
      max_concurrent_analyses: 5
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - healthcare-system.com
    - '*.trusted-medical-partner.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: doctor@example.com
    current_user_name: Dr. John Doe
    hospital_name: City Hospital
    timezone: UTC-6
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - numpy
    - pandas
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true