name: memory_metrics_analyzer
display_name: Memory Metrics Analyzer
description: Analyzes server memory metrics by listing current server configurations and updating memory allocations for specified servers. This ensures optimal memory usage and performance across the server infrastructure.
category: infrastructure_management
complexity_level: 3
estimated_duration: 30
required_permissions:
- server_management_access
- configuration_update_access
dependencies: []
generation_weight: 1.5
sample_actions:
- list_servers
- update_memory_allocation
metadata:
  selection_way: random
  selection_num: 2
tags:
- server_management
- memory_optimization
- infrastructure
context:
  available_tools:
  - name: list_servers
    display_name: List Servers
    description: List all servers with their current configurations.
    category: infrastructure_management
    parameters: []
    example_usage:
    - list_servers()
  - name: update_memory_allocation
    display_name: Update Memory Allocation
    description: Update the memory allocation for a specified server.
    category: infrastructure_management
    parameters:
    - name: server_id
      type: string
      description: The ID of the server.
      required: true
    - name: new_memory
      type: number
      description: The new memory allocation for the server.
      required: true
    example_usage:
    - update_memory_allocation(server_id='server123', new_memory=16)
  environment:
    name: server_management_platform
    description: Platform for managing server configurations and memory allocations
    variables:
    - name: MAX_MEMORY_ALLOCATION
      value: 64
      description: Maximum memory allocation per server in GB
      type: integer
    - name: DEFAULT_MEMORY_ALLOCATION
      value: 8
      description: Default memory allocation per server in GB
      type: integer
    settings:
      memory_allocation_unit: GB
      max_servers_per_operation: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - internal.company.com
    - '*.trusted-partner.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: admin@company.com
    current_user_name: System Administrator
    company_name: TechCorp Inc.
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true