name: metaverse_governance
display_name: Metaverse Governance
description: This scenario involves managing and overseeing various aspects of a virtual city's governance within the Metaverse. Tasks include reviewing facilities and events, accessing meeting notes, posting summaries to public forums, deactivating facilities to manage congestion, listing zone access policies, checking authority, and retrieving event details. The scenario aims to ensure smooth operation and governance of the virtual environment.
category: governance
complexity_level: 3
estimated_duration: 45
required_permissions:
- facility_management_access
- community_forum_access
- event_management_access
dependencies: []
generation_weight: 1.5
sample_actions:
- review_facilities_and_events
- access_meeting_notes
- post_summary
- deactivate_facilities
- list_zone_access_policies
- check_authority
- get_events
metadata:
  selection_way: random
  selection_num: 5
tags:
- governance
- virtual_city
- metaverse
- community_management
context:
  available_tools:
  - name: review_facilities_and_events
    display_name: Review Facilities and Events
    description: Review the existing active facilities and events.
    category: governance
    parameters: []
  - name: access_meeting_notes
    display_name: Access Meeting Notes
    description: Access and read notes from community meetings.
    category: governance
    parameters: []
  - name: post_summary
    display_name: Post Summary
    description: Post a summary of content to a public forum.
    category: communication
    parameters:
    - name: content
      type: string
      description: The text content to be posted publicly.
      required: true
  - name: deactivate_facilities
    display_name: Deactivate Facilities
    description: Deactivate specified public facilities in the virtual city to manage user flow and congestion.
    category: governance
    parameters:
    - name: facilities
      type: array
      description: The facilities to be deactivated.
      required: true
  - name: list_zone_access_policies
    display_name: List Zone Access Policies
    description: List the access policies for different zones in the Metaverse.
    category: governance
    parameters: []
  - name: check_authority
    display_name: Check Authority
    description: Check the authority of a person.
    category: governance
    parameters:
    - name: name
      type: string
      description: The input name to be checked
      required: true
  - name: get_events
    display_name: Get Events
    description: Get all available events with their details.
    category: event_management
    parameters: []
  environment:
    name: virtual_city_environment
    description: A simulated environment representing a virtual city within the Metaverse, equipped with governance and community management tools.
    variables:
    - name: COMMUNITY_FORUM_URL
      value: 'https://forum.metaverse-city.com'
      description: URL to the community forum
      type: string
    - name: MAX_CONCURRENT_EVENTS
      value: 10
      description: Maximum number of concurrent events allowed
      type: integer
    settings:
      event_notification_format: JSON
      max_facilities_per_deactivation: 3
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - metaverse-city.com
    - '*.trusted-partner.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: admin@metaverse-city.com
    current_user_name: City Administrator
    city_name: Metaverse City
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.0'
    available_libraries:
    - requests
    - json
    - yaml
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true