name: mind2web
display_name: Mind to Web Interaction
description: This scenario involves interacting with a web interface to log in, locate a search element, input search text, and execute a search. It tests the agent's ability to navigate web pages, handle user information, and perform search operations efficiently.
category: web_interaction
complexity_level: 3
estimated_duration: 15
required_permissions: []
dependencies: []
generation_weight: 1.0
sample_actions:
- login
- locate_the_search_element
- type_text_for_search
- click
metadata:
  selection_way: sequential
  selection_num: 4
tags:
- web
- search
- interaction
context:
  available_tools:
  - name: login
    display_name: Log In
    description: Log in to the website to access site rules and user information
    category: authentication
    parameters: []
    example_usage:
    - login()
  - name: locate_the_search_element
    display_name: Locate Search Element
    description: Locate the search box on the current page
    category: navigation
    parameters:
    - name: user_info
      type: string
      description: A detailed description of user information
      required: true
    example_usage:
    - locate_the_search_element(user_info='Detailed user info')
  - name: type_text_for_search
    display_name: Type Text for Search
    description: Type the search text into the search box
    category: input
    parameters:
    - name: search_text
      type: string
      description: The target to search
      required: true
    example_usage:
    - type_text_for_search(search_text='example search')
  - name: click
    display_name: Click Element
    description: Click the button corresponding to the located element
    category: interaction
    parameters: []
    example_usage:
    - click()
  environment:
    name: web_browser
    description: A standard web browser environment for testing web interactions
    variables: []
    settings:
      browser_type: Chrome
      headless_mode: true
    max_memory_mb: 512
    max_execution_time: 120
    network_access: true
    allowed_domains:
    - '*.example.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: user@example.com
    current_user_name: Test User
    company_name: WebTest Inc.
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '1.0'
    available_libraries:
    - selenium
    - beautifulsoup4
  security_policy:
    data_classification_required: false
    external_sharing_approval: false
    encryption_at_rest: false
    audit_logging: true