name: natural_disaster_response
display_name: Natural Disaster Response
description: Facilitates the coordination and management of resources and communications during natural disasters. This scenario includes obtaining necessary documents, broadcasting emergency messages, integrating plugins for enhanced functionality, and managing communication lines. It also involves querying for survival kits, checking area statuses, and allocating resources efficiently.
category: emergency_management
complexity_level: 3
estimated_duration: 45
required_permissions:
- communication_access
- resource_management_access
dependencies: []
generation_weight: 1.5
sample_actions:
- get_documents
- broadcast_message
- integrate_plugin
- list_communications
- disconnect_communication
- query_earthquake_kit
- check_area_status
- allocate_resources
metadata:
  selection_way: random
  selection_num: 5
tags:
- disaster_management
- emergency_response
- resource_allocation
context:
  available_tools:
  - name: get_documents
    display_name: Get Documents
    description: Retrieve all documents necessary for natural disaster response
    category: information_management
    parameters: []
    example_usage:
    - get_documents()
  - name: broadcast_message
    display_name: Broadcast Message
    description: Send an emergency message to all communication lines
    category: communication
    parameters:
    - name: content
      type: string
      description: The content of the message to be broadcasted
      required: true
    example_usage:
    - broadcast_message(content='Evacuate immediately due to incoming storm.')
  - name: integrate_plugin
    display_name: Integrate Plugin
    description: Add a new plugin to enhance system capabilities
    category: system_management
    parameters:
    - name: plugin_name
      type: string
      description: The name of the plugin to integrate
      required: true
    example_usage:
    - integrate_plugin(plugin_name='WeatherTracker')
  - name: list_communications
    display_name: List Communications
    description: Display all available communication lines
    category: communication
    parameters: []
    example_usage:
    - list_communications()
  - name: disconnect_communication
    display_name: Disconnect Communication
    description: Terminate a specified communication line
    category: communication
    parameters:
    - name: communication_name
      type: string
      description: The name of the communication line
      required: true
    example_usage:
    - disconnect_communication(communication_name='Line1')
  - name: query_earthquake_kit
    display_name: Query Earthquake Kit
    description: Provide a list of recommended items for an earthquake survival kit
    category: resource_management
    parameters:
    - name: disaster_name
      type: string
      description: The name of the disaster to search a survival kit for
      required: true
    example_usage:
    - query_earthquake_kit(disaster_name='earthquake')
  - name: check_area_status
    display_name: Check Area Status
    description: Obtain the current status of all areas affected by the disaster
    category: monitoring
    parameters: []
    example_usage:
    - check_area_status()
  - name: allocate_resources
    display_name: Allocate Resources
    description: Distribute resources to areas based on need and accessibility
    category: resource_management
    parameters:
    - name: area_name
      type: string
      description: Name of the area to allocate resources to
      required: true
    - name: resource_amount
      type: string
      description: Amount of resources to allocate
      required: true
    example_usage:
    - allocate_resources(area_name='Zone A', resource_amount='100 units')
  environment:
    name: disaster_response_system
    description: A system environment equipped with tools for managing natural disaster responses
    variables:
    - name: EMERGENCY_CONTACT_URL
      value: 'https://www.example.com/emergency-contact'
      description: URL to the emergency contact page
      type: string
    - name: MAX_BROADCAST_RANGE
      value: 100
      description: Maximum range for broadcasting messages in kilometers
      type: integer
    settings:
      message_format: SMS
      max_resources_per_allocation: 500
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - example.com
    - '*.emergency-services.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: responder@example.com
    current_user_name: Disaster Response Coordinator
    organization_name: Global Relief Agency
    timezone: UTC
    operation_hours: 24/7
  system_info:
    platform_version: '3.0'
    available_libraries:
    - requests
    - json
    - xml
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true