name: news_database
display_name: News Database
description: This scenario involves fetching and verifying news articles related to specific topics, particularly focusing on humanitarian aid in conflict zones. The agent is tasked with retrieving relevant articles, assessing their reliability, and ensuring the information is credible and useful for stakeholders.
category: information_retrieval
complexity_level: 3
estimated_duration: 30
required_permissions:
- internet_access
- data_analysis
dependencies: []
generation_weight: 1.5
sample_actions:
- retrieve_news
- fetch_news_articles
- check_reliability
metadata:
  selection_way: random
  selection_num: 5
tags:
- news
- information_retrieval
- reliability_check
context:
  available_tools:
  - name: retrieve_news
    display_name: Retrieve News
    description: Fetch articles related to humanitarian aid in conflict zones.
    category: information_retrieval
    parameters:
    - name: topic
      type: string
      description: The topic to query news articles for.
      required: true
    example_usage:
    - retrieve_news(topic='humanitarian aid')
  - name: fetch_news_articles
    display_name: Fetch News Articles
    description: Retrieve recent news articles related to a given topic or individual.
    category: information_retrieval
    parameters:
    - name: keyword
      type: string
      description: Keyword related to the news article to fetch.
      required: true
    example_usage:
    - fetch_news_articles(keyword='conflict zones')
  - name: check_reliability
    display_name: Check Reliability
    description: Check the reliability of the source of the fetched article.
    category: information_verification
    parameters:
    - name: source_name
      type: string
      description: Name of the source to check.
      required: true
    example_usage:
    - check_reliability(source_name='Trusted News Agency')
  environment:
    name: news_analysis_platform
    description: Platform for retrieving and analyzing news articles with tools for verification and reliability assessment.
    variables:
    - name: NEWS_API_KEY
      value: 'your_api_key_here'
      description: API key for accessing news services
      type: string
    - name: MAX_ARTICLES
      value: 50
      description: Maximum number of articles to fetch per query
      type: integer
    settings:
      article_format: JSON
      max_keywords: 5
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - newsapi.org
    - '*.reliable-news.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: analyst@example.com
    current_user_name: News Analyst
    organization_name: Global News Watch
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.0'
    available_libraries:
    - requests
    - json
    - pandas
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true