name: orbit_debris_shepherd
display_name: Orbit Debris Shepherd
description: This scenario involves managing satellite operations to prevent collisions with space debris. The agent will adjust monitoring priorities for satellites, list satellite information, and retrieve datasets for analysis. The goal is to ensure the safety and operational efficiency of satellites in orbit.
category: space_operations
complexity_level: 3
estimated_duration: 45
required_permissions:
- satellite_control_access
- data_retrieval_access
dependencies: []
generation_weight: 1.5
sample_actions:
- adjust_monitoring_priority
- list_satellites
- retrieve_dataset
metadata:
  selection_way: random
  selection_num: 3
tags:
- space
- satellite_management
- debris_avoidance
context:
  available_tools:
  - name: adjust_monitoring_priority
    display_name: Adjust Monitoring Priority
    description: Adjust the monitoring priority for a satellite.
    category: satellite_management
    parameters:
    - name: satellite_id
      type: string
      description: The ID of the satellite.
      required: true
    - name: monitoring_priority
      type: number
      description: The revised monitoring priority percentage.
      required: true
    example_usage:
    - adjust_monitoring_priority(satellite_id='SAT123', monitoring_priority=75)
  - name: list_satellites
    display_name: List Satellites
    description: List the information of all satellites.
    category: satellite_management
    parameters: []
    example_usage:
    - list_satellites()
  - name: retrieve_dataset
    display_name: Retrieve Dataset
    description: Retrieve a dataset for analysis. Requires the dataset name.
    category: data_analysis
    parameters:
    - name: dataset_name
      type: string
      description: The name of the dataset to retrieve.
      required: true
    example_usage:
    - retrieve_dataset(dataset_name='collision_risk_data')
  environment:
    name: satellite_control_center
    description: A control center environment for managing satellite operations and data analysis.
    variables:
    - name: SATELLITE_API_URL
      value: 'https://api.satellitecontrol.com'
      description: API endpoint for satellite control operations
      type: string
    - name: MAX_PRIORITY_LEVEL
      value: 100
      description: Maximum priority level for satellite monitoring
      type: integer
    settings:
      data_format: JSON
      max_satellites: 50
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - satellitecontrol.com
    - '*.trusted-space-agency.org'
    blocked_domains:
    - '*.unauthorized-access.com'
  predefined_variables:
    current_user_email: operator@satellitecontrol.com
    current_user_name: Satellite Operations Manager
    company_name: SpaceTech Inc.
    timezone: UTC
    business_hours: 24/7
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - numpy
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true