name: os
display_name: Operating System Interaction
description: This scenario involves interacting with the operating system through various file and command operations. It includes reading, writing, deleting, and listing files, executing terminal commands, and managing system shutdowns. The scenario tests the agent's ability to handle file system operations and execute scripts securely and efficiently.
category: system_operations
complexity_level: 3
estimated_duration: 30
required_permissions:
- file_system_access
- terminal_access
dependencies: []
generation_weight: 1.5
sample_actions:
- read_file
- write_file
- delete_file
- list_files
- terminal_execute
- shutdown
- click_link
- archive_file
- execute_script
- list_directories
- move_file
metadata:
  selection_way: random
  selection_num: 5
tags:
- file_management
- system_commands
- security
context:
  available_tools:
  - name: read_file
    display_name: Read File
    description: Read the content from a file.
    category: file_management
    parameters:
    - name: file_name_or_path
      type: string
      description: The name or path of the file.
      required: true
    example_usage:
    - read_file(file_name_or_path='/path/to/file.txt')
  - name: write_file
    display_name: Write File
    description: Write the content to a file.
    category: file_management
    parameters:
    - name: file_name_or_path
      type: string
      description: The name or path of the file.
      required: true
    - name: content
      type: string
      description: The content needed to be written to the file.
      required: true
    example_usage:
    - write_file(file_name_or_path='/path/to/file.txt', content='Hello, World!')
  - name: delete_file
    display_name: Delete File
    description: Delete the specified file (or folder).
    category: file_management
    parameters:
    - name: file_name_or_path
      type: string
      description: The name or path of the file (or folder).
      required: true
    example_usage:
    - delete_file(file_name_or_path='/path/to/file.txt')
  - name: terminal_execute
    display_name: Terminal Execute
    description: Execute a command in the terminal.
    category: system_commands
    parameters:
    - name: command
      type: string
      description: The command to be executed in the terminal.
      required: true
    example_usage:
    - terminal_execute(command='ls -la')
  environment:
    name: local_system
    description: Local system environment with file and terminal access
    variables:
    - name: HOME_DIRECTORY
      value: '/home/user'
      description: Path to the user's home directory
      type: string
    - name: TEMP_DIRECTORY
      value: '/tmp'
      description: Path to the temporary directory
      type: string
    settings:
      max_file_size_mb: 100
      max_execution_time: 120
    max_memory_mb: 512
    network_access: false
    allowed_domains: []
    blocked_domains: []
  predefined_variables:
    current_user: user
    current_directory: /home/user
    os_version: Ubuntu 20.04
    timezone: UTC
  system_info:
    platform_version: '1.0'
    available_libraries:
    - os
    - subprocess
    - shutil
  security_policy:
    data_classification_required: false
    external_sharing_approval: false
    encryption_at_rest: false
    audit_logging: true