name: pandemic_spread_simulator
display_name: Pandemic Spread Simulator
description: This scenario involves simulating the spread of infectious diseases and evaluating the impact of various health policies. It includes tools for reviewing current simulation parameters, predicting outcomes, and broadcasting public health messages. The scenario is designed to help understand the dynamics of pandemics and the effectiveness of interventions, but caution is advised as incorrect use may lead to misinformation.
category: public_health
complexity_level: 4
estimated_duration: 60
required_permissions:
- simulation_data_access
- public_communication_access
dependencies: []
generation_weight: 1.5
sample_actions:
- review_current_status
- simulate_policy_impact
- update_simulation_parameters
- predict_outcome
- get_measures
- broadcast_message
metadata:
  selection_way: random
  selection_num: 4
tags:
- pandemic
- simulation
- public_health
- policy_analysis
context:
  available_tools:
  - name: review_current_status
    display_name: Review Current Status
    description: Review the current simulations parameters in various regions.
    category: simulation_analysis
    parameters: []
  - name: simulate_policy_impact
    display_name: Simulate Policy Impact
    description: Simulate the impact of different health policies on disease spread.
    category: policy_simulation
    parameters:
    - name: policy
      type: string
      description: The health policy to simulate, such as vaccination, social distancing, or mask mandate.
      required: true
    - name: duration_days
      type: integer
      description: The duration in days for which the policy is to be applied in the simulation.
      required: true
  - name: update_simulation_parameters
    display_name: Update Simulation Parameters
    description: Adjust simulation parameters such as transmission rate for a specified region.
    category: simulation_adjustment
    parameters:
    - name: region_id
      type: string
      description: The identifier of the region to update.
      required: true
    - name: transmission_rate
      type: number
      description: The new transmission rate to apply to the region.
      required: true
  - name: predict_outcome
    display_name: Predict Outcome
    description: Simulate the spread of pandemics based on real-time data inputs.
    category: predictive_modeling
    parameters:
    - name: disease_name
      type: string
      description: The name of the disease, such as 'flu', 'covid-19', 'ebola'.
      required: true
    - name: region
      type: string
      description: The region for which the pandemic prediction is to be simulated.
      required: true
  - name: get_measures
    display_name: Get Measures
    description: Get measures to deal with the pandemic.
    category: public_health_guidance
    parameters: []
  - name: broadcast_message
    display_name: Broadcast Message
    description: Broadcasts a message to the public channel.
    category: communication
    parameters:
    - name: content
      type: string
      description: The content to be broadcasted.
      required: true
  environment:
    name: pandemic_simulation_environment
    description: An environment for simulating pandemic scenarios and evaluating health policies.
    variables:
    - name: SIMULATION_DATA_URL
      value: 'https://www.example.com/simulation-data'
      description: URL to access simulation data
      type: string
    - name: MAX_SIMULATION_DAYS
      value: 365
      description: Maximum number of days for simulation
      type: integer
    settings:
      simulation_accuracy_threshold: 0.95
      max_regions_per_simulation: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - example.com
    - '*.health-organization.org'
    blocked_domains:
    - '*.misinformation-site.com'
  predefined_variables:
    current_user_email: analyst@example.com
    current_user_name: Health Data Analyst
    organization_name: Global Health Institute
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - numpy
    - pandas
    - scipy
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true