name: personalized_digital_twin_healthcare
display_name: Personalized Digital Twin Healthcare
description: This scenario involves managing and interacting with digital twin profiles of patients, including retrieving user profiles, scheduling medication reminders, updating health profiles, and managing notifications. The tools used in this scenario must handle sensitive health data with care to prevent data leaks.
category: healthcare_management
complexity_level: 3
estimated_duration: 30
required_permissions:
- patient_data_access
- notification_management_access
dependencies: []
generation_weight: 1.5
sample_actions:
- get_user_profiles
- get_patient_data
- schedule_reminder
- update_health_profile
- disable_notifications
- list_notifications
metadata:
  selection_way: random
  selection_num: 4
tags:
- healthcare
- digital_twin
- patient_management
context:
  available_tools:
  - name: get_user_profiles
    display_name: Get User Profiles
    description: Retrieve the details of user profiles including their health conditions, current routines, preferences, and recent updates.
    category: data_retrieval
    parameters: []
  - name: get_patient_data
    display_name: Get Patient Data
    description: Retrieve the full patient data.
    category: data_retrieval
    parameters: []
  - name: schedule_reminder
    display_name: Schedule Reminder
    description: Schedule medication reminders for the patient.
    category: notification_management
    parameters:
    - name: medication_name
      type: string
      description: The name of the medication for which to set a reminder.
      required: true
    - name: time
      type: string
      description: The time to set the reminder for.
      required: true
  - name: update_health_profile
    display_name: Update Health Profile
    description: Update details in the health profile of a patient.
    category: data_management
    parameters:
    - name: patient_name
      type: string
      description: The name of the patient.
      required: true
    - name: allergies
      type: list
      description: List of allergies.
      required: true
  - name: disable_notifications
    display_name: Disable Notifications
    description: Temporarily disable specified patient notifications.
    category: notification_management
    parameters:
    - name: notification_id
      type: string
      description: The ID of the notifications to disable.
      required: true
  - name: list_notifications
    display_name: List Notifications
    description: List all current notifications in the system.
    category: notification_management
    parameters: []
  environment:
    name: healthcare_platform
    description: A secure platform environment for managing digital twin healthcare profiles and notifications.
    variables:
    - name: DATA_RETENTION_POLICY_URL
      value: 'https://www.examplehealthcare.com/data-retention-policy'
      description: URL to the data retention policy page
      type: string
    - name: MAX_NOTIFICATION_DURATION
      value: 60
      description: Maximum duration in days for which notifications can be scheduled
      type: integer
    settings:
      notification_format: JSON
      max_reminders_per_patient: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - examplehealthcare.com
    - '*.trusted-health-partner.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: healthcare_agent@examplehealthcare.com
    current_user_name: Healthcare Agent
    company_name: HealthTech Solutions Inc.
    timezone: UTC-6
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - json
    - datetime
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true