name: personalized_virtual_assistant_training
display_name: Personalized Virtual Assistant Training
description: This scenario involves training a personalized virtual assistant to manage various tasks such as listing events, publishing summaries, subscribing to services, and scheduling appointments. The assistant is designed to enhance productivity by automating routine tasks and providing quick access to information.
category: productivity
complexity_level: 3
estimated_duration: 30
required_permissions:
- user_data_access
- event_management_access
- service_subscription_access
dependencies: []
generation_weight: 1.5
sample_actions:
- list_events
- publish_summary
- subscribe
- schedule_appointment
metadata:
  selection_way: random
  selection_num: 5
tags:
- virtual_assistant
- automation
- productivity
context:
  available_tools:
  - name: list_events
    display_name: List Events
    description: Lists upcoming and past events attended or organized by the user
    category: event_management
    parameters: []
    example_usage:
    - list_events()
  - name: publish_summary
    display_name: Publish Summary
    description: Generate and publish a summary report from provided meeting notes
    category: documentation
    parameters:
    - name: event_id
      type: string
      description: The ID of the event for which to generate a summary
      required: true
    example_usage:
    - publish_summary(event_id='event123')
  - name: subscribe
    display_name: Subscribe to Service
    description: Subscribe to an educational service
    category: service_management
    parameters:
    - name: service_id
      type: string
      description: The unique identifier of the service
      required: true
    example_usage:
    - subscribe(service_id='service456')
  - name: schedule_appointment
    display_name: Schedule Appointment
    description: Schedule a new appointment for a family member
    category: scheduling
    parameters:
    - name: user_name
      type: string
      description: The name of the family member to schedule the appointment for
      required: true
    - name: day
      type: string
      description: The day for the appointment
      required: true
    - name: time
      type: string
      description: The time for the appointment
      required: true
    example_usage:
    - schedule_appointment(user_name='John Doe', day='Monday', time='10:00 AM')
  environment:
    name: virtual_assistant_platform
    description: A platform environment for managing personal and professional tasks using a virtual assistant
    variables:
    - name: TIMEZONE
      value: 'UTC'
      description: Default timezone for scheduling
      type: string
    - name: MAX_APPOINTMENTS_PER_DAY
      value: 10
      description: Maximum number of appointments that can be scheduled per day
      type: integer
    settings:
      report_format: PDF
      max_event_summaries: 5
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - example.com
    - '*.trusted-education.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: user@example.com
    current_user_name: Virtual Assistant User
    company_name: TechSolutions Inc.
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '1.0'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true