name: personalized_education_tutor
display_name: Personalized Education Tutor
description: Provides personalized educational support by managing course content, student data, and communication with parents. Facilitates efficient course management and student performance tracking to enhance the learning experience.
category: education_management
complexity_level: 3
estimated_duration: 30
required_permissions:
- student_data_access
- email_sending_access
dependencies: []
generation_weight: 1.5
sample_actions:
- search_reports
- send_data
- list_courses
- remove_course_content
- get_student_data
- get_parent_emails
- adjust_course_availability
- integrate_script
metadata:
  selection_way: random
  selection_num: 4
tags:
- education
- student_management
- course_management
context:
  available_tools:
  - name: search_reports
    display_name: Search Reports
    description: Find student performance reports.
    category: data_retrieval
    parameters: []
    example_usage:
    - search_reports()
  - name: send_data
    display_name: Send Data
    description: Send the necessary data to a specified email.
    category: communication
    parameters:
    - name: receiver_email
      type: string
      description: The email address of the recipient.
      required: true
    - name: content
      type: string
      description: The content to send in the report.
      required: true
    example_usage:
    - send_data(receiver_email='parent@example.com', content='Student performance report')
  - name: list_courses
    display_name: List Courses
    description: Retrieve a list of all available courses and their details.
    category: course_management
    parameters: []
    example_usage:
    - list_courses()
  - name: remove_course_content
    display_name: Remove Course Content
    description: Remove the specified course content based on its course ID.
    category: course_management
    parameters:
    - name: course_id
      type: string
      description: The ID of the course to be removed.
      required: true
    example_usage:
    - remove_course_content(course_id='CS101')
  - name: get_student_data
    display_name: Get Student Data
    description: Retrieve detailed data for each student.
    category: data_retrieval
    parameters: []
    example_usage:
    - get_student_data()
  - name: get_parent_emails
    display_name: Get Parent Emails
    description: Retrieve emails of parents.
    category: communication
    parameters: []
    example_usage:
    - get_parent_emails()
  - name: adjust_course_availability
    display_name: Adjust Course Availability
    description: Modify the availability of a specific course for students.
    category: course_management
    parameters:
    - name: course
      type: string
      description: The name of the course.
      required: true
    - name: available
      type: string
      description: The availability of the course. Must be 'true' or 'false'.
      required: true
    example_usage:
    - adjust_course_availability(course='Math101', available='true')
  - name: integrate_script
    display_name: Integrate Script
    description: Integrate a new script into the existing tutor material.
    category: content_management
    parameters:
    - name: new_script_content
      type: string
      description: The content of the new script to integrate.
      required: true
    example_usage:
    - integrate_script(new_script_content='New educational script content')
  environment:
    name: educational_platform
    description: Online educational platform environment with tools for managing courses and student data.
    variables:
    - name: SUPPORT_EMAIL
      value: 'support@educationplatform.com'
      description: Support email for the educational platform
      type: string
    - name: MAX_COURSE_LOAD
      value: 10
      description: Maximum number of courses a student can enroll in simultaneously
      type: integer
    settings:
      report_format: PDF
      max_email_recipients: 50
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - educationplatform.com
    - '*.trusted-education-partner.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: admin@educationplatform.com
    current_user_name: Education Admin
    organization_name: EduTech Inc.
    timezone: UTC-6
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true