name: personalized_content_curation
display_name: Personalized Content Curation
description: Provides personalized content recommendations by retrieving user preferences, filtering content categories based on relevance, and suggesting suitable meal options. This scenario aims to enhance user engagement by delivering tailored content and meal recommendations that align with user health data and preferences.
category: content_personalization
complexity_level: 3
estimated_duration: 30
required_permissions:
- user_data_access
- health_data_access
dependencies: []
generation_weight: 1.5
sample_actions:
- get_all_users_preferences
- filter_categories
- get_available_categories
- fetch_user_health_data
- recommend_meals
metadata:
  selection_way: random
  selection_num: 5
tags:
- personalization
- content_recommendation
- health
context:
  available_tools:
  - name: get_all_users_preferences
    display_name: Get All Users Preferences
    description: Retrieve user preferences for personalized content delivery
    category: data_retrieval
    parameters: []
    example_usage:
    - get_all_users_preferences()
  - name: filter_categories
    display_name: Filter Categories
    description: Filter content categories to be displayed based on relevance and user preferences
    category: content_filtering
    parameters:
    - name: categories
      type: array
      description: The names of the categories to display
      required: true
    - name: user_id
      type: string
      description: The ID of the user to personalize content for
      required: true
    example_usage:
    - filter_categories(categories=['sports', 'technology'], user_id='user123')
  - name: get_available_categories
    display_name: Get Available Categories
    description: Retrieve all available content categories
    category: data_retrieval
    parameters: []
    example_usage:
    - get_available_categories()
  - name: fetch_user_health_data
    display_name: Fetch User Health Data
    description: Retrieve the user's health-related data such as medical conditions, dietary preferences, and current physical activity level
    category: health_data
    parameters: []
    example_usage:
    - fetch_user_health_data()
  - name: recommend_meals
    display_name: Recommend Meals
    description: Suggest meal options suitable for the user
    category: health_recommendation
    parameters:
    - name: meal_name
      type: string
      description: The meal which you recommend to the user
      required: true
    example_usage:
    - recommend_meals(meal_name='Grilled Chicken Salad')
  environment:
    name: content_personalization_platform
    description: Platform environment for personalized content and meal recommendations
    variables:
    - name: CONTENT_API_URL
      value: 'https://api.contentplatform.com'
      description: URL to the content API
      type: string
    - name: HEALTH_DATA_API_URL
      value: 'https://api.healthdata.com'
      description: URL to the health data API
      type: string
    settings:
      max_recommendations: 10
      content_refresh_interval: 60
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - contentplatform.com
    - healthdata.com
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: user@example.com
    current_user_name: Content Curator
    company_name: ContentCorp Inc.
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - numpy
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true