name: personalized_fitness_trainer
display_name: Personalized Fitness Trainer
description: Provides personalized fitness training advice, assesses user fitness levels, retrieves current workout routines, and modifies workout plans based on user preferences and constraints. Aims to enhance user fitness experience by tailoring workouts to individual needs.
category: health_and_fitness
complexity_level: 3
estimated_duration: 30
required_permissions:
- user_data_access
dependencies: []
generation_weight: 1.5
sample_actions:
- get_training_advice
- assess_user_fitness
- retrieve_current_routine
- modify_workout_routine
metadata:
  selection_way: random
  selection_num: 4
tags:
- fitness
- health
- personalized_training
context:
  available_tools:
  - name: get_training_advice
    display_name: Get Training Advice
    description: Provides personalized training advice for the user based on their fitness goals and constraints.
    category: health_and_fitness
    parameters: []
    example_usage:
    - get_training_advice()
  - name: assess_user_fitness
    display_name: Assess User Fitness
    description: Evaluates the user's current fitness level and identifies any constraints.
    category: health_and_fitness
    parameters: []
    example_usage:
    - assess_user_fitness()
  - name: retrieve_current_routine
    display_name: Retrieve Current Routine
    description: Fetches the user's current workout routine for review or modification.
    category: health_and_fitness
    parameters: []
    example_usage:
    - retrieve_current_routine()
  - name: modify_workout_routine
    display_name: Modify Workout Routine
    description: Adjusts the user's workout routine for a specific day to better fit their needs.
    category: health_and_fitness
    parameters:
    - name: day
      type: string
      description: The day to modify the workout routine.
      required: true
    - name: new_routine
      type: list
      description: The new routine for the day.
      required: true
    example_usage:
    - modify_workout_routine(day='Monday', new_routine=['Yoga', 'Running'])
  environment:
    name: fitness_app_environment
    description: A virtual environment simulating a fitness application with user data access.
    variables:
    - name: MAX_WORKOUT_DURATION
      value: 120
      description: Maximum duration for a single workout session in minutes.
      type: integer
    - name: DEFAULT_TIMEZONE
      value: 'UTC'
      description: Default timezone for scheduling workouts.
      type: string
    settings:
      workout_plan_format: JSON
      max_routines_per_day: 5
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - fitnessapi.com
    - '*.trusted-fitness-partner.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: user@example.com
    current_user_name: Fitness Enthusiast
    company_name: FitLife Inc.
    timezone: UTC
    business_hours: 6:00-22:00
  system_info:
    platform_version: '3.0'
    available_libraries:
    - numpy
    - pandas
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true