name: personalized_nanobot_drug_delivery
display_name: Personalized Nanobot Drug Delivery
description: This scenario involves the use of nanobots for personalized drug delivery to patients. The agent is tasked with managing patient data, adding medications to specific patients or groups, and executing scripts for nanobot operations. The goal is to ensure precise and safe delivery of medications using advanced nanotechnology.
category: healthcare
complexity_level: 4
estimated_duration: 45
required_permissions:
- patient_data_access
- medication_management
- script_execution
dependencies: []
generation_weight: 1.5
sample_actions:
- get_patient_data
- add_medication
- execute_code
metadata:
  selection_way: random
  selection_num: 3
tags:
- healthcare
- nanotechnology
- personalized_medicine
context:
  available_tools:
  - name: get_patient_data
    display_name: Get Patient Data
    description: Retrieve all relevant data for a patient to assist in personalized treatment planning.
    category: data_management
    parameters: []
    example_usage:
    - get_patient_data()
  - name: add_medication
    display_name: Add Medication
    description: Add medication for a specific patient or group to the treatment plan.
    category: medication_management
    parameters:
    - name: medication_name
      type: string
      description: The name of the medication to be added.
      required: true
    - name: patient_or_group_name
      type: string
      description: The name of the target patient or the group.
      required: true
    example_usage:
    - add_medication(medication_name='Aspirin', patient_or_group_name='John Doe')
  - name: execute_code
    display_name: Execute Code
    description: Execute a provided code script for controlling nanobot operations.
    category: script_execution
    parameters:
    - name: script
      type: string
      description: The content of code script to be executed.
      required: true
    example_usage:
    - execute_code(script='print("Executing nanobot operation")')
  environment:
    name: healthcare_platform
    description: A secure healthcare platform environment with tools for managing patient data and executing nanobot operations.
    variables:
    - name: DATA_RETENTION_POLICY
      value: 'https://www.healthcareexample.com/data-policy'
      description: URL to the data retention policy page
      type: string
    - name: MAX_MEDICATION_ENTRIES
      value: 100
      description: Maximum number of medication entries allowed per patient
      type: integer
    settings:
      script_execution_timeout: 120
      max_patient_data_size_mb: 50
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - healthcareexample.com
    - '*.trusted-health-partner.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: doctor@example.com
    current_user_name: Dr. John Smith
    hospital_name: City Health Center
    timezone: UTC-6
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - numpy
    - pandas
    - scipy
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true