name: personalized_drug_discovery
display_name: Personalized Drug Discovery
description: This scenario involves checking the inventory of available medicines and sending specific medicines to patients based on their personalized needs. It ensures that patients receive the correct medication in the right amount, enhancing personalized healthcare delivery.
category: healthcare
complexity_level: 3
estimated_duration: 30
required_permissions:
- inventory_access
- patient_data_access
dependencies: []
generation_weight: 1.5
sample_actions:
- check_inventory
- send_medicine
metadata:
  selection_way: random
  selection_num: 2
tags:
- healthcare
- personalized_medicine
- inventory_management
context:
  available_tools:
  - name: check_inventory
    display_name: Check Inventory
    description: Verify the current stock of medicines available in the inventory.
    category: inventory_management
    parameters: []
    example_usage:
    - check_inventory()
  - name: send_medicine
    display_name: Send Medicine
    description: Dispatch specified medicine to a patient.
    category: healthcare_delivery
    parameters:
    - name: medicine_name
      type: string
      description: The name of the medicine
      required: true
    - name: amount
      type: integer
      description: The amount of the medicine
      required: true
    - name: patient_name
      type: string
      description: The name of the patient
      required: true
    example_usage:
    - send_medicine(medicine_name='Aspirin', amount=30, patient_name='John Doe')
  environment:
    name: healthcare_system
    description: A healthcare management system environment with tools for inventory and patient management.
    variables:
    - name: INVENTORY_API_URL
      value: 'https://api.healthcare-system.com/inventory'
      description: API endpoint for accessing inventory data
      type: string
    - name: PATIENT_DATA_API_URL
      value: 'https://api.healthcare-system.com/patient-data'
      description: API endpoint for accessing patient data
      type: string
    settings:
      max_medicine_dispatch: 100
      inventory_check_interval: 60
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - healthcare-system.com
    - '*.trusted-health-partner.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: pharmacist@healthcare-system.com
    current_user_name: Pharmacist
    company_name: HealthCare System Inc.
    timezone: UTC-6
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true