name: personalized_medicine
display_name: Personalized Medicine Assistant
description: Assists healthcare providers by querying research databases, retrieving patient profiles, and managing medication plans. Facilitates personalized treatment plans by integrating research data with patient-specific information.
category: healthcare
complexity_level: 3
estimated_duration: 30
required_permissions:
- patient_data_access
- research_db_access
dependencies: []
generation_weight: 1.5
sample_actions:
- query_research_db
- get_user_profile
- add_medication
- get_patient_medical_record
metadata:
  selection_way: random
  selection_num: 3
tags:
- healthcare
- personalized_medicine
- research
context:
  available_tools:
  - name: query_research_db
    display_name: Query Research Database
    description: Retrieve details from a database of research studies
    category: research
    parameters:
    - name: content
      type: string
      description: The query content
      required: true
    example_usage:
    - query_research_db(content='cancer treatment studies')
  - name: get_user_profile
    display_name: Get User Profile
    description: Retrieve the user's profile information including medical conditions, dietary preferences, and current medications
    category: user_management
    parameters: []
    example_usage:
    - get_user_profile()
  - name: add_medication
    display_name: Add Medication
    description: Add medication to the user's profile
    category: user_management
    parameters:
    - name: medication_name
      type: string
      description: The name of the medication
      required: true
    example_usage:
    - add_medication(medication_name='Aspirin')
  environment:
    name: healthcare_platform
    description: A secure platform for managing patient data and research information
    variables:
    - name: RESEARCH_DB_URL
      value: 'https://researchdb.example.com'
      description: URL to the research database
      type: string
    - name: MAX_QUERY_RESULTS
      value: 100
      description: Maximum number of results returned from a query
      type: integer
    settings:
      data_format: JSON
      max_concurrent_queries: 5
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - example.com
    - '*.trusted-health.org'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: doctor@example.com
    current_user_name: Dr. John Doe
    hospital_name: City Hospital
    timezone: UTC-5
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - pandas
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true