name: personalized_nutrition_synthesizer
display_name: Personalized Nutrition Synthesizer
description: Assists users in creating personalized diet plans by fetching nutritional data for food items and customizing diet plans based on individual health requirements and preferences. Ensures users receive tailored nutritional guidance to meet their dietary goals.
category: health_and_wellness
complexity_level: 3
estimated_duration: 30
required_permissions:
- nutritional_data_access
- user_profile_access
dependencies: []
generation_weight: 1.5
sample_actions:
- fetch_nutritional_data
- customize_diet_plan
metadata:
  selection_way: random
  selection_num: 2
tags:
- nutrition
- health
- diet_planning
context:
  available_tools:
  - name: fetch_nutritional_data
    display_name: Fetch Nutritional Data
    description: Retrieve detailed nutritional information for specified food items.
    category: data_retrieval
    parameters: []
    example_usage:
    - fetch_nutritional_data(food_items=['apple', 'banana'])
    common_errors:
    - Food item not found
    - API rate limit exceeded
  - name: customize_diet_plan
    display_name: Customize Diet Plan
    description: Create or adjust a diet plan based on user health requirements and available food items.
    category: diet_planning
    parameters:
    - name: user_name
      type: string
      description: Name of the user for whom the diet plan is to be customized.
      required: true
    - name: diet_plan
      type: list
      description: List of food items selected for the diet plan.
      required: true
    example_usage:
    - customize_diet_plan(user_name='John Doe', diet_plan=['salad', 'chicken breast'])
  environment:
    name: nutrition_platform
    description: Platform environment with access to nutritional databases and user health profiles.
    variables:
    - name: NUTRITION_API_KEY
      value: 'your_api_key_here'
      description: API key for accessing nutritional data services.
      type: string
    - name: MAX_DIET_ITEMS
      value: 20
      description: Maximum number of items allowed in a diet plan.
      type: integer
    settings:
      diet_plan_format: JSON
      max_customizations_per_user: 5
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - nutritiondata.com
    - '*.trusted-health.org'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: nutritionist@example.com
    current_user_name: Nutrition Specialist
    company_name: HealthPlus Inc.
    timezone: UTC-4
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - numpy
    - pandas
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true