name: personalized_learning_plan
display_name: Personalized Learning Plan
description: Facilitates the creation and management of personalized learning plans by allowing users to search for historical sources, incorporate them into lesson plans, list available plans, and remove plans as needed. This scenario supports educators in tailoring educational content to individual learning needs.
category: education
complexity_level: 3
estimated_duration: 30
required_permissions:
- educational_content_access
- plan_management_access
dependencies: []
generation_weight: 1.5
sample_actions:
- search_sources
- incorporate_sources
- list_plans
- remove_plan
metadata:
  selection_way: random
  selection_num: 2
tags:
- education
- personalized_learning
- lesson_planning
context:
  available_tools:
  - name: search_sources
    display_name: Search Sources
    description: Search for sources related to a specific historical topic
    category: research
    parameters: []
    example_usage:
    - search_sources()
  - name: incorporate_sources
    display_name: Incorporate Sources
    description: Incorporate chosen sources into a lesson plan
    category: lesson_planning
    parameters:
    - name: source_titles
      type: list
      description: Titles of the sources to incorporate
      required: true
    example_usage:
    - incorporate_sources(source_titles=['Source 1', 'Source 2'])
  - name: list_plans
    display_name: List Plans
    description: List all available personalized learning plans
    category: management
    parameters: []
    example_usage:
    - list_plans()
  - name: remove_plan
    display_name: Remove Plan
    description: Remove a specified learning plan from the system
    category: management
    parameters:
    - name: plan_name
      type: string
      description: The name of the learning plan
      required: true
    example_usage:
    - remove_plan(plan_name='History Plan 1')
  environment:
    name: educational_platform
    description: Platform environment for managing educational content and personalized learning plans
    variables:
    - name: MAX_PLANS
      value: 100
      description: Maximum number of learning plans a user can create
      type: integer
    settings:
      default_plan_format: PDF
      max_sources_per_plan: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - educational-resources.com
    - '*.trusted-education-partner.com'
    blocked_domains:
    - '*.unverified-source.com'
  predefined_variables:
    current_user_email: educator@example.com
    current_user_name: Educator
    institution_name: Learning Institute
    timezone: UTC-6
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - numpy
    - pandas
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true