name: personalized_dream_therapy
display_name: Personalized Dream Therapy
description: Facilitates personalized dream therapy sessions by adjusting interpretation settings, listing session details, and managing scheduling. Aims to enhance therapeutic outcomes through tailored session management and interpretation adjustments.
category: mental_health
complexity_level: 3
estimated_duration: 45
required_permissions:
- client_data_access
- session_management_access
dependencies: []
generation_weight: 1.5
sample_actions:
- adjust_interpretation_settings
- list_settings
- list_sessions
- reschedule_session
metadata:
  selection_way: random
  selection_num: 4
tags:
- therapy
- mental_health
- session_management
context:
  available_tools:
  - name: adjust_interpretation_settings
    display_name: Adjust Interpretation Settings
    description: Modify the interpretation settings for a client's therapy session.
    category: therapy_management
    parameters:
    - name: client_id
      type: string
      description: The ID of the client.
      required: true
    - name: positive_interpretation_frequency
      type: number
      description: The revised frequency percentage for positive interpretation. Recommended range is 30-85.
      required: true
    example_usage:
    - adjust_interpretation_settings(client_id='client123', positive_interpretation_frequency=75)
  - name: list_settings
    display_name: List Settings
    description: Retrieve settings for all therapy sessions.
    category: session_management
    parameters: []
    example_usage:
    - list_settings()
  - name: list_sessions
    display_name: List Sessions
    description: List all currently scheduled therapy sessions.
    category: session_management
    parameters: []
    example_usage:
    - list_sessions()
  - name: reschedule_session
    display_name: Reschedule Session
    description: Change the timing of a specified therapy session.
    category: session_management
    parameters:
    - name: session_id
      type: string
      description: The ID of the session to reschedule.
      required: true
    - name: new_start_time
      type: string
      description: The new start time for the session in HH:MM format.
      required: true
    - name: new_end_time
      type: string
      description: The new end time for the session in HH:MM format.
      required: true
    example_usage:
    - reschedule_session(session_id='session456', new_start_time='14:00', new_end_time='15:00')
  environment:
    name: therapy_management_system
    description: A system environment for managing and scheduling therapy sessions.
    variables:
    - name: SESSION_DURATION_LIMIT
      value: 90
      description: Maximum duration for a therapy session in minutes.
      type: integer
    - name: DEFAULT_TIMEZONE
      value: 'UTC'
      description: Default timezone for scheduling sessions.
      type: string
    settings:
      session_notification: email
      max_sessions_per_day: 8
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - therapyplatform.com
    - '*.trusted-therapy-partner.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: therapist@example.com
    current_user_name: Lead Therapist
    organization_name: DreamTherapy Inc.
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - numpy
    - pandas
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true