name: physical_assistant
display_name: Physical Activity Assistant
description: Provides users with suggestions for physical activities tailored to their preferences and needs. Aims to promote a healthy lifestyle by offering a variety of exercise options and guidance.
category: health_and_wellness
complexity_level: 1
estimated_duration: 10
required_permissions: []
dependencies: []
generation_weight: 1.0
sample_actions:
- get_suggestions
metadata:
  selection_way: random
  selection_num: 1
tags:
- physical_activity
- health
- wellness
context:
  available_tools:
  - name: get_suggestions
    display_name: Get Suggestions
    description: Retrieve a list of suggested physical activities
    category: health_and_wellness
    parameters: []
    example_usage:
    - get_suggestions()
    common_errors:
    - No suggestions available
  environment:
    name: health_platform
    description: Platform environment for health and wellness applications
    variables: []
    settings:
      suggestion_format: JSON
    max_memory_mb: 128
    max_execution_time: 60
    network_access: false
  predefined_variables:
    current_user_name: Health Enthusiast
    preferred_activity_type: Cardio
    timezone: UTC
    business_hours: 6:00-22:00
  system_info:
    platform_version: '1.0'
    available_libraries:
    - numpy
    - pandas
  security_policy:
    data_classification_required: false
    external_sharing_approval: false
    encryption_at_rest: false
    audit_logging: false