name: policy_advisor
display_name: Policy Advisor
description: Assists in managing and updating access levels for policy documents, listing available documents, and publishing reports. Facilitates efficient policy management and ensures proper access control for teams and individuals.
category: document_management
complexity_level: 3
estimated_duration: 30
required_permissions:
- document_access
- report_generation
dependencies: []
generation_weight: 1.5
sample_actions:
- update_user_access
- fetch_current_access_levels
- list_policy_documents
- publish_report
metadata:
  selection_way: random
  selection_num: 4
tags:
- policy_management
- access_control
- document_handling
context:
  available_tools:
  - name: update_user_access
    display_name: Update User Access
    description: Change the access level of a specified team or individual for policy documents
    category: access_control
    parameters:
    - name: team
      type: string
      description: The name of the team whose access level should be modified
      required: true
    - name: access_level
      type: array
      description: The list of permissions to assign
      required: true
    example_usage:
    - update_user_access(team='Engineering', access_level=['view', 'edit'])
  - name: fetch_current_access_levels
    display_name: Fetch Current Access Levels
    description: Retrieve the current access levels for all teams regarding policy documents
    category: access_control
    parameters: []
    example_usage:
    - fetch_current_access_levels()
  - name: list_policy_documents
    display_name: List Policy Documents
    description: List all available policy documents in the system
    category: document_management
    parameters: []
    example_usage:
    - list_policy_documents()
  - name: publish_report
    display_name: Publish Report
    description: Generate and publish a report based on the given document
    category: report_generation
    parameters:
    - name: document_name
      type: string
      description: The name of the document
      required: true
    example_usage:
    - publish_report(document_name='Annual Policy Review')
  environment:
    name: policy_management_system
    description: System environment for managing policy documents and access levels
    variables:
    - name: POLICY_DATABASE_URL
      value: 'https://policies.example.com/database'
      description: URL to the policy document database
      type: string
    - name: MAX_ACCESS_LEVELS
      value: 5
      description: Maximum number of access levels assignable
      type: integer
    settings:
      report_format: PDF
      max_documents_per_report: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - example.com
    - '*.trusted-partner.com'
    blocked_domains:
    - '*.unauthorized-site.com'
  predefined_variables:
    current_user_email: admin@example.com
    current_user_name: Policy Admin
    company_name: PolicyCorp Inc.
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.0'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true