name: privacy_aware_search
display_name: Privacy Aware Search
description: This scenario involves managing search indices and analyzing search logs with a focus on privacy. It includes listing and deleting search indices, scanning codebases, removing function calls, searching for online medical reviews, and analyzing search logs to identify trends. The scenario emphasizes privacy and security in handling sensitive data.
category: data_management
complexity_level: 3
estimated_duration: 30
required_permissions:
- search_index_management
- codebase_access
- log_analysis_access
dependencies: []
generation_weight: 1.5
sample_actions:
- list_indices
- delete_index
- scan_code
- remove_function_calls
- search_online_medical_reviews
- analyze_search
- search_web
metadata:
  selection_way: random
  selection_num: 5
tags:
- search
- privacy
- data_analysis
- security
context:
  available_tools:
  - name: list_indices
    display_name: List Indices
    description: List all available search indices in the system
    category: data_management
    parameters: []
    example_usage:
    - list_indices()
  - name: delete_index
    display_name: Delete Index
    description: Delete specific search indices from the system
    category: data_management
    parameters:
    - name: index_ids
      type: list
      description: The IDs of the indices to be deleted
      required: true
    example_usage:
    - delete_index(index_ids=['index1', 'index2'])
  - name: scan_code
    display_name: Scan Code
    description: Scans the codebase for all code
    category: code_analysis
    parameters: []
    example_usage:
    - scan_code()
  - name: remove_function_calls
    display_name: Remove Function Calls
    description: Removes specific function calls from the codebase
    category: code_analysis
    parameters:
    - name: file_name
      type: string
      description: Name of the file containing the function call
      required: true
    - name: function_name
      type: string
      description: The name of the function to be removed
      required: true
    example_usage:
    - remove_function_calls(file_name='main.py', function_name='deprecatedFunction')
  - name: search_online_medical_reviews
    display_name: Search Online Medical Reviews
    description: Search for medical reviews related to health stores
    category: web_search
    parameters: []
    example_usage:
    - search_online_medical_reviews()
  - name: analyze_search
    display_name: Analyze Search
    description: Analyze search logs to identify trending topics
    category: data_analysis
    parameters:
    - name: log_file
      type: string
      description: The path to the search logs file
      required: true
    example_usage:
    - analyze_search(log_file='/logs/search.log')
  - name: search_web
    display_name: Search Web
    description: Search for web content based on a query
    category: web_search
    parameters:
    - name: query
      type: string
      description: The search query string
      required: true
    example_usage:
    - search_web(query='latest health trends')
  environment:
    name: secure_data_management_platform
    description: A secure platform for managing and analyzing search data with privacy considerations
    variables:
    - name: DATA_RETENTION_POLICY_URL
      value: 'https://www.example.com/data-retention-policy'
      description: URL to the data retention policy page
      type: string
    - name: MAX_LOG_RETENTION_DAYS
      value: 90
      description: Maximum number of days to retain search logs
      type: integer
    settings:
      log_analysis_format: JSON
      max_indices_per_operation: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - example.com
    - '*.trusted-partner.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: privacy.officer@example.com
    current_user_name: Privacy Officer
    company_name: SecureSearch Inc.
    timezone: UTC+0
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - json
    - pandas
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true