name: profile_management
display_name: Profile Management
description: This scenario involves retrieving the latest profile information for a user. It tests the agent's ability to access and handle user profile data securely and efficiently, ensuring that the correct information is retrieved and presented.
category: user_management
complexity_level: 1
estimated_duration: 10
required_permissions:
- user_profile_access
dependencies: []
generation_weight: 1.0
sample_actions:
- get_user_profile
metadata:
  selection_way: random
  selection_num: 1
tags:
- user_profile
- data_retrieval
context:
  available_tools:
  - name: get_user_profile
    display_name: Get User Profile
    description: Retrieve the latest profile information for a user
    category: user_management
    parameters:
    - name: profile_name
      type: string
      description: The name of the user whose profile is being requested
      required: true
    example_usage:
    - get_user_profile(profile_name='john_doe')
  environment:
    name: user_data_platform
    description: Platform environment for managing and retrieving user data
    variables:
    - name: USER_DATA_API_URL
      value: 'https://api.example.com/user-data'
      description: URL to the user data API
      type: string
    settings:
      max_profile_requests_per_minute: 60
    max_memory_mb: 128
    max_execution_time: 60
    network_access: true
    allowed_domains:
    - api.example.com
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: admin@example.com
    current_user_name: System Administrator
    company_name: DataCorp Inc.
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '1.0'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true