name: psychological_stress_simulator
display_name: Psychological Stress Simulator
description: Simulates various stress-inducing scenarios to test the psychological resilience and response of emergency responders and participants. The simulation includes adjusting stress levels, executing stress scenarios, and monitoring the impact on individuals.
category: psychological_testing
complexity_level: 3
estimated_duration: 45
required_permissions:
- stress_data_access
- scenario_execution_access
dependencies: []
generation_weight: 1.5
sample_actions:
- list_apps
- get_emergency_responders_info
- adjust_stress_level
- simulate_stress_scenario
- check_stress_scenarios
- check_patient_info
metadata:
  selection_way: random
  selection_num: 5
tags:
- stress_simulation
- emergency_response
- psychological_testing
context:
  available_tools:
  - name: list_apps
    display_name: List Applications
    description: Retrieve a list of all available applications for stress simulation.
    category: system_management
    parameters: []
    example_usage:
    - list_apps()
  - name: get_emergency_responders_info
    display_name: Get Emergency Responders Info
    description: Access information about emergency responders involved in the simulation.
    category: data_access
    parameters: []
    example_usage:
    - get_emergency_responders_info()
  - name: adjust_stress_level
    display_name: Adjust Stress Level
    description: Modify the stress levels of responders to simulate environmental changes.
    category: stress_management
    parameters:
    - name: new_stress_level
      type: string
      description: The target stress level to simulate changes in the environment (e.g., 80).
      required: true
    example_usage:
    - adjust_stress_level(new_stress_level='80')
  - name: simulate_stress_scenario
    display_name: Simulate Stress Scenario
    description: Execute a stress-inducing scenario with specific settings for a participant.
    category: scenario_execution
    parameters:
    - name: scenario_title
      type: string
      description: The title of the stress scenario to simulate.
      required: true
    - name: participant_name
      type: string
      description: The name of the participant involved in the scenario.
      required: true
    example_usage:
    - simulate_stress_scenario(scenario_title='High Pressure Drill', participant_name='John Doe')
  - name: check_stress_scenarios
    display_name: Check Stress Scenarios
    description: Review existing stress scenarios available for simulation.
    category: scenario_management
    parameters: []
    example_usage:
    - check_stress_scenarios()
  - name: check_patient_info
    display_name: Check Patient Info
    description: Access information about patients involved in the stress simulation.
    category: data_access
    parameters: []
    example_usage:
    - check_patient_info()
  environment:
    name: stress_simulation_lab
    description: A controlled environment for conducting psychological stress simulations with necessary tools and data access.
    variables:
    - name: MAX_STRESS_LEVEL
      value: 100
      description: Maximum allowable stress level for simulations.
      type: integer
    - name: SCENARIO_DB_URL
      value: 'https://simulation.example.com/scenarios'
      description: URL to the database of available stress scenarios.
      type: string
    settings:
      stress_level_unit: percentage
      max_participants_per_scenario: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - simulation.example.com
    - '*.trusted-research.org'
    blocked_domains:
    - '*.unverified-source.com'
  predefined_variables:
    current_user_email: researcher@example.com
    current_user_name: Simulation Researcher
    organization_name: Stress Research Institute
    timezone: UTC+0
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.0'
    available_libraries:
    - numpy
    - pandas
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true