name: quantum_communication_network
display_name: Quantum Communication Network
description: This scenario involves managing and optimizing a Quantum Communication Network. It includes tasks such as retrieving encryption protocols, monitoring node statuses, adjusting latencies, managing routing paths, and setting up secure communication channels. The scenario is designed to ensure the network's efficiency, security, and reliability.
category: network_management
complexity_level: 4
estimated_duration: 45
required_permissions:
- network_configuration_access
- encryption_management_access
dependencies: []
generation_weight: 1.5
sample_actions:
- get_encryption_protocol
- get_node_status
- adjust_node_latency
- list_routing_paths
- modify_routing_path
metadata:
  selection_way: random
  selection_num: 5
tags:
- quantum_network
- encryption
- network_management
context:
  available_tools:
  - name: get_encryption_protocol
    display_name: Get Encryption Protocol
    description: Retrieve details about specific encryption protocols used in the Quantum Communication Network.
    category: security
    parameters: []
    example_usage:
    - get_encryption_protocol()
  - name: get_node_status
    display_name: Get Node Status
    description: Retrieve the current status and latency of a specified node.
    category: network_monitoring
    parameters:
    - name: node_name
      type: string
      description: The name of the node to get status information for.
      required: true
    example_usage:
    - get_node_status(node_name='NodeA')
  - name: adjust_node_latency
    display_name: Adjust Node Latency
    description: Modify the configuration to adjust the latency of a node.
    category: network_configuration
    parameters:
    - name: node_name
      type: string
      description: The name of the node to adjust.
      required: true
    - name: target_latency
      type: string
      description: The target latency to achieve for this node.
      required: true
    example_usage:
    - adjust_node_latency(node_name='NodeA', target_latency='10ms')
  environment:
    name: quantum_network_environment
    description: Environment for managing a quantum communication network with encryption and node management tools.
    variables:
    - name: NETWORK_POLICY_URL
      value: 'https://www.example.com/network-policy'
      description: URL to the network policy page
      type: string
    - name: MAX_NODE_LATENCY
      value: '50ms'
      description: Maximum allowable latency for nodes
      type: string
    settings:
      encryption_protocol: QuantumKeyDistribution
      max_nodes: 100
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - example.com
    - '*.secure-network.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: admin@network.com
    current_user_name: Network Administrator
    company_name: QuantumNet Inc.
    timezone: UTC+0
    business_hours: 0:00-23:59
  system_info:
    platform_version: '3.0'
    available_libraries:
    - quantum
    - networkx
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true