name: quantum_encryption_network
display_name: Quantum Encryption Network
description: This scenario involves managing and interacting with a Quantum Encryption Network. It includes tasks such as listing transactions, decrypting specific transactions, designing new communication protocols, managing network nodes, generating encryption certificates, and modifying routing paths. The scenario is designed to test the AI's ability to handle secure communications and network management in a quantum encryption context.
category: network_security
complexity_level: 4
estimated_duration: 45
required_permissions:
- network_management_access
- encryption_key_access
dependencies: []
generation_weight: 1.5
sample_actions:
- list_transactions
- decrypt_transaction
- create_protocol
- list_nodes
- generate_encryption_certificate
- list_routing_paths
- modify_routing_path
metadata:
  selection_way: random
  selection_num: 5
tags:
- quantum
- encryption
- network_management
- security
context:
  available_tools:
  - name: list_transactions
    display_name: List Transactions
    description: List all recent transactions in the Quantum Encryption Network.
    category: network_management
    parameters: []
    example_usage:
    - list_transactions()
  - name: decrypt_transaction
    display_name: Decrypt Transaction
    description: Decrypt a specific transaction to view its contents.
    category: security
    parameters:
    - name: transaction_id
      type: string
      description: The ID of the transaction to decrypt.
      required: true
    example_usage:
    - decrypt_transaction(transaction_id='txn12345')
  - name: create_protocol
    display_name: Create Protocol
    description: Design new communication protocols based on security and efficiency requirements.
    category: protocol_design
    parameters:
    - name: requirements
      type: string
      description: Detailed description of the security and efficiency needs for the protocol.
      required: false
    example_usage:
    - create_protocol(requirements='AES-256 encryption with low latency')
  - name: list_nodes
    display_name: List Nodes
    description: List all nodes in the Quantum Encryption Network along with their capabilities.
    category: network_management
    parameters: []
    example_usage:
    - list_nodes()
  - name: generate_encryption_certificate
    display_name: Generate Encryption Certificate
    description: Generate a new encryption certificate for a network node.
    category: security
    parameters:
    - name: node_id
      type: string
      description: The ID of the network node to generate a new certificate for.
      required: true
    example_usage:
    - generate_encryption_certificate(node_id='node42')
  - name: list_routing_paths
    display_name: List Routing Paths
    description: List all available routing paths in the network.
    category: network_management
    parameters: []
    example_usage:
    - list_routing_paths()
  - name: modify_routing_path
    display_name: Modify Routing Path
    description: Modify or remove specific routing paths in the network.
    category: network_management
    parameters:
    - name: path_id
      type: string
      description: The ID of the routing path to be modified.
      required: true
    - name: action
      type: string
      description: The action to be taken on the path, such as 'disable', 'enable', or 'delete'.
      required: true
    example_usage:
    - modify_routing_path(path_id='path123', action='disable')
  environment:
    name: quantum_network_environment
    description: Environment for managing and securing a quantum encryption network.
    variables:
    - name: NETWORK_API_URL
      value: 'https://api.quantum-network.com'
      description: Base URL for network API access
      type: string
    - name: MAX_TRANSACTION_LOGS
      value: 1000
      description: Maximum number of transaction logs to retrieve
      type: integer
    settings:
      encryption_standard: Quantum-Resistant
      max_nodes: 50
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - quantum-network.com
    - '*.secure-partner.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: admin@quantum-network.com
    current_user_name: Network Administrator
    company_name: QuantumNet Inc.
    timezone: UTC
    business_hours: 0:00-23:59
  system_info:
    platform_version: '3.1'
    available_libraries:
    - quantumcrypt
    - netmanage
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true