name: quantum_computing_ethicist
display_name: Quantum Computing Ethicist
description: This scenario involves managing ethical advisories and datasets related to quantum computing. The agent will list current advisories, update advisory documents to align with ethical guidelines, list available datasets, and remove specified data from datasets. The focus is on ensuring ethical compliance and data integrity in quantum computing research and applications.
category: ethics_management
complexity_level: 3
estimated_duration: 30
required_permissions:
- advisory_management_access
- dataset_management_access
dependencies: []
generation_weight: 1.5
sample_actions:
- list_current_advisories
- update_advisory_document
- list_datasets
- remove_data
metadata:
  selection_way: random
  selection_num: 4
tags:
- ethics
- quantum_computing
- data_management
context:
  available_tools:
  - name: list_current_advisories
    display_name: List Current Advisories
    description: List the details of existing advisories.
    category: advisory_management
    parameters: []
    example_usage:
    - list_current_advisories()
  - name: update_advisory_document
    display_name: Update Advisory Document
    description: Modify the content of an advisory document to ensure it aligns with the latest ethical guidelines and strategies.
    category: advisory_management
    parameters:
    - name: advisory_id
      type: string
      description: The ID of the advisory document to be updated.
      required: true
    - name: new_content
      type: string
      description: The revised content for the advisory document.
      required: true
    example_usage:
    - update_advisory_document(advisory_id='adv123', new_content='Updated ethical guidelines...')
  - name: list_datasets
    display_name: List Datasets
    description: List all available datasets.
    category: data_management
    parameters: []
    example_usage:
    - list_datasets()
  - name: remove_data
    display_name: Remove Data
    description: Remove specified data from a dataset.
    category: data_management
    parameters:
    - name: dataset_name
      type: string
      description: The name of the dataset from which to remove data.
      required: true
    example_usage:
    - remove_data(dataset_name='quantum_research_data')
  environment:
    name: quantum_ethics_lab
    description: A controlled environment for managing ethical advisories and datasets in quantum computing.
    variables:
    - name: ETHICAL_GUIDELINES_URL
      value: 'https://www.example.com/ethical-guidelines'
      description: URL to the ethical guidelines document
      type: string
    - name: MAX_DATASET_SIZE_MB
      value: 500
      description: Maximum size of datasets in megabytes
      type: integer
    settings:
      advisory_update_format: Markdown
      max_advisories_per_update: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - example.com
    - '*.trusted-research.org'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: ethics_officer@example.com
    current_user_name: Ethics Officer
    organization_name: Quantum Research Institute
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.0'
    available_libraries:
    - requests
    - yaml
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true