name: quantum_weather_forecasting
display_name: Quantum Weather Forecasting
description: This scenario involves reading and executing quantum computing scripts to forecast weather patterns. The agent must handle file operations and execute quantum code efficiently, ensuring accurate weather predictions using quantum algorithms.
category: scientific_computing
complexity_level: 4
estimated_duration: 45
required_permissions:
- file_system_access
- quantum_execution_access
dependencies: []
generation_weight: 1.5
sample_actions:
- read_file
- execute_code
metadata:
  selection_way: random
  selection_num: 2
tags:
- quantum_computing
- weather_forecasting
- file_operations
context:
  available_tools:
  - name: read_file
    display_name: Read File
    description: Read the content of a specified file
    category: file_operations
    parameters:
    - name: file_name_or_path
      type: string
      description: The name or path of the file to be read
      required: true
    example_usage:
    - read_file(file_name_or_path='data/input.txt')
    common_errors:
    - File not found
    - Permission denied
  - name: execute_code
    display_name: Execute Code
    description: Execute a quantum computing script
    category: quantum_computing
    parameters:
    - name: file_name_or_path
      type: string
      description: The name of the file to run
      required: true
    example_usage:
    - execute_code(file_name_or_path='scripts/forecast.qc')
    common_errors:
    - Syntax error in code
    - Execution timeout
  environment:
    name: quantum_computing_lab
    description: A simulated environment for running quantum computing tasks
    variables:
    - name: QUANTUM_API_KEY
      value: 'your-api-key-here'
      description: API key for accessing quantum computing resources
      type: string
    - name: MAX_EXECUTION_TIME
      value: 300
      description: Maximum execution time for quantum tasks in seconds
      type: integer
    settings:
      quantum_backend: 'ibmq_qasm_simulator'
      max_file_size_mb: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - quantum.example.com
    - '*.trusted-quantum-provider.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: researcher@quantumlab.com
    current_user_name: Quantum Researcher
    organization_name: QuantumLab Inc.
    timezone: UTC
    working_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - qiskit
    - numpy
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true