name: radioactive_waste_tracker
display_name: Radioactive Waste Tracker
description: Manages and tracks radioactive waste items, ensuring accurate status updates and inventory management. Facilitates compliance with safety regulations by providing tools to list and update the status of waste items.
category: environmental_management
complexity_level: 3
estimated_duration: 30
required_permissions:
- inventory_management_access
- status_update_access
dependencies: []
generation_weight: 1.5
sample_actions:
- list_items
- update_status
metadata:
  selection_way: random
  selection_num: 2
tags:
- waste_management
- compliance
- safety
context:
  available_tools:
  - name: list_items
    display_name: List Items
    description: List all items in the radioactive waste management system
    category: inventory_management
    parameters: []
    example_usage:
    - list_items()
  - name: update_status
    display_name: Update Status
    description: Update the status of a radioactive waste item
    category: inventory_management
    parameters:
    - name: item_id
      type: string
      description: The id of the item
      required: true
    - name: status
      type: string
      description: The new status of the item
      required: true
    example_usage:
    - update_status(item_id='RW123', status='disposed')
  environment:
    name: waste_management_system
    description: System environment for managing radioactive waste items with inventory and status update capabilities
    variables:
    - name: SAFETY_COMPLIANCE_URL
      value: 'https://www.example.com/safety-compliance'
      description: URL to the safety compliance guidelines
      type: string
    - name: MAX_ITEMS_TRACKED
      value: 1000
      description: Maximum number of waste items that can be tracked
      type: integer
    settings:
      status_update_format: JSON
      max_status_updates_per_hour: 50
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - example.com
    - '*.trusted-regulatory.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: waste_manager@example.com
    current_user_name: Waste Management Officer
    company_name: SafeWaste Inc.
    timezone: UTC+0
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true