name: real_time_translation
display_name: Real-Time Translation
description: Facilitates the translation of text, documents, and speech in real-time across multiple languages. This scenario supports various translation tasks including reading documents, translating text and speech, and updating translations to improve accuracy. It is designed to handle real-time communication needs in multilingual environments, though it may have limitations with specialized terminology.
category: language_translation
complexity_level: 3
estimated_duration: 30
required_permissions: []
dependencies: []
generation_weight: 1.5
sample_actions:
- read_document
- translate_text
- translate_document
- translate_audio_into_text
- update_translation
- translate_speech
- translate_text2Chinese
- fetch_content
metadata:
  selection_way: random
  selection_num: 4
tags:
- translation
- multilingual
- real-time
- communication
context:
  available_tools:
  - name: read_document
    display_name: Read Document
    description: Read the content of the given document which is to be translated.
    category: document_processing
    parameters:
    - name: document_name_or_path
      type: string
      description: The name or path of the document to be translated.
      required: true
  - name: translate_text
    display_name: Translate Text
    description: Translate a given block of text from one language to another.
    category: text_translation
    parameters:
    - name: text
      type: string
      description: The text content to be translated.
      required: true
    - name: source_language
      type: string
      description: The original language of the text.
      required: false
    - name: target_language
      type: string
      description: The language to translate the text into.
      required: true
  - name: translate_document
    display_name: Translate Document
    description: Translate the given document into the specified language.
    category: document_translation
    parameters:
    - name: document_name_or_path
      type: string
      description: The name or path of the document to be translated.
      required: true
    - name: language
      type: string
      description: The language to translate the document into.
      required: true
    - name: output_document_name_or_path
      type: string
      description: The name or path of the output translated document.
      required: true
  - name: translate_audio_into_text
    display_name: Translate Audio into Text
    description: Translate audio input from the user into text output.
    category: audio_processing
    parameters:
    - name: url
      type: string
      description: The URL of the audio input.
      required: true
  - name: update_translation
    display_name: Update Translation
    description: Update the translation of a certain phrase to enhance translation accuracy.
    category: translation_update
    parameters:
    - name: phrase
      type: string
      description: The given phrase.
      required: true
    - name: target_translation
      type: string
      description: The updated translation of the phrase.
      required: true
  - name: translate_speech
    display_name: Translate Speech
    description: Translate real-time speech between specified languages.
    category: speech_translation
    parameters:
    - name: text_in
      type: string
      description: The original text input to be translated.
      required: true
    - name: language_in
      type: string
      description: The language of the input text.
      required: true
    - name: language_out
      type: string
      description: The language for the translation output.
      required: true
  environment:
    name: multilingual_platform
    description: Platform environment supporting multilingual communication and translation tools.
    variables:
    - name: TRANSLATION_API_KEY
      value: 'your_api_key_here'
      description: API key for accessing translation services.
      type: string
    - name: SUPPORTED_LANGUAGES
      value: ['en', 'es', 'fr', 'de', 'zh']
      description: List of supported languages for translation.
      type: list
    settings:
      max_text_length: 5000
      max_audio_duration: 300
    max_memory_mb: 512
    max_execution_time: 240
    network_access: true
    allowed_domains:
    - translationapi.com
    - '*.trusted-translation.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: translator@example.com
    current_user_name: Translation Agent
    company_name: GlobalTrans Inc.
    timezone: UTC
    business_hours: 24/7
  system_info:
    platform_version: '3.0'
    available_libraries:
    - requests
    - json
    - speech_recognition
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true