name: remote_equipment_maintenance
display_name: Remote Equipment Maintenance
description: Facilitates the management and maintenance of remote equipment, allowing operators to update maintenance schedules, list equipment status, and control operations remotely. Ensures efficient and safe operation of equipment through timely updates and controls.
category: equipment_management
complexity_level: 3
estimated_duration: 30
required_permissions:
- equipment_control_access
- maintenance_schedule_access
dependencies: []
generation_weight: 1.5
sample_actions:
- remove_schedule
- list_turbines
- disable_operations
- update_maintenance_status
metadata:
  selection_way: random
  selection_num: 4
tags:
- maintenance
- equipment_management
- remote_operations
context:
  available_tools:
  - name: remove_schedule
    display_name: Remove Schedule
    description: Removes a maintenance schedule from the system
    category: maintenance_management
    parameters:
    - name: schedule_id
      type: string
      description: The ID of the schedule to remove
      required: true
    example_usage:
    - remove_schedule(schedule_id='sched123')
  - name: list_turbines
    display_name: List Turbines
    description: Lists all turbines and their current status
    category: equipment_status
    parameters: []
    example_usage:
    - list_turbines()
  - name: disable_operations
    display_name: Disable Operations
    description: Disables operations for a specified turbine
    category: equipment_control
    parameters:
    - name: turbine_name
      type: string
      description: The name of the turbine
      required: true
    example_usage:
    - disable_operations(turbine_name='TurbineA')
  - name: update_maintenance_status
    display_name: Update Maintenance Status
    description: Update the maintenance status of a specific equipment
    category: maintenance_management
    parameters:
    - name: equipment_id
      type: string
      description: The ID of the equipment
      required: true
    - name: status
      type: string
      description: The new status to be updated
      required: true
    example_usage:
    - update_maintenance_status(equipment_id='equip456', status='Under Maintenance')
  environment:
    name: remote_management_system
    description: System environment for managing remote equipment operations and maintenance
    variables:
    - name: MAINTENANCE_API_URL
      value: 'https://api.example.com/maintenance'
      description: API endpoint for maintenance operations
      type: string
    - name: MAX_CONCURRENT_OPERATIONS
      value: 10
      description: Maximum number of concurrent operations allowed
      type: integer
    settings:
      operation_timeout: 120
      max_schedules_per_day: 5
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - example.com
    - '*.trusted-equipment.com'
    blocked_domains:
    - '*.unauthorized-access.com'
  predefined_variables:
    current_user_email: operator@example.com
    current_user_name: Equipment Operator
    company_name: Industrial Solutions Inc.
    timezone: UTC+0
    business_hours: 6:00-20:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true