name: remote_work_security
display_name: Remote Work Security Management
description: This scenario involves managing security aspects of remote work environments, including editing presentations, listing employees, managing VPN access, and controlling network domain access. It ensures that remote employees have the appropriate access and resources while maintaining network security.
category: security_management
complexity_level: 3
estimated_duration: 30
required_permissions:
- vpn_access_management
- employee_data_access
- network_configuration_access
dependencies: []
generation_weight: 1.5
sample_actions:
- add_slide
- list_employees
- list_vpn_domains
- adjust_vpn_access
- manage_network_access
metadata:
  selection_way: random
  selection_num: 5
tags:
- remote_work
- security
- vpn
- network_management
context:
  available_tools:
  - name: add_slide
    display_name: Add Slide to Presentation
    description: Edit a presentation by adding a slide with specified title and content.
    category: document_management
    parameters:
    - name: file_name
      type: string
      description: Name of the presentation file.
      required: true
    - name: slide_title
      type: string
      description: Title of the new slide.
      required: true
    - name: slide_content
      type: string
      description: Content of the new slide.
      required: true
  - name: list_employees
    display_name: List Remote Employees
    description: List all remote employees and their roles.
    category: human_resources
    parameters: []
  - name: list_vpn_domains
    display_name: List VPN Domains
    description: Retrieve the list of VPN domains with specific access permissions.
    category: network_management
    parameters: []
  - name: adjust_vpn_access
    display_name: Adjust VPN Access
    description: Adjust the VPN access level for a specific employee.
    category: network_management
    parameters:
    - name: employee_id
      type: string
      description: The ID of the employee.
      required: true
    - name: access_level
      type: string
      description: The VPN access level to be set (e.g., none, limited, full).
      required: true
  - name: manage_network_access
    display_name: Manage Network Access
    description: Manage which domains the remote employees can access when connected to the company network.
    category: network_management
    parameters:
    - name: block_level
      type: string
      description: Either 'block', 'unblock', or 'staff-only'.
      required: true
    - name: domain
      type: string
      description: The URL of the domain to change block level.
      required: true
  environment:
    name: corporate_network
    description: Corporate network environment with security and VPN management tools.
    variables:
    - name: VPN_POLICY_URL
      value: 'https://www.example.com/vpn-policy'
      description: URL to the VPN policy page
      type: string
    - name: MAX_VPN_CONNECTIONS
      value: 100
      description: Maximum number of concurrent VPN connections allowed
      type: integer
    settings:
      vpn_access_levels: ['none', 'limited', 'full']
      default_block_level: 'block'
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - company.com
    - '*.trusted-partner.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: admin@company.com
    current_user_name: Network Administrator
    company_name: TechCorp Inc.
    timezone: UTC-6
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.0'
    available_libraries:
    - requests
    - json
    - os
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true