name: research_database
display_name: Research Database
description: Facilitates the retrieval of recent research papers based on specified topics. This scenario is designed to assist researchers and academics in quickly accessing the latest studies and publications relevant to their field of interest.
category: research_assistance
complexity_level: 1
estimated_duration: 5
required_permissions:
- internet_access
dependencies: []
generation_weight: 1.0
sample_actions:
- retrieve_papers
- filter_by_topic
metadata:
  selection_way: random
  selection_num: 1
tags:
- research
- academic
- information_retrieval
context:
  available_tools:
  - name: retrieve_papers
    display_name: Retrieve Papers
    description: Fetch recent research papers based on a given topic
    category: research
    parameters:
    - name: topic
      type: string
      description: The topic of the research papers to retrieve
      required: true
    example_usage:
    - retrieve_papers(topic='artificial intelligence')
    common_errors:
    - Invalid topic specified
    - No papers found for the given topic
  environment:
    name: academic_research_platform
    description: An environment equipped with tools and resources for academic research and paper retrieval
    variables:
    - name: API_ENDPOINT
      value: 'https://api.researchpapers.com/v1'
      description: Endpoint for accessing research paper data
      type: string
    settings:
      max_results_per_query: 50
    max_memory_mb: 128
    max_execution_time: 60
    network_access: true
    allowed_domains:
    - researchpapers.com
    - '*.edu'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: researcher@example.com
    current_user_name: Researcher
    institution_name: Global University
    timezone: UTC
    working_hours: 9:00-17:00
  system_info:
    platform_version: '1.0'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: false
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true