name: retail_fraud_detection
display_name: Retail Fraud Detection
description: This scenario involves detecting and managing fraudulent activities in a retail environment. It includes retrieving transactions, marking transactions as fraudulent, and managing detection rules. The goal is to ensure the integrity of financial transactions and prevent fraud.
category: fraud_management
complexity_level: 3
estimated_duration: 30
required_permissions:
- transaction_data_access
- fraud_detection_management
dependencies: []
generation_weight: 1.5
sample_actions:
- retrieve_transactions
- mark_as_fraudulent
- list_flagged_transactions
- approve_transaction
metadata:
  selection_way: random
  selection_num: 5
tags:
- fraud
- transactions
- security
context:
  available_tools:
  - name: retrieve_transactions
    display_name: Retrieve Transactions
    description: Retrieve a list of recent transactions.
    category: transaction_management
    parameters: []
    example_usage:
    - retrieve_transactions()
  - name: mark_as_fraudulent
    display_name: Mark as Fraudulent
    description: Mark a transaction as fraudulent.
    category: fraud_management
    parameters:
    - name: transaction_id
      type: string
      description: The ID of the transaction to mark as fraudulent.
      required: true
    example_usage:
    - mark_as_fraudulent(transaction_id='txn12345')
  - name: list_flagged_transactions
    display_name: List Flagged Transactions
    description: List all transactions that have been flagged as potentially fraudulent.
    category: fraud_management
    parameters: []
    example_usage:
    - list_flagged_transactions()
  - name: approve_transaction
    display_name: Approve Transaction
    description: Approve a flagged transaction if it is deemed valid.
    category: fraud_management
    parameters:
    - name: transaction_id
      type: string
      description: The unique identifier of the transaction to approve.
      required: true
    example_usage:
    - approve_transaction(transaction_id='txn12345')
  environment:
    name: retail_fraud_detection_system
    description: Environment for managing and detecting fraudulent activities in retail transactions.
    variables:
    - name: FRAUD_ALERT_EMAIL
      value: 'alerts@retailcorp.com'
      description: Email address to send fraud alerts.
      type: string
    - name: MAX_ALERTS_PER_HOUR
      value: 100
      description: Maximum number of alerts allowed per hour.
      type: integer
    settings:
      alert_format: JSON
      max_transactions_per_query: 50
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - retailcorp.com
    - '*.trusted-partner.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: fraud.detection@retailcorp.com
    current_user_name: Fraud Detection Specialist
    company_name: RetailCorp Inc.
    timezone: UTC-5
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.0'
    available_libraries:
    - requests
    - json
    - pandas
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true