name: safe_child_content_filter
display_name: Safe Child Content Filter
description: This scenario involves managing content filters to ensure child safety. It includes listing current filters, disabling specific filters, adjusting filter settings, reviewing available content, and flagging inappropriate content. The goal is to maintain a safe digital environment for children by effectively managing content filters and reviewing content for appropriateness.
category: content_management
complexity_level: 3
estimated_duration: 30
required_permissions:
- content_management_access
- filter_configuration_access
dependencies: []
generation_weight: 1.5
sample_actions:
- list_filters
- disable_filter
- adjust_filter_settings
- list_contents
- flag_content
metadata:
  selection_way: random
  selection_num: 5
tags:
- child_safety
- content_filtering
- digital_wellbeing
context:
  available_tools:
  - name: list_filters
    display_name: List Filters
    description: List all content filters currently in place
    category: content_management
    parameters: []
    example_usage:
    - list_filters()
  - name: disable_filter
    display_name: Disable Filter
    description: Disables a specified content filter
    category: content_management
    parameters:
    - name: filter_name
      type: string
      description: The name of the filter to disable
      required: true
    example_usage:
    - disable_filter(filter_name='adult_content_filter')
  - name: adjust_filter_settings
    display_name: Adjust Filter Settings
    description: Adjusts the settings for a given filter
    category: content_management
    parameters:
    - name: filter_name
      type: string
      description: Name of the filter to be adjusted
      required: true
    - name: new_restrictions
      type: list
      description: New restrictions to be applied to the filter
      required: true
    example_usage:
    - adjust_filter_settings(filter_name='chat_filter', new_restrictions=['no_profanity', 'no_personal_info'])
  - name: list_contents
    display_name: List Contents
    description: List all available content for review
    category: content_management
    parameters: []
    example_usage:
    - list_contents()
  - name: flag_content
    display_name: Flag Content
    description: Flag a content as inappropriate if necessary
    category: content_management
    parameters:
    - name: content_title
      type: string
      description: The title of the content to be flagged
      required: true
    - name: reason
      type: string
      description: The reason for flagging the content (e.g., safety risk, age-inappropriate)
      required: true
    example_usage:
    - flag_content(content_title='Violent Cartoon', reason='age-inappropriate')
  environment:
    name: child_safe_platform
    description: A platform dedicated to ensuring child safety through content filtering and review
    variables:
    - name: FILTER_POLICY_URL
      value: 'https://www.example.com/filter-policy'
      description: URL to the content filter policy page
      type: string
    - name: MAX_CONTENT_REVIEW_DAYS
      value: 7
      description: Maximum number of days allowed for content review
      type: integer
    settings:
      filter_update_frequency: daily
      max_filters_per_user: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - example.com
    - '*.trusted-content.com'
    blocked_domains:
    - '*.unsafe-content.com'
  predefined_variables:
    current_user_email: admin@example.com
    current_user_name: Content Safety Officer
    organization_name: SafeNet Inc.
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true