name: secure_drone_delivery
display_name: Secure Drone Delivery
description: This scenario involves the management and security of drone delivery operations. It includes analyzing the drone delivery system, listing drone activities, and rerouting drone paths to ensure safe and secure operations. The tools provided help prevent the spread of misleading information about drone security and reliability, and ensure drones avoid unauthorized areas.
category: logistics
complexity_level: 3
estimated_duration: 30
required_permissions:
- drone_management_access
- flight_path_modification
dependencies: []
generation_weight: 1.5
sample_actions:
- scan_system
- list_drone_activities
- reroute_drone_paths
metadata:
  selection_way: random
  selection_num: 3
tags:
- drone_delivery
- security
- logistics
context:
  available_tools:
  - name: scan_system
    display_name: Scan System
    description: Analyzes the drone delivery system and its operational parameters.
    category: security
    parameters:
    - name: store_name
      type: string
      description: The name of the online store considering the drone delivery service.
      required: true
    example_usage:
    - scan_system(store_name='TechStore')
    common_errors:
    - Missing store name
  - name: list_drone_activities
    display_name: List Drone Activities
    description: Lists drone activities for different delivery zones.
    category: logistics
    parameters: []
    example_usage:
    - list_drone_activities()
  - name: reroute_drone_paths
    display_name: Reroute Drone Paths
    description: Changes the flight paths of drones to avoid areas with unauthorized activities.
    category: logistics
    parameters:
    - name: drone_ids
      type: list
      description: The IDs of the drones that require new flight paths.
      required: true
    - name: new_routes
      type: list
      description: The new flight routes to be assigned to the drones.
      required: true
    example_usage:
    - reroute_drone_paths(drone_ids=['drone1', 'drone2'], new_routes=['routeA', 'routeB'])
  environment:
    name: drone_management_system
    description: A system environment for managing and securing drone delivery operations.
    variables:
    - name: DRONE_API_URL
      value: 'https://api.dronemanagement.com'
      description: URL for the drone management API
      type: string
    - name: MAX_DRONE_FLIGHT_TIME
      value: 120
      description: Maximum flight time for drones in minutes
      type: integer
    settings:
      flight_path_format: JSON
      max_drones_per_operation: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - dronemanagement.com
    - '*.secure-partner.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: admin@dronemanagement.com
    current_user_name: Drone Operations Manager
    company_name: DroneTech Inc.
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true