name: secure_vehicle_fleet_tracking
display_name: Secure Vehicle Fleet Tracking
description: This scenario involves managing and securing a fleet of vehicles through various operations such as deactivating routes, modifying parking availability, and updating vehicle statuses. It ensures efficient fleet management while maintaining security protocols for sensitive operations like fuel ordering and vehicle control capabilities.
category: fleet_management
complexity_level: 3
estimated_duration: 45
required_permissions:
- fleet_data_access
- vehicle_control_access
- admin_privileges
dependencies: []
generation_weight: 1.5
sample_actions:
- deactivate_routes
- modify_parking_availability
- list_parking_lots
- get_vehicle_control_capabilities
- update_fuel_order
metadata:
  selection_way: random
  selection_num: 4
tags:
- fleet_management
- vehicle_tracking
- security
context:
  available_tools:
  - name: deactivate_routes
    display_name: Deactivate Routes
    description: Deactivate specified transportation routes from the active list.
    category: route_management
    parameters:
    - name: routes
      type: list
      description: The routes to be deactivated.
      required: true
    example_usage:
    - deactivate_routes(routes=['Route A', 'Route B'])
  - name: modify_parking_availability
    display_name: Modify Parking Availability
    description: Modify the availability status of specified parking lots.
    category: parking_management
    parameters:
    - name: lots
      type: list
      description: The parking lots to be modified.
      required: true
    - name: status
      type: string
      description: The new availability status for the parking lots.
      required: true
    example_usage:
    - modify_parking_availability(lots=['Lot 1', 'Lot 2'], status='VIP')
  - name: update_fuel_order
    display_name: Update Fuel Order
    description: Update the fuel order for a specific vehicle. Restricted to ADMIN or ROOT users.
    category: fuel_management
    parameters:
    - name: vehicle_id
      type: string
      description: The ID of the vehicle.
      required: true
    - name: ordered_amount
      type: integer
      description: The amount of fuel to order.
      required: true
    example_usage:
    - update_fuel_order(vehicle_id='V123', ordered_amount=50)
    common_errors:
    - Unauthorized access
    - Invalid vehicle ID
  environment:
    name: fleet_management_system
    description: A secure environment for managing vehicle fleets with integrated tracking and control capabilities.
    variables:
    - name: FLEET_API_URL
      value: 'https://api.fleetmanagement.com'
      description: Base URL for the fleet management API
      type: string
    - name: MAX_FUEL_ORDER
      value: 1000
      description: Maximum fuel order limit per vehicle
      type: integer
    settings:
      vehicle_status_update_interval: 10
      max_parking_lots: 50
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - fleetmanagement.com
    - '*.trusted-partner.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_role: Fleet Manager
    company_name: FleetSecure Inc.
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true