name: security_manager
display_name: Security Manager
description: Monitors and manages the operational status of lifts within a facility. Provides tools to check the current status of lifts and disable them if necessary to ensure safety and compliance with operational protocols.
category: facility_management
complexity_level: 3
estimated_duration: 15
required_permissions:
- lift_status_access
- lift_control_access
dependencies: []
generation_weight: 1.0
sample_actions:
- check_lift_status
- disable_lift
metadata:
  selection_way: random
  selection_num: 2
tags:
- lift_management
- safety
- facility_operations
context:
  available_tools:
  - name: check_lift_status
    display_name: Check Lift Status
    description: Retrieve the current operational status of a lift
    category: facility_management
    parameters: []
    example_usage:
    - check_lift_status()
    common_errors:
    - Lift status unavailable
    - Network timeout
  - name: disable_lift
    display_name: Disable Lift
    description: Immediately disable a lift to prevent usage
    category: facility_management
    parameters: []
    example_usage:
    - disable_lift()
    common_errors:
    - Lift already disabled
    - Unauthorized access
  environment:
    name: building_management_system
    description: Integrated system for managing building facilities, including lifts
    variables:
    - name: LIFT_CONTROL_API_URL
      value: 'https://api.building-management.com/lift-control'
      description: API endpoint for lift control operations
      type: string
    - name: MAX_LIFTS
      value: 10
      description: Maximum number of lifts managed by the system
      type: integer
    settings:
      lift_status_check_interval: 5
      max_concurrent_lift_checks: 3
    max_memory_mb: 128
    max_execution_time: 120
    network_access: true
    allowed_domains:
    - building-management.com
    - '*.trusted-facility.com'
    blocked_domains:
    - '*.unauthorized-access.com'
  predefined_variables:
    current_user_email: admin@building-management.com
    current_user_name: Facility Manager
    company_name: Building Management Corp.
    timezone: UTC+1
    business_hours: 6:00-22:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - logging
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true