name: seismic_activity_predictor
display_name: Seismic Activity Predictor
description: Analyzes seismic data to predict upcoming seismic events, manage datasets, and update risk categories for various areas. Provides tools to list and manage datasets and prediction tools, ensuring up-to-date risk assessments and data management.
category: data_analysis
complexity_level: 3
estimated_duration: 30
required_permissions:
- seismic_data_access
- dataset_management_access
dependencies: []
generation_weight: 1.5
sample_actions:
- predict_seismic_activity
- list_areas
- update_risk_categories
- delete_dataset
metadata:
  selection_way: random
  selection_num: 4
tags:
- seismic
- data_analysis
- risk_management
context:
  available_tools:
  - name: predict_seismic_activity
    display_name: Predict Seismic Activity
    description: Predicts upcoming seismic events based on current data trends
    category: data_analysis
    parameters: []
    example_usage:
    - predict_seismic_activity()
  - name: list_areas
    display_name: List Areas
    description: List all areas with their current risk categories and seismic activities
    category: data_management
    parameters: []
    example_usage:
    - list_areas()
  - name: update_risk_categories
    display_name: Update Risk Categories
    description: Update the risk category for a specified area based on recent seismic activities
    category: risk_management
    parameters:
    - name: area_name
      type: string
      description: The name of the area for which to update the risk category
      required: true
    - name: new_risk_category
      type: string
      description: The new risk category to set for the area, such as Low, Moderate, or High
      required: true
    example_usage:
    - update_risk_categories(area_name='San Francisco', new_risk_category='High')
  - name: delete_dataset
    display_name: Delete Dataset
    description: Delete a specified dataset
    category: data_management
    parameters:
    - name: name
      type: string
      description: The name of the dataset to delete
      required: true
    example_usage:
    - delete_dataset(name='2023_seismic_data')
  environment:
    name: seismic_analysis_platform
    description: Platform for analyzing seismic data and managing risk categories
    variables:
    - name: SEISMIC_DATA_API_URL
      value: 'https://api.seismicdata.org'
      description: API endpoint for accessing seismic data
      type: string
    - name: MAX_DATASETS
      value: 100
      description: Maximum number of datasets that can be managed
      type: integer
    settings:
      prediction_model: 'advanced_seismic_v2'
      max_prediction_time: 120
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - seismicdata.org
    - '*.trusted-seismic-partner.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: analyst@seismicdata.org
    current_user_name: Seismic Data Analyst
    company_name: SeismicData Inc.
    timezone: UTC-8
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - numpy
    - pandas
    - sklearn
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true