name: singularity_controller
display_name: Singularity Controller
description: Manage and control traffic signals within a smart city infrastructure. This includes listing all traffic signals with their current status, removing specific traffic signals, and retrieving current alerts and warnings for the area. The system is designed to ensure efficient traffic management and safety.
category: infrastructure_management
complexity_level: 3
estimated_duration: 30
required_permissions:
- traffic_signal_control
- alert_management_access
dependencies: []
generation_weight: 1.5
sample_actions:
- list_traffic_signals
- remove_traffic_signals
- get_current_alerts
metadata:
  selection_way: random
  selection_num: 3
tags:
- traffic_management
- smart_city
- infrastructure
context:
  available_tools:
  - name: list_traffic_signals
    display_name: List Traffic Signals
    description: List all traffic signals and their current status
    category: infrastructure_management
    parameters: []
    example_usage:
    - list_traffic_signals()
  - name: remove_traffic_signals
    display_name: Remove Traffic Signals
    description: Remove the given traffic signal
    category: infrastructure_management
    parameters:
    - name: signal_id
      type: string
      description: The id of the traffic signal to be removed
      required: true
    example_usage:
    - remove_traffic_signals(signal_id='signal123')
  - name: get_current_alerts
    display_name: Get Current Alerts
    description: Get all current alerts and warnings issued for the area
    category: infrastructure_management
    parameters: []
    example_usage:
    - get_current_alerts()
  environment:
    name: smart_city_platform
    description: Smart city platform environment with traffic management tools
    variables:
    - name: ALERT_SYSTEM_URL
      value: 'https://alerts.smartcity.com'
      description: URL to the alert system
      type: string
    - name: MAX_SIGNAL_CONTROL
      value: 100
      description: Maximum number of signals that can be controlled simultaneously
      type: integer
    settings:
      alert_notification_format: JSON
      max_alerts_per_request: 50
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - smartcity.com
    - '*.trusted-partner.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: admin@smartcity.com
    current_user_name: City Infrastructure Manager
    company_name: SmartCity Inc.
    timezone: UTC+1
    business_hours: 24/7
  system_info:
    platform_version: '3.0'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true