name: smart_home_energy_optimization
display_name: Smart Home Energy Optimization
description: This scenario involves optimizing energy consumption in a smart home environment. It includes actions such as logging into the system, adjusting heating and cooling settings, scheduling device operations, and monitoring energy usage. The goal is to efficiently manage energy resources while maintaining comfort.
category: smart_home_management
complexity_level: 3
estimated_duration: 30
required_permissions:
- device_control_access
- energy_management_access
dependencies: []
generation_weight: 1.5
sample_actions:
- login
- remove_heating_systems
- set_temperature
- adjust_thermostat
- set_schedule
- check_status
- show_home_status
- control_appliance
metadata:
  selection_way: random
  selection_num: 4
tags:
- energy_optimization
- smart_home
- device_management
context:
  available_tools:
  - name: login
    display_name: Login
    description: Log into the smart home system to access and modify energy settings.
    category: authentication
    parameters: []
  - name: remove_heating_systems
    display_name: Remove Heating Systems
    description: Remove all the heating systems.
    category: device_management
    parameters: []
  - name: set_temperature
    display_name: Set Temperature
    description: Set the temperature of air conditioner.
    category: climate_control
    parameters:
    - name: target_temperature
      type: string
      description: The temperature which the air conditioner will maintain.
      required: true
  - name: adjust_thermostat
    display_name: Adjust Thermostat
    description: Adjusts the current thermostat setting to a specified temperature.
    category: climate_control
    parameters:
    - name: temperature
      type: integer
      description: The temperature to be set on the thermostat, in degrees Celsius.
      required: true
  - name: set_schedule
    display_name: Set Schedule
    description: Set the schedule for a specific device.
    category: scheduling
    parameters:
    - name: device_id
      type: string
      description: The unique identifier of the device.
      required: true
    - name: schedule
      type: object
      description: The schedule to set for the device.
      required: true
  - name: check_status
    display_name: Check Status
    description: Check the current status of the device settings.
    category: monitoring
    parameters:
    - name: device_id
      type: string
      description: The unique identifier of the device.
      required: true
  - name: show_home_status
    display_name: Show Home Status
    description: Display the current status of home appliances and energy consumption.
    category: monitoring
    parameters: []
  - name: control_appliance
    display_name: Control Appliance
    description: Control a specific appliance in the home.
    category: device_management
    parameters:
    - name: appliance
      type: string
      description: The appliance to control.
      required: true
    - name: action
      type: string
      description: The action to perform on the appliance (e.g., 'turn_on', 'turn_off').
      required: true
  environment:
    name: smart_home_system
    description: Smart home environment with energy management and device control capabilities.
    variables:
    - name: ENERGY_SAVING_MODE
      value: true
      description: Whether the energy-saving mode is enabled.
      type: boolean
    - name: DEFAULT_TEMPERATURE
      value: 22
      description: Default temperature setting for the home.
      type: integer
    settings:
      max_devices: 50
      schedule_format: 24-hour
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - smart-home.com
    - '*.trusted-device.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: user@smarthome.com
    current_user_name: Home Manager
    company_name: SmartHome Inc.
    timezone: UTC-7
    business_hours: 6:00-22:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true