name: smart_waste_management
display_name: Smart Waste Management
description: This scenario involves managing waste collection and analysis through various tools. It includes analyzing waste data, generating reports, adjusting collection schedules, and updating waste inventories. The tools provided help in optimizing waste management processes and ensuring efficient operations.
category: environmental_management
complexity_level: 3
estimated_duration: 45
required_permissions:
- data_analysis_access
- schedule_management_access
- inventory_update_access
dependencies: []
generation_weight: 1.5
sample_actions:
- analyze_waste_data
- generate_waste_report
- adjust_collection_schedule
- update_waste_inventory
metadata:
  selection_way: random
  selection_num: 5
tags:
- waste_management
- environmental_optimization
- data_analysis
context:
  available_tools:
  - name: waste_data_analysis
    display_name: Waste Data Analysis
    description: Provides statistical analysis of waste data, including trends and projections.
    category: data_analysis
    parameters:
    - name: category
      type: string
      description: Waste categories to analyze.
      required: true
    example_usage:
    - waste_data_analysis(category='plastic')
    common_errors:
    - Invalid category
  - name: report_generator
    display_name: Report Generator
    description: Compiles analyzed waste data into comprehensive reports.
    category: reporting
    parameters:
    - name: title
      type: string
      description: Title of the report.
      required: true
    - name: content
      type: string
      description: Main content of the report.
      required: true
    example_usage:
    - report_generator(title='Monthly Waste Report', content='Detailed analysis of waste trends.')
  - name: adjust_pickup_schedule
    display_name: Adjust Pickup Schedule
    description: Adjusts the pickup schedule for a location based on analysis.
    category: schedule_management
    parameters:
    - name: location
      type: string
      description: The location for which to adjust the pickup schedule.
      required: true
    - name: new_frequency
      type: string
      description: The new frequency for waste pickup.
      required: true
    example_usage:
    - adjust_pickup_schedule(location='Downtown', new_frequency='weekly')
  environment:
    name: waste_management_system
    description: A comprehensive system for managing waste collection and analysis.
    variables:
    - name: DATA_ANALYSIS_API
      value: 'https://api.wastemanagement.com/analyze'
      description: API endpoint for waste data analysis.
      type: string
    - name: MAX_REPORT_SIZE_MB
      value: 10
      description: Maximum size for generated reports in MB.
      type: integer
    settings:
      report_format: PDF
      max_zones_per_adjustment: 3
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - wastemanagement.com
    - '*.gov'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: admin@wastemanagement.com
    current_user_name: Waste Management Coordinator
    company_name: EcoWaste Solutions
    timezone: UTC+1
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - numpy
    - pandas
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true