name: smart_home_security_system
display_name: Smart Home Security System
description: Manages and secures smart home environments by interacting with sensors and firmware. Provides functionalities to search for sensors, update their settings, list available firmwares, and install new firmware versions. Ensures the system is up-to-date and operating efficiently.
category: home_automation
complexity_level: 3
estimated_duration: 30
required_permissions:
- sensor_management_access
- firmware_update_access
dependencies: []
generation_weight: 1.5
sample_actions:
- search_sensors
- update_sensor_settings
- list_firmwares
- install_firmware
metadata:
  selection_way: random
  selection_num: 4
tags:
- home_security
- sensors
- firmware_management
context:
  available_tools:
  - name: search_sensors
    display_name: Search Sensors
    description: Search for relevant sensors in the system
    category: sensor_management
    parameters: []
    example_usage:
    - search_sensors()
  - name: update_sensor_settings
    display_name: Update Sensor Settings
    description: Update the alert settings of a sensor
    category: sensor_management
    parameters:
    - name: sensor_id
      type: string
      description: The id of the sensor
      required: true
    - name: alert_setting
      type: string
      description: The new alert setting for the sensor
      required: true
    example_usage:
    - update_sensor_settings(sensor_id='sensor123', alert_setting='high')
  - name: list_firmwares
    display_name: List Firmwares
    description: List all available firmwares and the current firmware version
    category: firmware_management
    parameters: []
    example_usage:
    - list_firmwares()
  - name: install_firmware
    display_name: Install Firmware
    description: Installs a specified firmware version to the Smart Home Security System
    category: firmware_management
    parameters:
    - name: firmware_id
      type: string
      description: The ID of the firmware to install
      required: true
    example_usage:
    - install_firmware(firmware_id='fw_v2.0')
  environment:
    name: smart_home_environment
    description: Smart home environment with sensor and firmware management capabilities
    variables:
    - name: FIRMWARE_UPDATE_URL
      value: 'https://www.smarthome.com/firmware-updates'
      description: URL to the firmware update page
      type: string
    - name: MAX_SENSORS
      value: 50
      description: Maximum number of sensors supported
      type: integer
    settings:
      alert_notification_method: email
      firmware_update_schedule: weekly
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - smarthome.com
    - '*.trusted-supplier.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: admin@smarthome.com
    current_user_name: Smart Home Admin
    company_name: SmartHome Inc.
    timezone: UTC-6
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true