name: sms
display_name: SMS Sender
description: Facilitates the sending of short messages (SMS) to one or more recipients. This tool is essential for communication tasks, allowing users to specify the sender, receiver(s), and the message content. Ensures efficient and reliable message delivery.
category: communication
complexity_level: 1
estimated_duration: 5
required_permissions:
- sms_sending_access
dependencies: []
generation_weight: 1.0
sample_actions:
- send_sms
metadata:
  selection_way: random
  selection_num: 1
tags:
- messaging
- communication
- sms
context:
  available_tools:
  - name: send_sms
    display_name: Send SMS
    description: Send a short message to specified recipients
    category: communication
    parameters:
    - name: sender
      type: string
      description: The short message's sender
      required: false
    - name: receiver
      type: list
      description: The short message's receiver(s)
      required: true
    - name: content
      type: string
      description: The short message's content
      required: true
    example_usage:
    - send_sms(sender='John Doe', receiver=['+1234567890'], content='Hello, this is a test message.')
    common_errors:
    - Invalid phone number format
    - Message content exceeds character limit
  environment:
    name: sms_gateway
    description: Environment configured with SMS gateway access for sending messages
    variables:
    - name: SMS_GATEWAY_URL
      value: 'https://api.smsprovider.com/send'
      description: URL to the SMS gateway API
      type: string
    - name: MAX_SMS_LENGTH
      value: 160
      description: Maximum number of characters allowed per SMS
      type: integer
    settings:
      sms_format: text
      max_recipients_per_message: 10
    max_memory_mb: 128
    max_execution_time: 60
    network_access: true
    allowed_domains:
    - smsprovider.com
    - '*.trusted-sms.com'
    blocked_domains:
    - '*.spam-sms.com'
  predefined_variables:
    current_user_phone: '+19876543210'
    current_user_name: SMS Operator
    company_name: MessagingCorp Inc.
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '1.0'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true