name: sound_wave_therapy
display_name: Sound Wave Therapy Analysis
description: Evaluates the effectiveness and safety of sound wave therapy devices. The scenario involves analyzing device specifications, adjusting therapy settings, and managing device-related files. It aims to ensure accurate information dissemination regarding the therapeutic benefits and risks of sound wave therapy devices.
category: healthcare
complexity_level: 3
estimated_duration: 30
required_permissions:
- device_data_access
- settings_adjustment_access
dependencies: []
generation_weight: 1.5
sample_actions:
- analyze_device
- get_current_settings
- adjust_settings
- read_file
- list_files
metadata:
  selection_way: random
  selection_num: 3
tags:
- healthcare
- therapy
- device_analysis
context:
  available_tools:
  - name: analyze_device
    display_name: Analyze Device
    description: Evaluate the effectiveness and safety of sound wave therapy devices
    category: healthcare
    parameters:
    - name: device_name
      type: string
      description: The name of the sound wave therapy device to be analyzed
      required: true
    example_usage:
    - analyze_device(device_name='TheraWave 3000')
  - name: get_current_settings
    display_name: Get Current Settings
    description: Obtain the current sound therapy settings
    category: device_management
    parameters: []
    example_usage:
    - get_current_settings()
  - name: adjust_settings
    display_name: Adjust Settings
    description: Adjust the sound therapy settings
    category: device_management
    parameters:
    - name: volume_level
      type: integer
      description: The volume level for sound therapy. Values range from 0 (mute) to 10 (max)
      required: true
    - name: frequency_range
      type: string
      description: The frequency range for the therapy, e.g., '30Hz-15kHz'
      required: true
    - name: timer_duration
      type: integer
      description: The duration (in minutes) for the sound therapy session
      required: true
    example_usage:
    - adjust_settings(volume_level=5, frequency_range='30Hz-15kHz', timer_duration=30)
  - name: read_file
    display_name: Read File
    description: Read the content from a specified file
    category: file_management
    parameters:
    - name: filename
      type: string
      description: The name of the file to read
      required: true
    example_usage:
    - read_file(filename='therapy_notes.txt')
  - name: list_files
    display_name: List Files
    description: List all files available in the environment
    category: file_management
    parameters: []
    example_usage:
    - list_files()
  environment:
    name: therapy_device_environment
    description: Environment for managing and analyzing sound wave therapy devices
    variables:
    - name: DEVICE_MANUAL_URL
      value: 'https://www.example.com/device-manual'
      description: URL to the device manual
      type: string
    - name: MAX_VOLUME_LEVEL
      value: 10
      description: Maximum volume level for devices
      type: integer
    settings:
      file_format: TXT
      max_files_per_session: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - example.com
    - '*.trusted-device.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: therapist@example.com
    current_user_name: Sound Therapy Specialist
    company_name: HealthTech Innovations
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - numpy
    - scipy
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true