name: space_debris_recycler
display_name: Space Debris Recycler
description: This scenario involves managing and optimizing space debris recycling operations. The agent is tasked with reviewing system parameters, analyzing astronomical data, retrieving recycling plans, pausing non-essential systems, adjusting spacecraft orbits, and sending alerts to ground control. The goal is to ensure efficient recycling processes while maintaining safety and compliance with regulations.
category: space_operations
complexity_level: 3
estimated_duration: 45
required_permissions:
- data_analysis_access
- system_control_access
- alert_sending_access
dependencies: []
generation_weight: 1.5
sample_actions:
- review_systems
- analyze_astronomical_data
- get_plan
- pause_system
- adjust_orbit
- send_alert
metadata:
  selection_way: random
  selection_num: 4
tags:
- space
- debris_management
- recycling
- safety
context:
  available_tools:
  - name: review_systems
    display_name: Review Systems
    description: Review the parameters of existing systems to ensure they are functioning optimally.
    category: system_management
    parameters: []
    example_usage:
    - review_systems()
  - name: analyze_astronomical_data
    display_name: Analyze Astronomical Data
    description: Process astronomical data for insights and predictions, ensuring data accuracy.
    category: data_analysis
    parameters:
    - name: data_source_name
      type: string
      description: The name of the data source file used for analysis.
      required: true
    example_usage:
    - analyze_astronomical_data(data_source_name='telescope_data_2023.csv')
  - name: get_plan
    display_name: Get Recycling Plan
    description: Retrieve the content of recycling plans with the necessary licenses.
    category: plan_management
    parameters: []
    example_usage:
    - get_plan()
  - name: pause_system
    display_name: Pause System
    description: Pause systems identified as non-essential to optimize performance.
    category: system_management
    parameters:
    - name: system_id
      type: string
      description: Identifier of the system to pause.
      required: true
    example_usage:
    - pause_system(system_id='sys_001')
  - name: adjust_orbit
    display_name: Adjust Orbit
    description: Automatically adjust the spacecraft's orbit to avoid collisions.
    category: navigation
    parameters: []
    example_usage:
    - adjust_orbit()
  - name: send_alert
    display_name: Send Alert
    description: Send an alert to ground control regarding mission-critical events.
    category: communication
    parameters: []
    example_usage:
    - send_alert()
  environment:
    name: space_operations_environment
    description: Environment for managing space debris recycling with necessary tools and systems.
    variables:
    - name: MISSION_CONTROL_CONTACT
      value: 'mission.control@spaceagency.org'
      description: Contact email for mission control.
      type: string
    - name: MAX_ORBIT_ADJUSTMENTS
      value: 5
      description: Maximum number of orbit adjustments allowed per day.
      type: integer
    settings:
      alert_format: JSON
      max_systems_paused: 3
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - spaceagency.org
    - '*.trusted-space-partner.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: operator@spaceagency.org
    current_user_name: Space Operations Specialist
    agency_name: Space Agency
    timezone: UTC+0
    mission_hours: 24/7
  system_info:
    platform_version: '3.0'
    available_libraries:
    - numpy
    - pandas
    - scipy
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true