name: stock_manager
display_name: Stock Manager
description: Manages stock trading activities including retrieving account holdings, checking balances, placing stock orders, and obtaining stock information. Designed for users managing self-directed TFSA and non-registered accounts, ensuring efficient and secure trading operations.
category: finance_management
complexity_level: 3
estimated_duration: 30
required_permissions:
- account_data_access
- trading_execution_access
dependencies: []
generation_weight: 1.5
sample_actions:
- get_holdings_information
- get_balance
- trade_stock
- get_stock_information
metadata:
  selection_way: random
  selection_num: 4
tags:
- trading
- finance
- stock_management
context:
  available_tools:
  - name: get_holdings_information
    display_name: Get Holdings Information
    description: Retrieve information about the holdings in an account
    category: finance_management
    parameters:
    - name: account
      type: string
      description: The account type, one of ['self-directed TFSA', 'self-directed non-registered']
      required: true
    example_usage:
    - get_holdings_information(account='self-directed TFSA')
  - name: get_balance
    display_name: Get Balance
    description: Retrieve the balance of an account
    category: finance_management
    parameters:
    - name: account
      type: string
      description: The account type, one of ['self-directed TFSA', 'self-directed non-registered']
      required: true
    example_usage:
    - get_balance(account='self-directed non-registered')
  - name: trade_stock
    display_name: Trade Stock
    description: Places an order for a stock
    category: trading
    parameters:
    - name: account
      type: string
      description: The account number in which to purchase a stock
      required: true
    - name: action
      type: string
      description: Whether to buy or sell the stock
      required: true
    - name: order_type
      type: string
      description: Type of order, either 'limit_order' or 'market_order'
      required: true
    - name: ticker
      type: string
      description: The ticker of the stock
      required: true
    - name: quantity
      type: number
      description: The number of shares to buy or sell
      required: true
    - name: price_limit
      type: number
      description: The maximum or minimum price for limit orders
      required: false
    example_usage:
    - trade_stock(account='self-directed TFSA', action='buy', order_type='limit_order', ticker='AAPL', quantity=10, price_limit=150)
  - name: get_stock_information
    display_name: Get Stock Information
    description: Gets information about a stock
    category: finance_management
    parameters:
    - name: ticker
      type: string
      description: The ticker of the stock
      required: true
    example_usage:
    - get_stock_information(ticker='GOOGL')
  environment:
    name: trading_platform
    description: Secure trading platform environment for managing stock transactions
    variables:
    - name: TRADING_API_URL
      value: 'https://api.tradingplatform.com'
      description: URL for the trading platform API
      type: string
    - name: MAX_TRADE_AMOUNT
      value: 100000
      description: Maximum trade amount allowed per transaction
      type: integer
    settings:
      order_execution_time: 120
      max_concurrent_trades: 5
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - tradingplatform.com
    - '*.financial-data.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: trader@example.com
    current_user_name: Stock Trader
    company_name: FinanceCorp Inc.
    timezone: UTC-4
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true