name: supply_chain_optimization
display_name: Supply Chain Optimization
description: Facilitates the optimization of supply chain operations by enabling search for products, listing locations, adjusting shipment quantities, and monitoring stock levels. This scenario is designed to improve efficiency and accuracy in supply chain management.
category: logistics
complexity_level: 3
estimated_duration: 30
required_permissions:
- inventory_management_access
- location_data_access
dependencies: []
generation_weight: 1.5
sample_actions:
- search_items
- list_locations
- adjust_shipment
- list_stock_levels
metadata:
  selection_way: random
  selection_num: 4
tags:
- supply_chain
- logistics
- inventory_management
context:
  available_tools:
  - name: search_items
    display_name: Search Items
    description: Search for relevant products in the supply chain
    category: logistics
    parameters:
    - name: query
      type: string
      description: The search criteria for the product
      required: true
    example_usage:
    - search_items(query='laptop')
  - name: list_locations
    display_name: List Locations
    description: List the locations in the supply chain
    category: logistics
    parameters: []
    example_usage:
    - list_locations()
  - name: adjust_shipment
    display_name: Adjust Shipment
    description: Adjust the shipment quantity for a specific product in a specific location
    category: logistics
    parameters:
    - name: product_id
      type: string
      description: The ID of the product
      required: true
    - name: location_id
      type: string
      description: The ID of the location to adjust shipment quantities for
      required: true
    - name: quantity
      type: number
      description: The quantity to be set for shipment
      required: true
    example_usage:
    - adjust_shipment(product_id='123', location_id='456', quantity=100)
  - name: list_stock_levels
    display_name: List Stock Levels
    description: List the current stock level of items in the warehouses
    category: logistics
    parameters: []
    example_usage:
    - list_stock_levels()
  environment:
    name: supply_chain_management_system
    description: Environment for managing supply chain operations with tools for inventory and logistics
    variables:
    - name: SUPPLY_CHAIN_API_URL
      value: 'https://api.supplychain.example.com'
      description: Base URL for the supply chain API
      type: string
    - name: MAX_SHIPMENT_QUANTITY
      value: 1000
      description: Maximum quantity allowed per shipment adjustment
      type: integer
    settings:
      shipment_adjustment_format: JSON
      max_locations_per_query: 50
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - supplychain.example.com
    - '*.trusted-supplier.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: logistics_manager@example.com
    current_user_name: Logistics Manager
    company_name: GlobalSupply Inc.
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - pandas
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true