name: telecom_fraud_prevention
display_name: Telecom Fraud Prevention
description: This scenario focuses on preventing fraudulent activities within the telecommunications sector. It involves searching for resources, accessing industry reports, viewing system information, and blocking suspicious phone numbers to safeguard company operations.
category: telecommunications_security
complexity_level: 3
estimated_duration: 30
required_permissions:
- telecom_data_access
- system_log_access
dependencies: []
generation_weight: 1.5
sample_actions:
- search_resources
- get_industry_report
- view_system_info
- block_number
metadata:
  selection_way: random
  selection_num: 4
tags:
- telecommunications
- fraud_prevention
- security
context:
  available_tools:
  - name: search_resources
    display_name: Search Resources
    description: Search for resources related to telecommunications topics.
    category: information_retrieval
    parameters: []
    example_usage:
    - search_resources()
  - name: get_industry_report
    display_name: Get Industry Report
    description: Retrieve detailed reports on telecommunications industry topics.
    category: data_analysis
    parameters:
    - name: report_id
      type: integer
      description: The ID of the report to retrieve.
      required: true
    example_usage:
    - get_industry_report(report_id=101)
    common_errors:
    - Report ID not found
    - Outdated report data
  - name: view_system_info
    display_name: View System Information
    description: View the system information and recent activity logs.
    category: system_monitoring
    parameters: []
    example_usage:
    - view_system_info()
  - name: block_number
    display_name: Block Number
    description: Block a phone number from reaching the company line.
    category: telecommunications_security
    parameters:
    - name: phone_number
      type: string
      description: The phone number to block.
      required: true
    example_usage:
    - block_number(phone_number='+1234567890')
  environment:
    name: telecom_security_platform
    description: A platform designed to enhance security measures in telecommunications operations.
    variables:
    - name: FRAUD_ALERT_THRESHOLD
      value: 5
      description: Number of suspicious activities before triggering an alert.
      type: integer
    - name: REPORT_UPDATE_FREQUENCY
      value: 'monthly'
      description: Frequency of updating industry reports.
      type: string
    settings:
      log_retention_days: 90
      max_blocked_numbers: 1000
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - telecom-company.com
    - '*.trusted-partner.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: security@telecom-company.com
    current_user_name: Telecom Security Officer
    company_name: TelecomCorp Inc.
    timezone: UTC+0
    business_hours: 24/7
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - pandas
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true