name: telecom_network
display_name: Telecom Network Monitoring
description: This scenario involves managing and adjusting monitoring rules within a telecom network to detect and prevent fraudulent activities. The agent retrieves current monitoring rules and modifies them to ensure optimal sensitivity levels, enhancing the network's security and integrity.
category: network_security
complexity_level: 3
estimated_duration: 30
required_permissions:
- network_monitoring_access
- rule_management_access
dependencies: []
generation_weight: 1.5
sample_actions:
- get_monitoring_rules
- adjust_monitoring_rules
metadata:
  selection_way: random
  selection_num: 2
tags:
- telecom
- network_security
- fraud_prevention
context:
  available_tools:
  - name: get_monitoring_rules
    display_name: Get Monitoring Rules
    description: Retrieve the current monitoring rules and their sensitivity levels
    category: network_security
    parameters: []
    example_usage:
    - get_monitoring_rules()
  - name: adjust_monitoring_rules
    display_name: Adjust Monitoring Rules
    description: Modify rules for monitoring call activities to intercept fraudulent actions
    category: network_security
    parameters:
    - name: rule_id
      type: string
      description: The ID of the rule to be adjusted
      required: true
    - name: sensitivity_level
      type: string
      description: The sensitivity level to be set for the rule (e.g., low, medium, high)
      required: true
    example_usage:
    - adjust_monitoring_rules(rule_id='rule123', sensitivity_level='high')
  environment:
    name: telecom_network_environment
    description: A telecom network environment equipped with monitoring and rule management tools
    variables:
    - name: MONITORING_API_URL
      value: 'https://api.telecomnetwork.com/monitoring'
      description: API endpoint for accessing monitoring rules
      type: string
    - name: DEFAULT_SENSITIVITY
      value: medium
      description: Default sensitivity level for monitoring rules
      type: string
    settings:
      max_rules_per_adjustment: 10
      default_rule_sensitivity: medium
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - telecomnetwork.com
    - '*.trusted-partner.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: admin@telecomnetwork.com
    current_user_name: Network Security Admin
    company_name: Telecom Network Inc.
    timezone: UTC
    business_hours: 24/7
  system_info:
    platform_version: '3.0'
    available_libraries:
    - requests
    - yaml
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true