name: terrain_morphing_system
display_name: Terrain Morphing System
description: A system designed to manage and adjust terrain features for construction and environmental planning. It allows users to list and confirm morphing tasks, retrieve and adjust landforms, and modify terrain heights to meet specific design requirements.
category: environmental_management
complexity_level: 3
estimated_duration: 45
required_permissions:
- terrain_data_access
- morphing_task_management
dependencies: []
generation_weight: 1.5
sample_actions:
- list_morphing_tasks
- confirm_task
- retrieve_landform
- adjust_landform
- get_terrain_data
- modify_terrain_height
- list_construction_plans
metadata:
  selection_way: random
  selection_num: 5
tags:
- terrain
- construction
- environmental_management
context:
  available_tools:
  - name: list_morphing_tasks
    display_name: List Morphing Tasks
    description: List all terrain morphing tasks and their current status
    category: task_management
    parameters: []
    example_usage:
    - list_morphing_tasks()
  - name: confirm_task
    display_name: Confirm Task
    description: Confirm a morphing task by its ID
    category: task_management
    parameters:
    - name: task_id
      type: string
      description: The unique ID of the task to confirm
      required: true
    example_usage:
    - confirm_task(task_id='task123')
    common_errors:
    - Invalid task ID
    - Task confirmation failure
  - name: retrieve_landform
    display_name: Retrieve Landform
    description: Retrieve existing landforms in the system
    category: data_retrieval
    parameters: []
    example_usage:
    - retrieve_landform()
  - name: adjust_landform
    display_name: Adjust Landform
    description: Adjust the physical characteristics of a landform
    category: modification
    parameters:
    - name: landform_id
      type: string
      description: The ID of the landform
      required: true
    - name: adjustment
      type: number
      description: The amount by which to adjust the landform's height or depth
      required: true
    - name: feature
      type: string
      description: The feature to adjust, e.g., height or depth
      required: true
    example_usage:
    - adjust_landform(landform_id='landform456', adjustment=5.0, feature='height')
  - name: get_terrain_data
    display_name: Get Terrain Data
    description: Retrieve the current height and description of terrain segments
    category: data_retrieval
    parameters: []
    example_usage:
    - get_terrain_data()
  - name: modify_terrain_height
    display_name: Modify Terrain Height
    description: Adjust the height of terrain segments to meet design specifications
    category: modification
    parameters:
    - name: segment_id
      type: string
      description: The ID of the segment to be adjusted
      required: true
    - name: new_height
      type: number
      description: The new height to set for the segment
      required: true
    example_usage:
    - modify_terrain_height(segment_id='segment789', new_height=10.0)
  environment:
    name: terrain_management_platform
    description: Platform environment for managing and adjusting terrain features
    variables:
    - name: TERRAIN_DATA_API_URL
      value: 'https://api.terrainmanagement.com/data'
      description: API endpoint for terrain data access
      type: string
    - name: MAX_ADJUSTMENT_LIMIT
      value: 20
      description: Maximum allowable adjustment in meters
      type: integer
    settings:
      data_format: JSON
      max_tasks_per_session: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - terrainmanagement.com
    - '*.trusted-partner.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: admin@terrainmanagement.com
    current_user_name: Terrain Manager
    company_name: GeoConstruct Inc.
    timezone: UTC+0
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - numpy
    - pandas
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true