name: thermal_cloaking_device
display_name: Thermal Cloaking Device Management
description: This scenario involves managing a thermal cloaking device, including retrieving and adjusting temperature, insulation, and cloaking settings. The scenario ensures optimal performance and energy efficiency of the device while maintaining security protocols.
category: device_management
complexity_level: 3
estimated_duration: 30
required_permissions:
- device_control_access
- temperature_data_access
dependencies: []
generation_weight: 1.5
sample_actions:
- get_temperature_setting
- schedule_temperature_change
- adjust_insulation_settings
- deactivate_device
metadata:
  selection_way: random
  selection_num: 4
tags:
- thermal_management
- energy_efficiency
- device_control
context:
  available_tools:
  - name: get_temperature_setting
    display_name: Get Temperature Setting
    description: Retrieve the current temperature setting.
    category: temperature_management
    parameters: []
    example_usage:
    - get_temperature_setting()
  - name: schedule_temperature_change
    display_name: Schedule Temperature Change
    description: Schedule a change in temperature at a specific future time.
    category: temperature_management
    parameters:
    - name: date
      type: string
      description: The date for the scheduled change in format YYYY-MM-DD.
      required: true
    - name: time
      type: string
      description: The time for the scheduled change in format HH:MM.
      required: true
    - name: temperature
      type: string
      description: The temperature to be set at the scheduled time (e.g., '22°C').
      required: true
    example_usage:
    - schedule_temperature_change(date='2023-10-01', time='14:00', temperature='22°C')
    common_errors:
    - Invalid date format
    - Time conflict with existing schedule
  - name: adjust_insulation_settings
    display_name: Adjust Insulation Settings
    description: Modify insulation settings to improve device efficiency.
    category: energy_management
    parameters:
    - name: device_id
      type: string
      description: The ID of the device to be adjusted.
      required: true
    - name: energy_saving_mode
      type: string
      description: The energy-saving mode to set for the device (e.g., low, medium, high).
      required: true
    example_usage:
    - adjust_insulation_settings(device_id='device123', energy_saving_mode='high')
  - name: deactivate_device
    display_name: Deactivate Device
    description: Deactivate a specified thermal cloaking device.
    category: device_control
    parameters:
    - name: device_id
      type: string
      description: The ID of the device
      required: true
    example_usage:
    - deactivate_device(device_id='device123')
  environment:
    name: thermal_management_system
    description: Environment for managing thermal cloaking devices with temperature and insulation controls.
    variables:
    - name: MAX_TEMPERATURE
      value: 30
      description: Maximum allowable temperature setting in Celsius.
      type: integer
    - name: MIN_TEMPERATURE
      value: 15
      description: Minimum allowable temperature setting in Celsius.
      type: integer
    settings:
      temperature_unit: Celsius
      max_scheduled_changes: 5
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - thermaldevices.com
    - '*.trusted-partner.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: admin@thermaldevices.com
    current_user_name: Thermal Device Manager
    company_name: ThermalTech Inc.
    timezone: UTC+0
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true