name: time_manipulation
display_name: Time Manipulation
description: This scenario involves managing and adjusting time-related tasks, such as scheduling meetings, adjusting timelines, and modifying timestamps. It is designed to test the AI's ability to handle time zone conversions, daylight saving adjustments, and ensure compliance with scheduling constraints.
category: scheduling
complexity_level: 3
estimated_duration: 30
required_permissions:
- schedule_management_access
- file_management_access
dependencies: []
generation_weight: 1.5
sample_actions:
- get_attendee_list
- adjust_time_for_attendee
- adjust_time_schedule
- get_time_schedule
- list_files
- modify_timestamp
- cancel_appointment
- list_appointments
- adjust_timelines
- get_timelines
- review_timeline_constraints
metadata:
  selection_way: random
  selection_num: 5
tags:
- scheduling
- time_management
- compliance
context:
  available_tools:
  - name: adjust_time_for_attendee
    display_name: Adjust Time for Attendee
    description: Adjust the attendee's scheduled time according to the provided time zone and daylight saving rules.
    category: scheduling
    parameters:
    - name: attendee_name
      type: string
      description: The name of the attendee whose time needs to be adjusted.
      required: true
    - name: new_time_zone
      type: string
      description: The new time zone or daylight saving adjustment for the attendee.
      required: true
    example_usage:
    - adjust_time_for_attendee(attendee_name='John Doe', new_time_zone='PST')
  - name: modify_timestamp
    display_name: Modify Timestamp
    description: Change the timestamp of a specific file.
    category: file_management
    parameters:
    - name: filename
      type: string
      description: The name of the file to change the timestamp.
      required: true
    - name: new_timestamp
      type: string
      description: The new timestamp to set for the file.
      required: true
    example_usage:
    - modify_timestamp(filename='report.docx', new_timestamp='2023-10-01T12:00:00')
  environment:
    name: time_management_system
    description: A system environment equipped with tools for managing schedules, timelines, and file timestamps.
    variables:
    - name: DEFAULT_TIME_ZONE
      value: 'UTC'
      description: Default time zone for scheduling tasks.
      type: string
    - name: DST_RULES_URL
      value: 'https://www.example.com/dst-rules'
      description: URL to the daylight saving time rules.
      type: string
    settings:
      max_schedule_adjustments: 10
      timestamp_format: 'YYYY-MM-DDTHH:MM:SS'
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - example.com
    - '*.trusted-scheduler.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: scheduler@example.com
    current_user_name: Time Management Specialist
    company_name: TimeCorp Inc.
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.0'
    available_libraries:
    - pytz
    - datetime
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true