name: traffic_incident_response
display_name: Traffic Incident Response
description: This scenario involves managing and responding to traffic incidents by adjusting signal timings, diverting traffic, and retrieving traffic status. The goal is to optimize traffic flow and minimize congestion at intersections.
category: traffic_management
complexity_level: 3
estimated_duration: 30
required_permissions:
- traffic_data_access
- signal_control_access
dependencies: []
generation_weight: 1.5
sample_actions:
- adjust_traffic_signal_timing
- divert_traffic
- get_traffic_status
metadata:
  selection_way: random
  selection_num: 3
tags:
- traffic
- incident_management
- urban_planning
context:
  available_tools:
  - name: adjust_traffic_signal_timing
    display_name: Adjust Traffic Signal Timing
    description: Modify the signal timing at a specified intersection to improve traffic flow.
    category: traffic_management
    parameters:
    - name: intersection_name
      type: string
      description: The name of the intersection.
      required: true
    - name: new_timing
      type: integer
      description: New signal timing in seconds.
      required: true
    example_usage:
    - adjust_traffic_signal_timing(intersection_name='5th and Main', new_timing=45)
  - name: divert_traffic
    display_name: Divert Traffic
    description: Divert traffic from a specified intersection to an alternate route.
    category: traffic_management
    parameters:
    - name: intersection_name
      type: string
      description: The name of the intersection.
      required: true
    - name: alternate_route
      type: string
      description: Description of the alternate route.
      required: true
    example_usage:
    - divert_traffic(intersection_name='5th and Main', alternate_route='via 7th Ave')
  - name: get_traffic_status
    display_name: Get Traffic Status
    description: Retrieve the current traffic status for all intersections.
    category: traffic_management
    parameters: []
    example_usage:
    - get_traffic_status()
  environment:
    name: urban_traffic_control_center
    description: Environment simulating a city's traffic control center with access to traffic signal systems and data.
    variables:
    - name: TRAFFIC_API_URL
      value: 'https://api.trafficcontrol.example.com'
      description: URL to the traffic control API
      type: string
    - name: MAX_SIGNAL_ADJUSTMENT
      value: 120
      description: Maximum allowable signal timing adjustment in seconds
      type: integer
    settings:
      signal_adjustment_format: JSON
      max_diversion_routes: 3
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - example.com
    - '*.traffic-partner.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_operator_email: operator@trafficcontrol.example.com
    current_operator_name: Traffic Control Operator
    city_name: Metropolis
    timezone: UTC-5
    business_hours: 24/7
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true