name: traffic_control_system
display_name: Traffic Control System
description: Manages and optimizes traffic flow through the control of traffic lights and intersections. Provides tools for listing traffic lights and intersections, setting light schedules, adjusting signal timings, and modifying traffic flow based on current data. Aims to improve traffic efficiency and reduce congestion.
category: traffic_management
complexity_level: 3
estimated_duration: 30
required_permissions:
- traffic_data_access
- signal_control_access
dependencies: []
generation_weight: 1.5
sample_actions:
- list_traffic_lights
- set_light_schedule
- adjust_signal_timings
- list_intersections
- get_traffic_data
- modify_traffic_flow
metadata:
  selection_way: random
  selection_num: 3
tags:
- traffic
- urban_planning
- infrastructure
context:
  available_tools:
  - name: list_traffic_lights
    display_name: List Traffic Lights
    description: Retrieve a list of all traffic lights and their current schedules
    category: traffic_management
    parameters: []
    example_usage:
    - list_traffic_lights()
  - name: set_light_schedule
    display_name: Set Light Schedule
    description: Update the schedule for a specific traffic light
    category: traffic_management
    parameters:
    - name: light_id
      type: string
      description: The identifier of the traffic light
      required: true
    - name: schedule
      type: string
      description: The new schedule for the traffic light
      required: true
    example_usage:
    - set_light_schedule(light_id='TL123', schedule='08:00-18:00 [GREEN, 60; RED, 30; YELLOW, 10]')
  - name: adjust_signal_timings
    display_name: Adjust Signal Timings
    description: Modify the signal timings for a specific intersection
    category: traffic_management
    parameters:
    - name: intersection_id
      type: string
      description: The ID of the intersection
      required: true
    - name: green
      type: string
      description: Duration of green light in seconds
      required: true
    - name: yellow
      type: string
      description: Duration of yellow light in seconds
      required: true
    - name: red
      type: string
      description: Duration of red light in seconds
      required: true
    example_usage:
    - adjust_signal_timings(intersection_id='INT456', green='60', yellow='10', red='30')
  - name: modify_traffic_flow
    display_name: Modify Traffic Flow
    description: Change the traffic flow status for a specific street
    category: traffic_management
    parameters:
    - name: street_name
      type: string
      description: The name of the street
      required: true
    - name: new_status
      type: string
      description: The new traffic status
      required: true
    example_usage:
    - modify_traffic_flow(street_name='Main St', new_status='clear')
  environment:
    name: urban_traffic_network
    description: Simulated urban environment with traffic control capabilities
    variables:
    - name: TRAFFIC_API_URL
      value: 'https://api.trafficcontrol.com'
      description: API endpoint for traffic data
      type: string
    - name: MAX_SIGNAL_DURATION
      value: 120
      description: Maximum duration for traffic signals in seconds
      type: integer
    settings:
      default_signal_pattern: 'GREEN, 60; RED, 30; YELLOW, 10'
      max_intersections: 50
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - trafficcontrol.com
    - '*.city.gov'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_operator_email: operator@trafficcontrol.com
    current_operator_name: Traffic Control Operator
    city_name: Metropolis
    timezone: UTC-6
    business_hours: 6:00-22:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - pandas
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true