name: underwater_exploration
display_name: Underwater Exploration
description: This scenario involves obtaining suggestions for underwater exploration activities. It aims to assist researchers and enthusiasts in planning their underwater expeditions by providing insights and recommendations based on various parameters such as location, depth, and environmental conditions.
category: exploration
complexity_level: 3
estimated_duration: 45
required_permissions:
- ocean_data_access
- environmental_conditions_access
dependencies: []
generation_weight: 1.5
sample_actions:
- get_suggestions
metadata:
  selection_way: random
  selection_num: 5
tags:
- exploration
- marine
- research
context:
  available_tools:
  - name: get_suggestions
    display_name: Get Suggestions
    description: Retrieve suggestions for underwater exploration based on current conditions and user preferences.
    category: exploration
    parameters: []
    example_usage:
    - get_suggestions()
    common_errors:
    - No suggestions available
    - Invalid parameters
  environment:
    name: marine_research_platform
    description: A platform designed for marine research and exploration, equipped with tools for data analysis and environmental monitoring.
    variables:
    - name: OCEAN_DATA_API_URL
      value: 'https://api.oceanexploration.com/data'
      description: API endpoint for accessing oceanographic data
      type: string
    - name: MAX_DEPTH_METERS
      value: 1000
      description: Maximum depth for exploration in meters
      type: integer
    settings:
      data_format: JSON
      max_suggestions: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - oceanexploration.com
    - '*.marine-research.org'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: explorer@oceanexploration.com
    current_user_name: Marine Explorer
    organization_name: Ocean Exploration Institute
    timezone: UTC+0
    operational_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - numpy
    - pandas
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true