name: unmanned_vehicle_coordination
display_name: Unmanned Vehicle Coordination
description: This scenario involves coordinating unmanned vehicles, including UAVs, for efficient delivery route planning and real-time vehicle tracking. It ensures optimal route management, vehicle location updates, and weather monitoring to facilitate seamless operations in logistics and delivery services.
category: logistics
complexity_level: 3
estimated_duration: 30
required_permissions:
- vehicle_tracking_access
- route_management_access
dependencies: []
generation_weight: 1.5
sample_actions:
- list_routes
- locate_vehicles
- add_new_route
- schedule_delivery
- monitor_weather
- list_uavs
metadata:
  selection_way: random
  selection_num: 4
tags:
- logistics
- delivery
- UAV
- vehicle_tracking
context:
  available_tools:
  - name: list_routes
    display_name: List Routes
    description: List all available delivery routes.
    category: logistics
    parameters: []
    example_usage:
    - list_routes()
  - name: locate_vehicles
    display_name: Locate Vehicles
    description: Locate vehicles to get their current position in real-time.
    category: logistics
    parameters: []
    example_usage:
    - locate_vehicles()
  - name: add_new_route
    display_name: Add New Route
    description: Add a new location to the route of a vehicle.
    category: logistics
    parameters:
    - name: vehicle_id
      type: string
      description: The ID of the vehicle to update.
      required: true
    - name: location
      type: string
      description: The new location to be added to the route.
      required: true
    example_usage:
    - add_new_route(vehicle_id='V123', location='Warehouse B')
  - name: schedule_delivery
    display_name: Schedule Delivery
    description: Plan the delivery route for a UAV.
    category: logistics
    parameters:
    - name: uav_id
      type: string
      description: The ID of the UAV to schedule the delivery for.
      required: true
    - name: destination
      type: string
      description: The destination of the delivery.
      required: true
    example_usage:
    - schedule_delivery(uav_id='UAV001', destination='Customer Location')
  - name: monitor_weather
    display_name: Monitor Weather
    description: Check current and forecasted weather conditions.
    category: logistics
    parameters: []
    example_usage:
    - monitor_weather()
  - name: list_uavs
    display_name: List UAVs
    description: List all available UAVs and their current status.
    category: logistics
    parameters: []
    example_usage:
    - list_uavs()
  environment:
    name: vehicle_coordination_platform
    description: Platform environment for managing and coordinating unmanned vehicles and UAVs.
    variables:
    - name: WEATHER_API_URL
      value: 'https://api.weather.com'
      description: URL for accessing weather data
      type: string
    - name: MAX_VEHICLE_CAPACITY
      value: 50
      description: Maximum number of vehicles that can be managed simultaneously
      type: integer
    settings:
      route_update_interval: 10
      max_uavs_per_operator: 5
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - api.weather.com
    - '*.logistics-partner.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_operator_email: operator@logistics.com
    current_operator_name: Logistics Coordinator
    company_name: LogisticsCorp Inc.
    timezone: UTC
    business_hours: 24/7
  system_info:
    platform_version: '3.0'
    available_libraries:
    - requests
    - json
    - geopy
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true