name: venue_manager
display_name: Venue Manager
description: Manages venue-related operations including fetching venue information, retrieving weather forecasts, and booking venues for specific dates. Ensures efficient handling of venue data and booking processes.
category: event_management
complexity_level: 3
estimated_duration: 30
required_permissions:
- venue_data_access
- booking_management_access
dependencies: []
generation_weight: 1.5
sample_actions:
- fetch_weather_forecasts
- fetch_venues
- book_venue
metadata:
  selection_way: random
  selection_num: 3
tags:
- venues
- event_management
- booking
context:
  available_tools:
  - name: fetch_weather_forecasts
    display_name: Fetch Weather Forecasts
    description: Retrieve the weather forecasts for planning events
    category: weather
    parameters: []
    example_usage:
    - fetch_weather_forecasts()
    common_errors:
    - Unable to retrieve weather data
  - name: fetch_venues
    display_name: Fetch Venues
    description: Fetch the venue information for event planning
    category: venue_management
    parameters: []
    example_usage:
    - fetch_venues()
    common_errors:
    - Venue data not available
  - name: book_venue
    display_name: Book Venue
    description: Book a venue with a specific id and a date
    category: booking
    parameters:
    - name: id
      type: string
      description: The id of the venue
      required: true
    - name: date
      type: string
      description: The date for the booking
      required: true
    example_usage:
    - book_venue(id='venue123', date='2023-12-25')
    common_errors:
    - Invalid venue ID
    - Date not available for booking
  environment:
    name: event_management_platform
    description: Platform environment for managing venue and event bookings
    variables:
    - name: VENUE_API_URL
      value: 'https://api.venueinfo.com'
      description: API endpoint for venue data
      type: string
    - name: MAX_BOOKING_DAYS
      value: 365
      description: Maximum number of days in advance a venue can be booked
      type: integer
    settings:
      booking_confirmation_format: PDF
      max_venues_per_request: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - venueinfo.com
    - '*.trusted-partner.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: events@company.com
    current_user_name: Event Coordinator
    company_name: EventCorp Inc.
    timezone: UTC-5
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.0'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true