name: virtual_event_coordinator
display_name: Virtual Event Coordinator
description: Facilitates the organization and management of virtual events by gathering speaker biographies, generating event agendas, retrieving sponsor information, listing scheduled events, and sending emails to participants. Ensures seamless coordination and communication for successful virtual events.
category: event_management
complexity_level: 3
estimated_duration: 45
required_permissions:
- email_sending_access
- event_data_access
dependencies: []
generation_weight: 1.5
sample_actions:
- fetch_speaker_biographies
- generate_event_agenda
- get_sponsors_information
- list_events
- send_email
metadata:
  selection_way: random
  selection_num: 5
tags:
- virtual_events
- coordination
- communication
context:
  available_tools:
  - name: fetch_speaker_biographies
    display_name: Fetch Speaker Biographies
    description: Gather background information and biographies of potential speakers for virtual events
    category: information_gathering
    parameters: []
  - name: generate_event_agenda
    display_name: Generate Event Agenda
    description: Create a draft agenda for an event, including speaker names and their associated topics
    category: planning
    parameters:
    - name: event_name
      type: string
      description: The name of the event for which the agenda should be generated
      required: true
    - name: speaker_intro
      type: string
      description: The introduction of the speaker
      required: true
  - name: get_sponsors_information
    display_name: Get Sponsors Information
    description: Retrieve information of sponsors
    category: information_gathering
    parameters: []
  - name: list_events
    display_name: List Events
    description: List all scheduled events, their details, and participants
    category: information_gathering
    parameters: []
  - name: send_email
    display_name: Send Email
    description: Send an email to specified participants about an event
    category: communication
    parameters:
    - name: recipients
      type: list
      description: Email addresses of recipients
      required: true
    - name: subject
      type: string
      description: Subject of the email
      required: true
    - name: body
      type: string
      description: Body content of the email
      required: true
  environment:
    name: virtual_event_platform
    description: Platform environment for managing virtual events with communication and coordination tools
    variables:
    - name: EVENT_API_URL
      value: 'https://api.virtualevents.com'
      description: Base URL for the event management API
      type: string
    - name: MAX_EMAIL_RECIPIENTS
      value: 100
      description: Maximum number of email recipients allowed per send
      type: integer
    settings:
      email_format: HTML
      max_events_per_day: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - virtualevents.com
    - '*.trusted-sponsor.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: coordinator@virtualevents.com
    current_user_name: Event Coordinator
    company_name: VirtualEvents Inc.
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.0'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true