name: virtual_therapy
display_name: Virtual Therapy Session Management
description: Manage and retrieve details of virtual therapy sessions, including session listings, note management, and confidentiality considerations. This scenario supports therapists in organizing and accessing session information efficiently while maintaining patient confidentiality.
category: healthcare
complexity_level: 3
estimated_duration: 30
required_permissions:
- session_data_access
- note_modification_access
dependencies: []
generation_weight: 1.5
sample_actions:
- get_all_therapy_session_details
- list_sessions
- list_notes
- modify_note_content
metadata:
  selection_way: random
  selection_num: 2
tags:
- therapy
- healthcare
- session_management
context:
  available_tools:
  - name: get_all_therapy_session_details
    display_name: Get All Therapy Session Details
    description: Retrieve comprehensive details of all therapy sessions including facilitator and topics discussed.
    category: session_management
    parameters: []
    example_usage:
    - get_all_therapy_session_details()
  - name: list_sessions
    display_name: List Sessions
    description: List all available therapy sessions.
    category: session_management
    parameters: []
    example_usage:
    - list_sessions()
  - name: list_notes
    display_name: List Notes
    description: Lists all notes available for patients.
    category: note_management
    parameters: []
    example_usage:
    - list_notes()
  - name: modify_note_content
    display_name: Modify Note Content
    description: Modify the content of a note with a specific ID.
    category: note_management
    parameters:
    - name: note_id
      type: string
      description: The ID of the note whose content is to be modified.
      required: true
    - name: new_content
      type: string
      description: The new content to be modified.
      required: true
    example_usage:
    - modify_note_content(note_id='note123', new_content='Updated content here.')
  environment:
    name: virtual_therapy_platform
    description: A secure platform for managing virtual therapy sessions and patient notes.
    variables:
    - name: CONFIDENTIALITY_NOTICE_URL
      value: 'https://www.exampletherapy.com/confidentiality'
      description: URL to the confidentiality notice page
      type: string
    - name: MAX_SESSION_DURATION
      value: 60
      description: Maximum duration of a therapy session in minutes
      type: integer
    settings:
      note_format: text
      max_notes_per_session: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - exampletherapy.com
    - '*.trusted-health.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: therapist@exampletherapy.com
    current_user_name: Licensed Therapist
    organization_name: TherapyCare Inc.
    timezone: UTC-6
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true