name: virtual_reality_training_simulator
display_name: Virtual Reality Training Simulator
description: A comprehensive virtual reality training simulator designed to enhance training experiences by providing various modules and scenarios. It allows users to list available modules, update training group sizes, retrieve user activity logs, check user authority, and manage training scenarios.
category: training_simulation
complexity_level: 3
estimated_duration: 45
required_permissions:
- module_management_access
- user_activity_access
dependencies: []
generation_weight: 1.5
sample_actions:
- list_modules
- update_training_group_size
- get_user_activity_logs
- check_authority
- list_scenarios
- upload_scenario
metadata:
  selection_way: random
  selection_num: 5
tags:
- virtual_reality
- training
- simulation
context:
  available_tools:
  - name: list_modules
    display_name: List Modules
    description: List all available training modules.
    category: module_management
    parameters: []
    example_usage:
    - list_modules()
  - name: update_training_group_size
    display_name: Update Training Group Size
    description: Update the group size for a specific training module.
    category: module_management
    parameters:
    - name: module_id
      type: string
      description: The identifier of the training module.
      required: true
    - name: group_size
      type: number
      description: The new group size for the module.
      required: true
    example_usage:
    - update_training_group_size(module_id='module123', group_size=10)
  - name: get_user_activity_logs
    display_name: Get User Activity Logs
    description: Retrieve the activity logs for a given user including all simulations they have participated in.
    category: user_management
    parameters: []
    example_usage:
    - get_user_activity_logs()
  - name: check_authority
    display_name: Check Authority
    description: Check the authority of a person whether he or she has access to user logs.
    category: security
    parameters:
    - name: name
      type: string
      description: The input name to be checked
      required: true
    example_usage:
    - check_authority(name='John Doe')
  - name: list_scenarios
    display_name: List Scenarios
    description: Lists all available training scenarios within the VR system.
    category: scenario_management
    parameters: []
    example_usage:
    - list_scenarios()
  - name: upload_scenario
    display_name: Upload Scenario
    description: Upload the scenario to the public.
    category: scenario_management
    parameters:
    - name: scenario_id
      type: string
      description: The ID of the scenario to update.
      required: true
    example_usage:
    - upload_scenario(scenario_id='scenario456')
  environment:
    name: vr_training_environment
    description: Virtual reality training environment with module and scenario management tools.
    variables:
    - name: MAX_GROUP_SIZE
      value: 20
      description: Maximum number of participants allowed in a training group.
      type: integer
    - name: SCENARIO_UPLOAD_URL
      value: 'https://vr-training.example.com/upload'
      description: URL for uploading training scenarios.
      type: string
    settings:
      default_group_size: 5
      log_retention_days: 90
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - vr-training.example.com
    - '*.trusted-vr-partner.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_role: Training Manager
    organization_name: VR Training Solutions Inc.
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.2'
    available_libraries:
    - numpy
    - pandas
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true