name: volcanic_activity_tracker
display_name: Volcanic Activity Tracker
description: Monitors and provides updates on the recent status of specified volcanoes, offering crucial information for disaster preparedness and response efforts.
category: environmental_monitoring
complexity_level: 3
estimated_duration: 15
required_permissions:
- geolocation_access
- data_retrieval_access
dependencies: []
generation_weight: 1.5
sample_actions:
- get_volcano_info
metadata:
  selection_way: random
  selection_num: 2
tags:
- volcanoes
- disaster_preparedness
- environmental_monitoring
context:
  available_tools:
  - name: get_volcano_info
    display_name: Get Volcano Information
    description: Retrieve the latest status and activity reports of specified volcanoes
    category: data_retrieval
    parameters:
    - name: volcano_id
      type: string
      description: Unique identifier for the volcano
      required: true
    - name: region
      type: string
      description: Geographical region of interest
      required: false
    example_usage:
    - get_volcano_info(volcano_id='volcano123', region='Pacific Northwest')
    common_errors:
    - Invalid volcano ID
    - Data not available for the specified region
  environment:
    name: geological_monitoring_system
    description: A system environment equipped with tools for monitoring geological activities and natural disasters
    variables:
    - name: VOLCANO_API_URL
      value: 'https://api.volcanoes.example.com'
      description: API endpoint for accessing volcano data
      type: string
    - name: ALERT_THRESHOLD
      value: 5
      description: Alert level threshold for volcanic activity
      type: integer
    settings:
      data_refresh_interval: 10
      max_volcanoes_per_request: 10
    max_memory_mb: 512
    max_execution_time: 120
    network_access: true
    allowed_domains:
    - volcanoes.example.com
    - '*.trusted-data-source.com'
    blocked_domains:
    - '*.unverified-source.com'
  predefined_variables:
    current_user_email: geologist@example.com
    current_user_name: Geological Analyst
    organization_name: GeoWatch Institute
    timezone: UTC-8
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - xml.etree.ElementTree
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true