name: weather_predictor
display_name: Weather Predictor
description: Provides weather forecasting capabilities by listing current settings, accessing forecast data, and adjusting prediction confidence levels for different regions. This scenario is designed to ensure accurate and reliable weather predictions by allowing adjustments and checks on forecast data.
category: data_analysis
complexity_level: 3
estimated_duration: 30
required_permissions:
- weather_data_access
- forecast_adjustment_access
dependencies: []
generation_weight: 1.5
sample_actions:
- list_current_settings
- check_forecast
- adjust_prediction_confidence
metadata:
  selection_way: random
  selection_num: 3
tags:
- weather
- forecasting
- data_analysis
context:
  available_tools:
  - name: list_current_settings
    display_name: List Current Settings
    description: List the current settings for weather reporting in different regions
    category: data_management
    parameters: []
    example_usage:
    - list_current_settings()
  - name: check_forecast
    display_name: Check Forecast
    description: Access the weather forecast data for the specified location and date
    category: data_access
    parameters:
    - name: location
      type: string
      description: The location for which to check the forecast
      required: true
    - name: forecast_date
      type: string
      description: The date for which to retrieve the forecast
      required: true
    example_usage:
    - check_forecast(location='New York', forecast_date='2023-10-15')
  - name: adjust_prediction_confidence
    display_name: Adjust Prediction Confidence
    description: Adjust the confidence level for weather predictions in a specific region
    category: data_adjustment
    parameters:
    - name: region_id
      type: string
      description: The ID of the region
      required: true
    - name: confidence
      type: number
      description: The revised confidence level percentage
      required: true
    example_usage:
    - adjust_prediction_confidence(region_id='region123', confidence=85.5)
  environment:
    name: weather_analysis_platform
    description: Platform for analyzing and predicting weather patterns with access to regional data
    variables:
    - name: API_KEY
      value: 'your_api_key_here'
      description: API key for accessing weather data services
      type: string
    - name: DEFAULT_CONFIDENCE_LEVEL
      value: 75
      description: Default confidence level for predictions
      type: integer
    settings:
      forecast_data_format: JSON
      max_regions_per_query: 10
    max_memory_mb: 512
    max_execution_time: 300
    network_access: true
    allowed_domains:
    - weatherapi.com
    - '*.trusted-weather-source.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: analyst@weathercorp.com
    current_user_name: Weather Data Analyst
    company_name: WeatherCorp Inc.
    timezone: UTC
    business_hours: 9:00-17:00
  system_info:
    platform_version: '3.1'
    available_libraries:
    - requests
    - numpy
    - pandas
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true