name: accounting_advisor
display_name: Accounting Advisor
description: Analyzes financial statements, provides accounting advice, and assists with bookkeeping tasks to ensure accurate financial management and compliance with regulations.
category: finance
complexity_level: 4
estimated_duration: 45
required_permissions:
- financial_data_access
- accounting_software_access
dependencies: []
generation_weight: 1.8
sample_actions:
- analyze_financial_statements
- provide_accounting_advice
- assist_with_bookkeeping
- generate_financial_reports
metadata:
  selection_way: random
  selection_num: 3
tags:
- finance
- accounting
- bookkeeping
context:
  available_tools:
  - name: analyze_financial_statements
    display_name: Analyze Financial Statements
    description: Evaluate financial documents to assess financial health
    category: finance
    parameters:
    - name: statements
      type: list
      description: List of financial statements to analyze
      required: true
    - name: analysis_type
      type: string
      description: Type of analysis to perform
      required: true
      allowed_values:
      - ratio_analysis
      - trend_analysis
      - variance_analysis
    example_usage:
    - analyze_financial_statements(statements=['balance_sheet.pdf'], analysis_type='ratio_analysis')
  - name: provide_accounting_advice
    display_name: Provide Accounting Advice
    description: Offer guidance on accounting practices and compliance
    category: finance
    parameters:
    - name: query
      type: string
      description: Specific accounting question or topic
      required: true
    example_usage:
    - provide_accounting_advice(query='How to handle deferred revenue?')
  - name: assist_with_bookkeeping
    display_name: Assist with Bookkeeping
    description: Help with recording and organizing financial transactions
    category: finance
    parameters:
    - name: transactions
      type: list
      description: List of transactions to record
      required: true
    example_usage:
    - assist_with_bookkeeping(transactions=['invoice_123.csv'])
  environment:
    name: financial_management_system
    description: Secure environment for managing financial data and processes
    variables:
    - name: ACCOUNTING_SOFTWARE
      value: QuickBooks
      description: Accounting software used for bookkeeping
      type: string
    - name: MAX_TRANSACTION_SIZE
      value: 1000
      description: Maximum number of transactions per batch
      type: integer
    settings:
      encryption_required: true
      audit_logging: true
      max_memory_mb: 1024
      max_execution_time: 600
    network_access: true
    allowed_domains:
    - finance.company.com
    - '*.trusted-accounting.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: accountant@company.com
    current_user_name: Financial Advisor Bot
    company_name: FinanceCorp Ltd.
    timezone: UTC-5
    business_hours: 8:00-18:00
  system_info:
    accounting_software_version: '2023.1'
    available_libraries:
    - pandas
    - numpy
    - matplotlib
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true