name: action_figure_generator
display_name: Action Figure Generator
description: Designs custom action figures and packaging based on user or business personas. This scenario involves creating detailed 3D models, selecting materials, and designing packaging that reflects the persona's characteristics and branding.
category: design
complexity_level: 4
estimated_duration: 45
required_permissions:
- design_tool_access
- 3d_modeling_access
dependencies: []
generation_weight: 2.0
sample_actions:
- create_3d_model
- select_materials
- design_packaging
- generate_persona_profile
metadata:
  selection_way: random
  selection_num: 3
tags:
- design
- 3d_modeling
- branding
context:
  available_tools:
  - name: create_3d_model
    display_name: Create 3D Model
    description: Develops a 3D model of the action figure based on input parameters
    category: 3d_modeling
    parameters:
    - name: persona_attributes
      type: dict
      description: Attributes of the persona to model
      required: true
    - name: scale
      type: float
      description: Scale of the model
      required: true
    example_usage:
    - "create_3d_model(persona_attributes={'height': '6ft', 'style': 'heroic'}, scale=1.0)"
    common_errors:
    - Invalid persona attributes
    - Unsupported scale value
  - name: design_packaging
    display_name: Design Packaging
    description: Creates packaging design that reflects the persona's branding
    category: design
    parameters:
    - name: branding_elements
      type: list
      description: List of branding elements to include
      required: true
    - name: packaging_material
      type: string
      description: Material for packaging
      required: true
    example_usage:
    - "design_packaging(branding_elements=['logo', 'color_scheme'], packaging_material='cardboard')"
  environment:
    name: design_studio
    description: Virtual design studio environment with access to 3D modeling and design tools
    variables:
    - name: DESIGN_TOOL_VERSION
      value: '2.5'
      description: Version of the design tool
      type: string
    - name: MAX_MODEL_SIZE_MB
      value: 100
      description: Maximum size for 3D models in MB
      type: integer
    - name: SUPPORTED_FORMATS
      value: ['stl', 'obj', 'fbx']
      description: Supported 3D model formats
      type: list
    settings:
      high_resolution_rendering: true
      packaging_design_templates: true
    max_memory_mb: 1024
    max_execution_time: 600
    network_access: true
    allowed_domains:
    - design-tools.com
    - '*.trusted-partner.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_role: Designer
    company_name: CreativeWorks Inc.
    timezone: UTC-5
    business_hours: 8:00-18:00
  system_info:
    design_tool_version: '2.5'
    available_libraries:
    - blender
    - photoshop
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true