name: art_graphic_designer
display_name: Art & Graphic Designer
description: The agent is tasked with designing logos, graphics, and visual materials. This involves using graphic design software to create visually appealing and effective designs for various purposes, including branding, marketing, and digital content.
category: design
complexity_level: 4
estimated_duration: 45
required_permissions:
- design_software_access
- file_system_access
dependencies: []
generation_weight: 1.8
sample_actions:
- open_design_software
- create_new_project
- export_design
- apply_filter
metadata:
  selection_way: random
  selection_num: 3
tags:
- design
- graphics
- creativity
context:
  available_tools:
  - name: design_software
    display_name: Design Software
    description: Software used for creating and editing graphic designs
    category: design
    parameters:
    - name: project_name
      type: string
      description: Name of the design project
      required: true
    - name: canvas_size
      type: string
      description: Size of the design canvas
      required: true
    - name: color_palette
      type: list
      description: List of colors to be used in the design
      required: false
    example_usage:
    - open_design_software(project_name='Logo Design', canvas_size='1024x768')
    - open_design_software(project_name='Flyer', canvas_size='A4', color_palette=['#FF5733', '#33FF57'])
    common_errors:
    - Unsupported canvas size
    - Invalid color code in palette
  - name: image_library
    display_name: Image Library
    description: Access a library of stock images and graphics
    category: design
    parameters:
    - name: search_query
      type: string
      description: Keywords to search for images
      required: true
    - name: license_type
      type: string
      description: Type of license for image use
      required: false
      default_value: royalty_free
      allowed_values:
      - royalty_free
      - rights_managed
    example_usage:
    - image_library(search_query='nature', license_type='royalty_free')
    - image_library(search_query='business icons')
  environment:
    name: graphic_design_suite
    description: A comprehensive environment equipped with tools for graphic design and image editing
    variables:
    - name: DESIGN_TOOL_PATH
      value: /usr/local/bin/design_tool
      description: Path to the design software executable
      type: string
    - name: MAX_CANVAS_SIZE
      value: '4096x4096'
      description: Maximum allowable canvas size
      type: string
    - name: SUPPORTED_FORMATS
      value: ['png', 'jpg', 'svg', 'pdf']
      description: Supported export formats
      type: list
    settings:
      auto_save_interval: 10
      default_color_mode: RGB
      max_layers_per_project: 100
    max_memory_mb: 1024
    max_execution_time: 600
    network_access: true
    allowed_domains:
    - '*.trusted-image-source.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_name: Graphic Designer AI
    company_name: Creative Solutions Inc.
    timezone: UTC-5
    business_hours: 8:00-18:00
  system_info:
    design_software_version: '2.5'
    available_libraries:
    - PIL
    - numpy
  security_policy:
    data_classification_required: false
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true