name: competitive_analysis_agent
display_name: Competitive Analysis Agent
description: Conducts market and competitor research, generating comparative insights.
  This agent is designed to gather data on market trends, analyze competitors' strengths
  and weaknesses, and provide actionable insights for strategic decision-making.
category: research
complexity_level: 4
estimated_duration: 45
required_permissions:
- internet_access
- data_analysis
dependencies: []
generation_weight: 1.8
sample_actions:
- gather_market_data
- analyze_competitor_strengths
- generate_insights
- compile_report
metadata:
  selection_way: random
  selection_num: 3
tags:
- market_analysis
- competitor_research
- strategic_planning
context:
  available_tools:
  - name: web_scraper
    display_name: Web Scraper
    description: Extract data from websites for analysis
    category: data_collection
    parameters:
    - name: url
      type: string
      description: URL of the website to scrape
      required: true
    - name: data_points
      type: list
      description: Specific data points to extract
      required: true
    example_usage:
    - web_scraper(url='https://example.com', data_points=['price', 'features'])
    common_errors:
    - Invalid URL format
    - Data points not found on the page
  - name: data_analyzer
    display_name: Data Analyzer
    description: Analyze collected data to generate insights
    category: data_analysis
    parameters:
    - name: dataset
      type: string
      description: Path to the dataset file
      required: true
    - name: analysis_type
      type: string
      description: Type of analysis to perform
      required: true
      allowed_values:
      - SWOT
      - trend
      - comparative
    example_usage:
    - data_analyzer(dataset='market_data.csv', analysis_type='SWOT')
  environment:
    name: research_environment
    description: Secure environment for conducting market and competitor research
    variables:
    - name: API_KEY
      value: 'your_api_key_here'
      description: API key for accessing external data sources
      type: string
    - name: MAX_DATA_SIZE
      value: 100
      description: Maximum data size in MB
      type: integer
    settings:
      data_encryption: true
      secure_data_storage: true
      max_concurrent_requests: 10
    max_memory_mb: 1024
    max_execution_time: 600
    network_access: true
    allowed_domains:
    - '*.trusted-data-source.com'
    - '*.market-research.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_role: Research Analyst
    organization_name: InsightCorp
    timezone: UTC-5
    working_hours: 8:00-18:00
  system_info:
    analysis_tool_version: '2.5'
    available_libraries:
    - pandas
    - numpy
    - requests
  security_policy:
    data_classification_required: true
    external_data_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true