name: concept_explainer
display_name: Concept Explainer
description: The agent breaks down complex topics into understandable explanations, making it easier for users to grasp difficult concepts. This involves using various tools and methods to simplify information and present it in an accessible format.
category: education
complexity_level: 4
estimated_duration: 45
required_permissions:
- knowledge_access
dependencies: []
generation_weight: 1.2
sample_actions:
- analyze_topic
- simplify_information
- generate_examples
- create_visual_aids
metadata:
  selection_way: random
  selection_num: 3
tags:
- education
- explanation
- learning
context:
  available_tools:
  - name: summarize_text
    display_name: Summarize Text
    description: Summarize complex text into simpler, shorter versions
    category: text_processing
    parameters:
    - name: text
      type: string
      description: Text to be summarized
      required: true
    example_usage:
    - summarize_text(text='Quantum mechanics is a fundamental theory in physics...')
    common_errors:
    - Input text too short to summarize
  - name: generate_analogy
    display_name: Generate Analogy
    description: Create analogies to explain complex concepts
    category: creativity
    parameters:
    - name: concept
      type: string
      description: Concept to explain with an analogy
      required: true
    example_usage:
    - generate_analogy(concept='Blockchain technology')
  environment:
    name: educational_platform
    description: An environment optimized for educational content delivery and interaction
    variables:
    - name: MAX_TEXT_LENGTH
      value: 10000
      description: Maximum length of text input for processing
      type: integer
    - name: SUPPORTED_LANGUAGES
      value: ['en', 'es', 'fr']
      description: Languages supported for explanation
      type: list
    settings:
      interactive_mode: true
      feedback_collection: true
    max_memory_mb: 1024
    max_execution_time: 600
    network_access: true
    allowed_domains:
    - '*.edu'
    - '*.knowledge-base.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_role: educator
    preferred_language: en
    learning_style: visual
  system_info:
    explanation_engine_version: '2.3'
    available_libraries:
    - nltk
    - transformers
  security_policy:
    data_classification_required: false
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true