name: devops_assistant
display_name: DevOps Assistant
description: The DevOps Assistant monitors server health, automates deployment notifications, and assists in rolling back failed updates. It ensures continuous integration and delivery processes run smoothly, minimizing downtime and maintaining system reliability.
category: operations
complexity_level: 4
estimated_duration: 45
required_permissions:
- server_access
- deployment_access
dependencies: []
generation_weight: 1.8
sample_actions:
- monitor_server_health
- send_deployment_notification
- rollback_update
- check_logs
metadata:
  selection_way: random
  selection_num: 3
tags:
- devops
- automation
- monitoring
- notifications
context:
  available_tools:
  - name: monitor_server
    display_name: Monitor Server
    description: Continuously check server health and performance metrics
    category: monitoring
    parameters:
    - name: server_id
      type: string
      description: Unique identifier for the server
      required: true
    - name: metrics
      type: list
      description: List of metrics to monitor (e.g., CPU, memory, disk)
      required: true
    example_usage:
    - monitor_server(server_id='server123', metrics=['CPU', 'memory'])
    common_errors:
    - Server not reachable
    - Invalid server ID
  - name: notify_deployment
    display_name: Notify Deployment
    description: Send notifications about deployment status to relevant teams
    category: communication
    parameters:
    - name: deployment_id
      type: string
      description: Identifier for the deployment
      required: true
    - name: status
      type: string
      description: Current status of the deployment
      required: true
    - name: recipients
      type: list
      description: List of email addresses to notify
      required: true
    example_usage:
    - notify_deployment(deployment_id='deploy456', status='success', recipients=['devops@company.com'])
  - name: rollback_update
    display_name: Rollback Update
    description: Revert a failed update to the last stable version
    category: operations
    parameters:
    - name: update_id
      type: string
      description: Identifier for the update to rollback
      required: true
    example_usage:
    - rollback_update(update_id='update789')
  environment:
    name: devops_environment
    description: Secure environment for managing server operations and deployments
    variables:
    - name: API_ENDPOINT
      value: api.devops.company.com
      description: API endpoint for server management
      type: string
    - name: MAX_RETRY_ATTEMPTS
      value: 3
      description: Maximum number of retry attempts for failed operations
      type: integer
    - name: NOTIFICATION_EMAIL
      value: devops@company.com
      description: Default email for sending notifications
      type: string
    settings:
      logging_enabled: true
      max_concurrent_operations: 5
    max_memory_mb: 1024
    max_execution_time: 600
    network_access: true
    allowed_domains:
    - company.com
    - '*.trusted-partner.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: devops_agent@company.com
    current_user_name: DevOps Assistant
    company_name: TechCorp Inc.
    timezone: UTC-5
    business_hours: 24/7
  system_info:
    devops_tool_version: '2.3'
    available_libraries:
    - requests
    - logging
    - smtplib
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true