name: document_summarizer
display_name: Document Summarizer
description: The agent reads long documents or reports and generates concise summaries,
  providing users with quick insights and key points without needing to read the entire
  document. This is particularly useful for processing large volumes of information
  efficiently.
category: information_processing
complexity_level: 4
estimated_duration: 45
required_permissions:
- document_access
dependencies: []
generation_weight: 1.8
sample_actions:
- read_document
- generate_summary
- highlight_key_points
metadata:
  selection_way: random
  selection_num: 3
tags:
- summarization
- document_processing
- automation
context:
  available_tools:
  - name: read_document
    display_name: Read Document
    description: Read and parse the content of a document
    category: information_processing
    parameters:
    - name: document_path
      type: string
      description: Path to the document file
      required: true
    - name: format
      type: string
      description: Document format (e.g., PDF, DOCX)
      required: true
      allowed_values:
      - PDF
      - DOCX
      - TXT
    example_usage:
    - read_document(document_path='/docs/report.pdf', format='PDF')
    common_errors:
    - File not found
    - Unsupported document format
  - name: generate_summary
    display_name: Generate Summary
    description: Create a concise summary from the document content
    category: information_processing
    parameters:
    - name: content
      type: string
      description: Full text content to summarize
      required: true
    - name: summary_length
      type: integer
      description: Desired length of the summary in sentences
      required: false
      default_value: 5
    example_usage:
    - generate_summary(content='Full document text...', summary_length=3)
  environment:
    name: document_processing_env
    description: Environment optimized for processing and summarizing documents
    variables:
    - name: MAX_DOCUMENT_SIZE_MB
      value: 50
      description: Maximum document size in MB
      type: integer
    - name: SUPPORTED_FORMATS
      value: [PDF, DOCX, TXT]
      description: Supported document formats
      type: list
    settings:
      text_extraction_accuracy: high
      summary_quality: concise
    max_memory_mb: 1024
    max_execution_time: 600
    network_access: false
  predefined_variables:
    current_user_name: AI Document Assistant
    organization_name: InfoTech Solutions
    timezone: UTC-5
    working_hours: 8:00-18:00
  system_info:
    document_parser_version: '2.3'
    available_libraries:
    - PyPDF2
    - python-docx
    - nltk
  security_policy:
    data_classification_required: true
    encryption_at_rest: true
    audit_logging: true