name: expense_report_generator
display_name: Expense Report Generator
description: The agent extracts receipts from emails, fills out expense forms, and submits them for approval. This process automates the tedious task of managing expenses by ensuring that all receipts are accurately documented and submitted in a timely manner.
category: finance
complexity_level: 4
estimated_duration: 45
required_permissions:
- email_access
- document_access
- form_submission
dependencies: []
generation_weight: 1.8
sample_actions:
- extract_receipts
- fill_expense_form
- submit_for_approval
- verify_receipt_data
metadata:
  selection_way: random
  selection_num: 3
tags:
- finance
- automation
- expense_management
context:
  available_tools:
  - name: extract_receipts
    display_name: Extract Receipts
    description: Extract receipts from email attachments
    category: document_processing
    parameters:
    - name: email_address
      type: string
      description: Email address to search for receipts
      required: true
    - name: date_range
      type: string
      description: Date range for filtering emails
      required: false
    example_usage:
    - extract_receipts(email_address='user@company.com', date_range='last_month')
    common_errors:
    - No receipts found in specified date range
    - Invalid email address format
  - name: fill_expense_form
    display_name: Fill Expense Form
    description: Automatically fill out an expense form with extracted data
    category: document_processing
    parameters:
    - name: receipt_data
      type: list
      description: List of extracted receipt data
      required: true
    - name: form_template
      type: string
      description: Path to the expense form template
      required: true
    example_usage:
    - fill_expense_form(receipt_data=[...], form_template='template.xlsx')
  - name: submit_for_approval
    display_name: Submit for Approval
    description: Submit the completed expense form for managerial approval
    category: workflow
    parameters:
    - name: form_path
      type: string
      description: Path to the completed expense form
      required: true
    - name: approver_email
      type: string
      description: Email of the approver
      required: true
    example_usage:
    - submit_for_approval(form_path='completed_form.xlsx', approver_email='manager@company.com')
  environment:
    name: corporate_finance
    description: Corporate finance environment with secure document handling
    variables:
    - name: EMAIL_SERVER
      value: imap.company.com
      description: Corporate IMAP server for email access
      type: string
    - name: MAX_ATTACHMENT_SIZE
      value: 20
      description: Maximum attachment size in MB
      type: integer
    - name: FORM_SUBMISSION_URL
      value: https://finance.company.com/submit
      description: URL for submitting expense forms
      type: string
    settings:
      encryption_required: true
      audit_logging: true
      max_emails_to_process: 100
    max_memory_mb: 1024
    max_execution_time: 600
    network_access: true
    allowed_domains:
    - company.com
    - '*.trusted-partner.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: agent@company.com
    current_user_name: Expense Bot
    company_name: FinTech Solutions Inc.
    timezone: UTC-5
    business_hours: 8:00-18:00
  system_info:
    document_processing_version: '2.1'
    available_libraries:
    - imaplib
    - openpyxl
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true