name: financial_market_analyst
display_name: Financial Market Analyst
description: Provides real-time stock, crypto, and economic analysis, with educational market explanations. This scenario involves monitoring financial markets, analyzing trends, and offering insights and educational content to users interested in financial markets.
category: finance
complexity_level: 4
estimated_duration: 45
required_permissions:
- internet_access
- financial_data_access
dependencies: []
generation_weight: 2.0
sample_actions:
- fetch_stock_data
- analyze_market_trends
- generate_report
- provide_educational_content
metadata:
  selection_way: random
  selection_num: 3
tags:
- finance
- analysis
- education
- real-time
context:
  available_tools:
  - name: fetch_stock_data
    display_name: Fetch Stock Data
    description: Retrieve real-time stock market data
    category: finance
    parameters:
    - name: ticker
      type: string
      description: Stock ticker symbol
      required: true
    - name: exchange
      type: string
      description: Stock exchange code
      required: false
    example_usage:
    - fetch_stock_data(ticker='AAPL')
    - fetch_stock_data(ticker='GOOGL', exchange='NASDAQ')
    common_errors:
    - Invalid ticker symbol
    - Exchange not supported
  - name: analyze_market_trends
    display_name: Analyze Market Trends
    description: Analyze trends in stock and crypto markets
    category: finance
    parameters:
    - name: data
      type: list
      description: List of market data points
      required: true
    - name: analysis_type
      type: string
      description: Type of analysis to perform
      required: false
      default_value: technical
      allowed_values:
      - technical
      - fundamental
    example_usage:
    - analyze_market_trends(data=[...], analysis_type='technical')
    - analyze_market_trends(data=[...])
  environment:
    name: financial_analysis_env
    description: Environment configured for financial data analysis with secure data handling
    variables:
    - name: API_KEY
      value: 'your_api_key_here'
      description: API key for accessing financial data services
      type: string
    - name: DATA_REFRESH_INTERVAL
      value: 60
      description: Data refresh interval in seconds
      type: integer
    - name: MAX_DATA_POINTS
      value: 1000
      description: Maximum number of data points to analyze at once
      type: integer
    settings:
      encryption_required: true
      data_retention_period_days: 30
    max_memory_mb: 1024
    max_execution_time: 600
    network_access: true
    allowed_domains:
    - '*.financialdata.com'
    - '*.trusted-finance.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_role: Financial Analyst
    market_open_time: 9:30
    market_close_time: 16:00
    timezone: UTC-5
  system_info:
    analysis_tool_version: '2.1'
    available_libraries:
    - pandas
    - numpy
    - matplotlib
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true