name: fleet_tracker
display_name: Fleet Tracker
description: Monitors vehicle locations, schedules maintenance, and notifies about delays. 
  This scenario involves tracking the real-time location of vehicles, managing maintenance 
  schedules to ensure fleet efficiency, and providing timely notifications to relevant 
  stakeholders about any delays or issues.
category: logistics
complexity_level: 4
estimated_duration: 45
required_permissions:
- location_access
- notification_access
dependencies: []
generation_weight: 1.8
sample_actions:
- track_vehicle
- schedule_maintenance
- notify_delay
- update_location
metadata:
  selection_way: random
  selection_num: 3
tags:
- fleet
- logistics
- tracking
- maintenance
context:
  available_tools:
  - name: track_vehicle
    display_name: Track Vehicle
    description: Track the real-time location of a vehicle
    category: logistics
    parameters:
    - name: vehicle_id
      type: string
      description: Unique identifier for the vehicle
      required: true
    - name: gps_coordinates
      type: string
      description: Current GPS coordinates of the vehicle
      required: true
    example_usage:
    - track_vehicle(vehicle_id='V123', gps_coordinates='37.7749,-122.4194')
    common_errors:
    - Invalid vehicle ID
    - GPS coordinates not found
  - name: schedule_maintenance
    display_name: Schedule Maintenance
    description: Schedule maintenance for a vehicle
    category: logistics
    parameters:
    - name: vehicle_id
      type: string
      description: Unique identifier for the vehicle
      required: true
    - name: maintenance_date
      type: string
      description: Date for scheduled maintenance
      required: true
    example_usage:
    - schedule_maintenance(vehicle_id='V123', maintenance_date='2023-11-15')
  - name: notify_delay
    display_name: Notify Delay
    description: Notify stakeholders about a delay
    category: logistics
    parameters:
    - name: vehicle_id
      type: string
      description: Unique identifier for the vehicle
      required: true
    - name: delay_reason
      type: string
      description: Reason for the delay
      required: true
    example_usage:
    - notify_delay(vehicle_id='V123', delay_reason='Traffic congestion')
  environment:
    name: fleet_management_system
    description: Fleet management environment with tracking and notification capabilities
    variables:
    - name: GPS_API_ENDPOINT
      value: api.gpsprovider.com
      description: Endpoint for GPS data
      type: string
    - name: MAINTENANCE_DB
      value: maintenance.db
      description: Database for maintenance records
      type: string
    - name: NOTIFICATION_SERVICE
      value: notify.service.com
      description: Service for sending notifications
      type: string
    settings:
      gps_tracking_enabled: true
      maintenance_alerts_enabled: true
      delay_notifications_enabled: true
    max_memory_mb: 1024
    max_execution_time: 600
    network_access: true
    allowed_domains:
    - gpsprovider.com
    - notify.service.com
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    fleet_manager_email: fleet.manager@logistics.com
    fleet_manager_name: Fleet Manager
    company_name: LogisticsCorp Inc.
    timezone: UTC-5
    business_hours: 8:00-18:00
  system_info:
    fleet_management_version: '2.1'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true