name: irrigation_scheduler
display_name: Irrigation Scheduler
description: Automates irrigation scheduling by analyzing weather forecasts and soil moisture data to optimize water usage and ensure efficient plant growth.
category: automation
complexity_level: 4
estimated_duration: 45
required_permissions:
- weather_data_access
- soil_data_access
dependencies: []
generation_weight: 1.8
sample_actions:
- fetch_weather_data
- analyze_soil_moisture
- schedule_irrigation
- adjust_irrigation_timing
metadata:
  selection_way: random
  selection_num: 3
tags:
- irrigation
- automation
- agriculture
- environmental
context:
  available_tools:
  - name: fetch_weather_data
    display_name: Fetch Weather Data
    description: Retrieve current and forecasted weather data from a reliable source
    category: data_acquisition
    parameters:
    - name: location
      type: string
      description: Geographic location for weather data
      required: true
    - name: forecast_days
      type: integer
      description: Number of days to forecast
      required: false
      default_value: 7
    example_usage:
    - fetch_weather_data(location='Farmville', forecast_days=5)
    common_errors:
    - Invalid location format
    - Data source unavailable
  - name: analyze_soil_moisture
    display_name: Analyze Soil Moisture
    description: Analyze soil moisture levels using sensor data
    category: data_analysis
    parameters:
    - name: sensor_id
      type: string
      description: Identifier for the soil moisture sensor
      required: true
    - name: threshold
      type: float
      description: Moisture level threshold for irrigation
      required: false
      default_value: 0.3
    example_usage:
    - analyze_soil_moisture(sensor_id='sensor_01', threshold=0.25)
  environment:
    name: smart_irrigation_system
    description: Environment for managing smart irrigation with real-time data integration
    variables:
    - name: WEATHER_API_URL
      value: api.weather.com
      description: URL for the weather data API
      type: string
    - name: SOIL_SENSOR_API
      value: api.soilsensors.com
      description: API endpoint for soil sensor data
      type: string
    - name: MAX_IRRIGATION_DURATION
      value: 120
      description: Maximum irrigation duration in minutes
      type: integer
    settings:
      data_refresh_interval: 60
      max_concurrent_sensors: 10
    max_memory_mb: 256
    max_execution_time: 600
    network_access: true
    allowed_domains:
    - weather.com
    - soilsensors.com
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    default_location: Farmville
    irrigation_start_time: 6:00
    irrigation_end_time: 18:00
    timezone: UTC-5
  system_info:
    irrigation_system_version: '2.1'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true