name: logo_design_advisor
display_name: Logo Design Advisor
description: The agent suggests logo concepts and style guides for new brands, providing creative
  insights and recommendations based on industry trends and brand identity.
category: design
complexity_level: 4
estimated_duration: 45
required_permissions:
- design_tool_access
- internet_access
dependencies: []
generation_weight: 1.8
sample_actions:
- analyze_brand_identity
- suggest_logo_concepts
- create_style_guide
- recommend_color_palette
metadata:
  selection_way: random
  selection_num: 3
tags:
- design
- branding
- creativity
context:
  available_tools:
  - name: design_tool
    display_name: Design Tool
    description: Tool for creating and editing logo designs
    category: design
    parameters:
    - name: brand_identity
      type: string
      description: Description of the brand's identity and values
      required: true
    - name: industry
      type: string
      description: Industry in which the brand operates
      required: true
    - name: style_preference
      type: string
      description: Preferred style for the logo
      required: false
    example_usage:
    - design_tool(brand_identity='eco-friendly', industry='retail', style_preference='minimalist')
    - design_tool(brand_identity='innovative tech', industry='software')
    common_errors:
    - Missing brand identity information
    - Unsupported style preference
  - name: trend_analysis
    display_name: Trend Analysis
    description: Analyze current design trends relevant to the brand's industry
    category: research
    parameters:
    - name: industry
      type: string
      description: Industry to analyze trends for
      required: true
    - name: region
      type: string
      description: Geographic region for trend analysis
      required: false
    example_usage:
    - trend_analysis(industry='fashion')
    - trend_analysis(industry='technology', region='North America')
  environment:
    name: design_suite
    description: Design environment with access to creative tools and resources
    variables:
    - name: DESIGN_TOOL_API
      value: api.designsuite.com
      description: API endpoint for design tools
      type: string
    - name: MAX_IMAGE_SIZE_MB
      value: 50
      description: Maximum image size for uploads in MB
      type: integer
    - name: SUPPORTED_FORMATS
      value: ['svg', 'png', 'jpg']
      description: Supported image formats for export
      type: list
    settings:
      high_resolution_required: true
      color_accuracy_required: true
      max_concepts_per_session: 10
    max_memory_mb: 1024
    max_execution_time: 600
    network_access: true
    allowed_domains:
    - designsuite.com
    - '*.trusted-design.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_role: Designer
    current_project_name: New Brand Launch
    company_name: Creative Solutions Inc.
    timezone: UTC-5
    business_hours: 8:00-18:00
  system_info:
    design_tool_version: '2.5'
    available_libraries:
    - PIL
    - numpy
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true