name: maintenance_request_handler
display_name: Maintenance Request Handler
description: This scenario enables tenants to submit maintenance issues, assigns appropriate vendors to handle the requests, and tracks the progress of each request until resolution. It ensures efficient management of maintenance tasks within a residential or commercial property setting.
category: property_management
complexity_level: 4
estimated_duration: 45
required_permissions:
- issue_tracking_access
- vendor_assignment_access
dependencies: []
generation_weight: 1.8
sample_actions:
- submit_issue
- assign_vendor
- update_progress
- close_request
metadata:
  selection_way: priority_based
  selection_num: 10
tags:
- maintenance
- property_management
- task_tracking
context:
  available_tools:
  - name: submit_issue
    display_name: Submit Issue
    description: Submit a maintenance issue with details
    category: issue_management
    parameters:
    - name: issue_description
      type: string
      description: Detailed description of the maintenance issue
      required: true
    - name: priority
      type: string
      description: Priority level of the issue
      required: true
      allowed_values:
      - low
      - medium
      - high
    - name: location
      type: string
      description: Location of the issue within the property
      required: true
    example_usage:
    - submit_issue(issue_description='Leaking faucet in kitchen', priority='high', location='Apartment 12B')
  - name: assign_vendor
    display_name: Assign Vendor
    description: Assign a vendor to handle the maintenance issue
    category: vendor_management
    parameters:
    - name: issue_id
      type: string
      description: Unique identifier of the maintenance issue
      required: true
    - name: vendor_id
      type: string
      description: Unique identifier of the vendor
      required: true
    example_usage:
    - assign_vendor(issue_id='12345', vendor_id='67890')
  - name: update_progress
    display_name: Update Progress
    description: Update the progress of a maintenance request
    category: task_tracking
    parameters:
    - name: issue_id
      type: string
      description: Unique identifier of the maintenance issue
      required: true
    - name: status
      type: string
      description: Current status of the issue
      required: true
      allowed_values:
      - pending
      - in_progress
      - completed
    example_usage:
    - update_progress(issue_id='12345', status='in_progress')
  environment:
    name: property_management_system
    description: A system environment for managing property maintenance requests and vendor assignments
    variables:
    - name: DATABASE_URL
      value: db.propertymanagement.com
      description: URL of the property management database
      type: string
    - name: MAX_ISSUE_SUBMISSIONS
      value: 100
      description: Maximum number of issues that can be submitted per day
      type: integer
    settings:
      issue_submission_notification: true
      vendor_assignment_notification: true
      max_vendors_per_issue: 3
    max_memory_mb: 1024
    max_execution_time: 600
    network_access: true
    allowed_domains:
    - propertymanagement.com
    - '*.trusted-vendor.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_role: property_manager
    property_name: Greenfield Apartments
    timezone: UTC-5
    business_hours: 8:00-18:00
  system_info:
    management_system_version: '2.1'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    vendor_verification_required: true
    encryption_at_rest: true
    audit_logging: true