name: network_monitoring
display_name: Network Monitoring
description: Detects and alerts administrators of unusual network activity, ensuring
  network integrity and security by monitoring traffic patterns and identifying potential
  threats.
category: security
complexity_level: 4
estimated_duration: 45
required_permissions:
- network_access
- alert_management
dependencies: []
generation_weight: 2.0
sample_actions:
- monitor_traffic
- analyze_patterns
- send_alert
- block_suspicious_activity
metadata:
  selection_way: random
  selection_num: 3
tags:
- network
- security
- monitoring
context:
  available_tools:
  - name: monitor_traffic
    display_name: Monitor Traffic
    description: Continuously monitor network traffic for anomalies
    category: security
    parameters:
    - name: interface
      type: string
      description: Network interface to monitor
      required: true
    - name: duration
      type: integer
      description: Duration in seconds to monitor
      required: false
      default_value: 60
    example_usage:
    - monitor_traffic(interface='eth0', duration=120)
    common_errors:
    - Invalid network interface
    - Insufficient permissions
  - name: send_alert
    display_name: Send Alert
    description: Send an alert to administrators about detected anomalies
    category: security
    parameters:
    - name: alert_message
      type: string
      description: Message to send in the alert
      required: true
    - name: severity
      type: string
      description: Severity level of the alert
      required: true
      allowed_values:
      - low
      - medium
      - high
    example_usage:
    - send_alert(alert_message='Unusual traffic detected', severity='high')
  environment:
    name: corporate_network
    description: Corporate network environment with strict security policies
    variables:
    - name: NETWORK_INTERFACE
      value: eth0
      description: Default network interface for monitoring
      type: string
    - name: ALERT_RECIPIENT
      value: admin@company.com
      description: Default recipient for alerts
      type: string
    settings:
      encryption_required: true
      max_alerts_per_hour: 10
    max_memory_mb: 1024
    max_execution_time: 600
    network_access: true
    allowed_domains:
    - '*.trusted-network.com'
    blocked_domains:
    - '*.malicious-site.com'
  predefined_variables:
    current_user_email: network_admin@company.com
    current_user_name: Network Admin
    company_name: SecureNet Inc.
    timezone: UTC-5
    business_hours: 24/7
  system_info:
    monitoring_tool_version: '2.1'
    available_libraries:
    - scapy
    - psutil
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true