name: order_status_checker
display_name: Order Status Checker
description: Provides real-time updates on order and delivery status, allowing users to track their purchases from dispatch to delivery. This scenario involves checking order details, estimated delivery times, and any potential delays.
category: logistics
complexity_level: 2
estimated_duration: 15
required_permissions:
- order_access
- delivery_tracking
dependencies: []
generation_weight: 1.2
sample_actions:
- check_order_status
- track_delivery
- notify_user
metadata:
  selection_way: random
  selection_num: 3
tags:
- logistics
- tracking
- automation
context:
  available_tools:
  - name: check_order_status
    display_name: Check Order Status
    description: Retrieve the current status of an order
    category: logistics
    parameters:
    - name: order_id
      type: string
      description: Unique identifier for the order
      required: true
    example_usage:
    - check_order_status(order_id='12345')
    common_errors:
    - Invalid order ID
    - Order not found
  - name: track_delivery
    display_name: Track Delivery
    description: Track the delivery progress of an order
    category: logistics
    parameters:
    - name: tracking_number
      type: string
      description: Delivery service tracking number
      required: true
    example_usage:
    - track_delivery(tracking_number='1Z999AA10123456784')
    common_errors:
    - Invalid tracking number
    - Tracking information not available
  environment:
    name: ecommerce_platform
    description: E-commerce platform environment with order and delivery tracking capabilities
    variables:
    - name: API_ENDPOINT
      value: api.ecommerce.com
      description: API endpoint for order and delivery services
      type: string
    - name: MAX_CONCURRENT_REQUESTS
      value: 10
      description: Maximum number of concurrent API requests
      type: integer
    settings:
      secure_connection_required: true
      data_encryption: true
    max_memory_mb: 256
    max_execution_time: 120
    network_access: true
    allowed_domains:
    - ecommerce.com
    - '*.trusted-carrier.com'
    blocked_domains:
    - '*.fraudulent-site.com'
  predefined_variables:
    current_user_id: user123
    current_user_name: John Doe
    preferred_carrier: FastShip Inc.
    timezone: UTC-5
    business_hours: 8:00-20:00
  system_info:
    platform_version: '2.5'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true