name: parking_spot_finder
display_name: Parking Spot Finder
description: This scenario involves locating available parking spots in crowded urban areas. 
  The agent will utilize various tools and data sources to efficiently identify and 
  suggest parking options to users, considering factors such as proximity, cost, and 
  availability.
category: navigation
complexity_level: 4
estimated_duration: 20
required_permissions:
- location_access
- internet_access
dependencies: []
generation_weight: 1.2
sample_actions:
- search_parking
- check_availability
- reserve_spot
metadata:
  selection_way: random
  selection_num: 3
tags:
- parking
- navigation
- urban
- automation
context:
  available_tools:
  - name: search_parking
    display_name: Search Parking
    description: Search for available parking spots in a specified area
    category: navigation
    parameters:
    - name: location
      type: string
      description: Location to search for parking
      required: true
    - name: radius
      type: integer
      description: Search radius in meters
      required: false
      default_value: 500
    - name: max_cost
      type: float
      description: Maximum acceptable parking cost
      required: false
    example_usage:
    - search_parking(location='Downtown', radius=1000, max_cost=10.0)
    - search_parking(location='Airport')
    common_errors:
    - Invalid location format
    - No parking found within specified parameters
  - name: check_availability
    display_name: Check Availability
    description: Check real-time availability of a specific parking spot
    category: navigation
    parameters:
    - name: spot_id
      type: string
      description: Unique identifier for the parking spot
      required: true
    example_usage:
    - check_availability(spot_id='P12345')
  environment:
    name: urban_navigation
    description: Urban navigation environment with real-time traffic and parking data
    variables:
    - name: MAP_API_KEY
      value: your_map_api_key_here
      description: API key for accessing map services
      type: string
    - name: MAX_SEARCH_RADIUS
      value: 2000
      description: Maximum search radius for parking in meters
      type: integer
    settings:
      real_time_updates: true
      max_search_results: 50
    max_memory_mb: 256
    max_execution_time: 120
    network_access: true
    allowed_domains:
    - maps.api.com
    - parkingdata.com
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_location: 'City Center'
    preferred_parking_type: 'Covered'
    user_vehicle_type: 'Sedan'
  system_info:
    navigation_client_version: '2.3'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: false
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true