name: personalized_academic_assistant
display_name: Personalized Academic Assistant
description: The Personalized Academic Assistant offers tailored study plans, resources,
  and academic advice to students. It helps in organizing study schedules, finding
  relevant academic materials, and providing guidance on various subjects to enhance
  learning efficiency.
category: education
complexity_level: 4
estimated_duration: 45
required_permissions:
- internet_access
- personal_data_access
dependencies: []
generation_weight: 1.8
sample_actions:
- create_study_plan
- recommend_resources
- provide_academic_advice
- track_progress
metadata:
  selection_way: random
  selection_num: 3
tags:
- education
- learning
- personalization
context:
  available_tools:
  - name: create_study_plan
    display_name: Create Study Plan
    description: Generate a personalized study plan based on the student's schedule
      and goals
    category: education
    parameters:
    - name: subjects
      type: list
      description: List of subjects to include in the study plan
      required: true
    - name: study_hours_per_week
      type: integer
      description: Number of hours available for study each week
      required: true
    - name: goals
      type: string
      description: Academic goals to achieve
      required: true
    example_usage:
    - create_study_plan(subjects=['Math', 'Science'], study_hours_per_week=10, goals='Improve
      grades in Math and Science')
  - name: recommend_resources
    display_name: Recommend Resources
    description: Suggest educational resources such as books, articles, and online
      courses
    category: education
    parameters:
    - name: subject
      type: string
      description: Subject for which resources are needed
      required: true
    - name: resource_type
      type: string
      description: Type of resource
      required: false
      default_value: all
      allowed_values:
      - all
      - book
      - article
      - course
    example_usage:
    - recommend_resources(subject='History', resource_type='book')
    - recommend_resources(subject='Physics')
  environment:
    name: academic_assistant_env
    description: Environment for academic assistance with access to educational databases
    variables:
    - name: MAX_RESOURCES_PER_QUERY
      value: 10
      description: Maximum number of resources to recommend per query
      type: integer
    - name: STUDY_PLAN_TEMPLATE
      value: default_template
      description: Template used for generating study plans
      type: string
    settings:
      personalized_recommendations: true
      progress_tracking_enabled: true
    max_memory_mb: 1024
    max_execution_time: 600
    network_access: true
    allowed_domains:
    - '*.edu'
    - '*.academic-resources.com'
    blocked_domains:
    - '*.social-media.com'
  predefined_variables:
    current_user_name: Student
    academic_year: 2023-2024
    timezone: UTC-5
    study_hours: 9:00-21:00
  system_info:
    available_libraries:
    - numpy
    - pandas
    - requests
  security_policy:
    data_classification_required: true
    encryption_at_rest: true
    audit_logging: true