name: photo_organizer
display_name: Photo Organizer
description: An AI-driven tool that sorts and tags your image library, enhancing organization
  and accessibility. It leverages advanced image recognition to categorize photos
  based on content, date, and location metadata.
category: media_management
complexity_level: 4
estimated_duration: 45
required_permissions:
- photo_library_access
- metadata_access
dependencies: []
generation_weight: 1.8
sample_actions:
- sort_photos
- tag_photos
- search_photos
- delete_duplicates
metadata:
  selection_way: random
  selection_num: 10
tags:
- photos
- organization
- AI
- media
context:
  available_tools:
  - name: sort_photos
    display_name: Sort Photos
    description: Organize photos into folders based on date, location, or content
    category: media_management
    parameters:
    - name: criteria
      type: string
      description: Sorting criteria such as date, location, or content
      required: true
      allowed_values:
      - date
      - location
      - content
    example_usage:
    - sort_photos(criteria='date')
    - sort_photos(criteria='location')
    common_errors:
    - Invalid sorting criteria
    - Insufficient metadata for sorting
  - name: tag_photos
    display_name: Tag Photos
    description: Apply tags to photos based on detected objects and scenes
    category: media_management
    parameters:
    - name: tags
      type: list
      description: List of tags to apply
      required: true
    example_usage:
    - tag_photos(tags=['vacation', 'beach'])
    - tag_photos(tags=['family', 'holiday'])
  environment:
    name: photo_management_system
    description: A secure environment for managing and organizing digital photos
    variables:
    - name: MAX_PHOTO_SIZE_MB
      value: 10
      description: Maximum size of a photo in MB
      type: integer
    - name: SUPPORTED_FORMATS
      value: ['jpg', 'png', 'gif']
      description: Supported photo formats
      type: list
    settings:
      auto_backup_enabled: true
      max_photos_per_operation: 100
    max_memory_mb: 1024
    max_execution_time: 600
    network_access: true
    allowed_domains:
    - '*.trusted-photo-service.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_name: Photo Enthusiast
    timezone: UTC-5
    preferred_photo_format: jpg
  system_info:
    photo_management_version: '2.1'
    available_libraries:
    - pillow
    - opencv
  security_policy:
    data_classification_required: true
    encryption_at_rest: true
    audit_logging: true