name: photo_restoration_specialist
display_name: Photo Restoration Specialist
description: Restores, edits, or enhances old or damaged images using advanced photo editing tools and techniques. This scenario involves using digital tools to repair and improve the quality of photographs that have been affected by time, wear, or damage.
category: image_processing
complexity_level: 4
estimated_duration: 45
required_permissions:
- image_editing_access
- file_system_access
dependencies: []
generation_weight: 1.8
sample_actions:
- load_image
- apply_filter
- adjust_brightness
- remove_noise
- save_image
metadata:
  selection_way: random
  selection_num: 3
tags:
- photo_restoration
- image_editing
- digital_art
context:
  available_tools:
  - name: load_image
    display_name: Load Image
    description: Load an image file for editing
    category: file_management
    parameters:
    - name: file_path
      type: string
      description: Path to the image file
      required: true
      validation_pattern: ^.*\.(jpg|jpeg|png|tiff)$
    example_usage:
    - load_image(file_path='old_photo.jpg')
    common_errors:
    - File not found
    - Unsupported file format
  - name: apply_filter
    display_name: Apply Filter
    description: Apply a filter to enhance the image
    category: image_processing
    parameters:
    - name: filter_type
      type: string
      description: Type of filter to apply
      required: true
      allowed_values:
      - sepia
      - grayscale
      - sharpen
    example_usage:
    - apply_filter(filter_type='sepia')
  - name: adjust_brightness
    display_name: Adjust Brightness
    description: Adjust the brightness of the image
    category: image_processing
    parameters:
    - name: level
      type: integer
      description: Brightness level adjustment
      required: true
      validation_range: [-100, 100]
    example_usage:
    - adjust_brightness(level=20)
  environment:
    name: photo_editing_suite
    description: A secure environment for photo editing with necessary tools and libraries
    variables:
    - name: MAX_IMAGE_SIZE_MB
      value: 50
      description: Maximum image size in MB
      type: integer
    - name: SUPPORTED_FORMATS
      value: jpg,jpeg,png,tiff
      description: Supported image formats
      type: string
    settings:
      auto_save_interval: 10
      max_undo_steps: 20
    max_memory_mb: 1024
    max_execution_time: 600
    network_access: false
  predefined_variables:
    current_user_name: Photo Editor AI
    company_name: ImageTech Solutions
    timezone: UTC-5
    business_hours: 8:00-18:00
  system_info:
    image_editing_software_version: '2.5'
    available_libraries:
    - PIL
    - OpenCV
  security_policy:
    data_classification_required: false
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true