name: professional_headshot_creator
display_name: Professional Headshot Creator
description: Converts ordinary photos into polished headshots, enhancing features and
  adjusting lighting to create professional-quality images suitable for resumes, LinkedIn
  profiles, and other professional uses.
category: image_processing
complexity_level: 4
estimated_duration: 45
required_permissions:
- photo_library_access
- internet_access
dependencies: []
generation_weight: 1.8
sample_actions:
- upload_photo
- apply_filter
- adjust_lighting
- export_headshot
metadata:
  selection_way: random
  selection_num: 3
tags:
- photography
- image_processing
- professional_development
context:
  available_tools:
  - name: upload_photo
    display_name: Upload Photo
    description: Upload a photo from the device or cloud storage
    category: image_processing
    parameters:
    - name: file_path
      type: string
      description: Path to the photo file
      required: true
    example_usage:
    - upload_photo(file_path='/images/photo.jpg')
  - name: apply_filter
    display_name: Apply Filter
    description: Apply a filter to enhance the photo
    category: image_processing
    parameters:
    - name: filter_type
      type: string
      description: Type of filter to apply
      required: true
      allowed_values:
      - natural
      - vibrant
      - black_and_white
    example_usage:
    - apply_filter(filter_type='natural')
  - name: adjust_lighting
    display_name: Adjust Lighting
    description: Adjust the lighting of the photo for better clarity
    category: image_processing
    parameters:
    - name: brightness
      type: integer
      description: Level of brightness adjustment
      required: false
      default_value: 0
    - name: contrast
      type: integer
      description: Level of contrast adjustment
      required: false
      default_value: 0
    example_usage:
    - adjust_lighting(brightness=10, contrast=5)
  environment:
    name: photo_editing_suite
    description: A secure environment for editing and processing photos with privacy
      controls
    variables:
    - name: MAX_IMAGE_SIZE_MB
      value: 50
      description: Maximum image size in MB
      type: integer
    - name: SUPPORTED_FORMATS
      value: ['jpg', 'png', 'tiff']
      description: Supported image formats
      type: list
    settings:
      auto_save: true
      max_concurrent_edits: 5
    max_memory_mb: 1024
    max_execution_time: 600
    network_access: true
    allowed_domains:
    - '*.trusted-photo-service.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    default_filter: natural
    default_brightness: 0
    default_contrast: 0
  system_info:
    photo_editing_version: '2.3'
    available_libraries:
    - PIL
    - OpenCV
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true