name: real_estate_analyzer
display_name: Real Estate Analyzer
description: Evaluates property listings and generates neighborhood comparisons to assist
  potential buyers in making informed decisions. The agent analyzes various property
  attributes and compares them against neighborhood statistics to provide comprehensive
  insights.
category: analysis
complexity_level: 4
estimated_duration: 45
required_permissions:
- data_access
- internet_access
dependencies: []
generation_weight: 1.8
sample_actions:
- evaluate_property
- compare_neighborhoods
- generate_report
metadata:
  selection_way: random
  selection_num: 3
tags:
- real_estate
- analysis
- data_processing
context:
  available_tools:
  - name: evaluate_property
    display_name: Evaluate Property
    description: Analyze property details such as price, size, and amenities
    category: analysis
    parameters:
    - name: property_id
      type: string
      description: Unique identifier for the property
      required: true
    - name: attributes
      type: list
      description: List of property attributes to evaluate
      required: true
    example_usage:
    - evaluate_property(property_id='12345', attributes=['price', 'size', 'amenities'])
  - name: compare_neighborhoods
    display_name: Compare Neighborhoods
    description: Compare property listings across different neighborhoods
    category: analysis
    parameters:
    - name: neighborhood_ids
      type: list
      description: List of neighborhood identifiers
      required: true
    - name: comparison_criteria
      type: list
      description: Criteria for comparison such as price, schools, crime rate
      required: true
    example_usage:
    - compare_neighborhoods(neighborhood_ids=['n1', 'n2'], comparison_criteria=['price', 'schools'])
  environment:
    name: real_estate_analysis_env
    description: Environment for analyzing real estate data with access to property and neighborhood databases
    variables:
    - name: API_ENDPOINT
      value: api.realestate.com
      description: API endpoint for accessing real estate data
      type: string
    - name: MAX_PROPERTIES
      value: 100
      description: Maximum number of properties to analyze in one session
      type: integer
    settings:
      data_refresh_interval: 24
      max_comparison_criteria: 5
    max_memory_mb: 1024
    max_execution_time: 600
    network_access: true
    allowed_domains:
    - realestate.com
    - '*.trusted-data-source.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_role: analyst
    default_currency: USD
    timezone: UTC-5
    business_hours: 8:00-18:00
  system_info:
    analysis_tool_version: '2.1'
    available_libraries:
    - pandas
    - numpy
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true