name: sora_video_prompt_optimizer
display_name: Sora Video Prompt Optimizer
description: This scenario involves refining video generation prompts and pairing them with images to enhance the quality and relevance of video content. The agent will optimize prompts for better video synthesis and ensure that the selected images align with the intended video themes and messages.
category: content_creation
complexity_level: 4
estimated_duration: 45
required_permissions:
- image_access
- video_generation_access
dependencies: []
generation_weight: 1.8
sample_actions:
- refine_prompt
- select_image
- generate_video
- evaluate_output
metadata:
  selection_way: random
  selection_num: 3
tags:
- video
- content_creation
- optimization
context:
  available_tools:
  - name: refine_prompt
    display_name: Refine Prompt
    description: Refine video generation prompts for clarity and effectiveness
    category: content_creation
    parameters:
    - name: prompt
      type: string
      description: Initial video generation prompt
      required: true
    - name: target_audience
      type: string
      description: Intended audience for the video
      required: false
    example_usage:
    - refine_prompt(prompt='Create a video about space exploration')
  - name: select_image
    display_name: Select Image
    description: Choose images that align with video prompts
    category: content_creation
    parameters:
    - name: image_tags
      type: list
      description: Tags to search for relevant images
      required: true
    - name: resolution
      type: string
      description: Desired image resolution
      required: false
      default_value: '1080p'
    example_usage:
    - select_image(image_tags=['space', 'rocket'])
  - name: generate_video
    display_name: Generate Video
    description: Generate video content based on refined prompts and selected images
    category: content_creation
    parameters:
    - name: prompt
      type: string
      description: Refined video generation prompt
      required: true
    - name: images
      type: list
      description: List of image paths to include
      required: true
    example_usage:
    - generate_video(prompt='Explore the universe', images=['space1.jpg', 'rocket.png'])
  environment:
    name: video_creation_suite
    description: Environment equipped with tools for video prompt optimization and generation
    variables:
    - name: VIDEO_API_ENDPOINT
      value: api.videogen.com
      description: Endpoint for video generation API
      type: string
    - name: MAX_VIDEO_LENGTH
      value: 300
      description: Maximum video length in seconds
      type: integer
    - name: IMAGE_REPOSITORY
      value: images.videogen.com
      description: Repository for image selection
      type: string
    settings:
      high_resolution_support: true
      prompt_suggestion_enabled: true
    max_memory_mb: 1024
    max_execution_time: 600
    network_access: true
    allowed_domains:
    - videogen.com
    - '*.trusted-image-source.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_role: Video Content Specialist
    company_name: MediaTech Innovations
    timezone: UTC-5
    business_hours: 8:00-18:00
  system_info:
    video_generation_version: '2.5'
    available_libraries:
    - opencv
    - pillow
  security_policy:
    data_classification_required: true
    external_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true