name: statistics_coach
display_name: Statistics Coach
description: The Statistics Coach agent is designed to teach statistics, solve statistical problems, and explain data analysis concepts. It provides users with guidance on statistical methods, helps in interpreting data, and offers solutions to complex statistical queries.
category: education
complexity_level: 4
estimated_duration: 45
required_permissions:
- data_access
dependencies: []
generation_weight: 1.8
sample_actions:
- explain_concept
- solve_problem
- analyze_data
- generate_report
metadata:
  selection_way: random
  selection_num: 3
tags:
- statistics
- education
- data_analysis
context:
  available_tools:
  - name: solve_statistical_problem
    display_name: Solve Statistical Problem
    description: Provides solutions to statistical problems using various methods
    category: education
    parameters:
    - name: problem_statement
      type: string
      description: The statistical problem to solve
      required: true
    - name: method
      type: string
      description: Statistical method to use
      required: false
      allowed_values:
      - regression
      - hypothesis_testing
      - probability
    example_usage:
    - solve_statistical_problem(problem_statement='Calculate the mean of the dataset', method='regression')
    - solve_statistical_problem(problem_statement='Test the hypothesis', method='hypothesis_testing')
  - name: explain_statistical_concept
    display_name: Explain Statistical Concept
    description: Provides explanations for various statistical concepts
    category: education
    parameters:
    - name: concept
      type: string
      description: The statistical concept to explain
      required: true
    example_usage:
    - explain_statistical_concept(concept='Standard Deviation')
    - explain_statistical_concept(concept='P-value')
  environment:
    name: statistical_analysis
    description: Environment for performing statistical analysis and data interpretation
    variables:
    - name: DATA_SOURCE
      value: data_repository
      description: Source of the data for analysis
      type: string
    - name: MAX_DATA_SIZE_MB
      value: 100
      description: Maximum data size for analysis in MB
      type: integer
    settings:
      data_encryption_required: true
      logging_enabled: true
      max_concurrent_sessions: 10
    max_memory_mb: 1024
    max_execution_time: 600
    network_access: true
    allowed_domains:
    - '*.trusted-data-source.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_role: Data Analyst
    preferred_statistical_software: R
    timezone: UTC-5
    working_hours: 8:00-18:00
  system_info:
    statistical_software_version: '3.6.1'
    available_libraries:
    - numpy
    - pandas
    - scipy
  security_policy:
    data_classification_required: true
    external_data_sharing_approval: true
    encryption_at_rest: true
    audit_logging: true