name: system_backup
display_name: System Backup
description: The agent schedules regular system backups, confirms their completion, and notifies administrators of any issues encountered during the process. This ensures data integrity and availability in case of system failures or data loss.
category: data_management
complexity_level: 4
estimated_duration: 45
required_permissions:
- system_access
- notification_access
dependencies: []
generation_weight: 1.8
sample_actions:
- schedule_backup
- confirm_backup
- notify_issue
- check_backup_status
metadata:
  selection_way: random
  selection_num: 3
tags:
- backup
- data_management
- automation
context:
  available_tools:
  - name: schedule_backup
    display_name: Schedule Backup
    description: Schedule a system backup at a specified time
    category: data_management
    parameters:
    - name: time
      type: string
      description: Time to schedule the backup
      required: true
      validation_pattern: ^([01]?[0-9]|2[0-3]):[0-5][0-9]$
    - name: frequency
      type: string
      description: Frequency of the backup
      required: true
      allowed_values:
      - daily
      - weekly
      - monthly
    example_usage:
    - schedule_backup(time='02:00', frequency='daily')
    - schedule_backup(time='03:00', frequency='weekly')
    common_errors:
    - Invalid time format
    - Unsupported frequency value
  - name: notify_admin
    display_name: Notify Admin
    description: Send a notification to the system administrator
    category: communication
    parameters:
    - name: message
      type: string
      description: Notification message content
      required: true
    example_usage:
    - notify_admin(message='Backup completed successfully.')
    - notify_admin(message='Backup failed due to insufficient storage.')
  environment:
    name: backup_system
    description: Environment configured for managing system backups with necessary security protocols
    variables:
    - name: BACKUP_SERVER
      value: backup.server.com
      description: Server used for storing backups
      type: string
    - name: BACKUP_STORAGE_LIMIT
      value: 1000
      description: Maximum storage limit for backups in GB
      type: integer
    - name: NOTIFICATION_EMAIL
      value: admin@company.com
      description: Email address for sending notifications
      type: string
    settings:
      encryption_required: true
      backup_retention_period_days: 30
    max_memory_mb: 1024
    max_execution_time: 600
    network_access: true
    allowed_domains:
    - company.com
    - '*.trusted-backup.com'
    blocked_domains:
    - '*.untrusted-source.com'
  predefined_variables:
    current_user_email: backup_agent@company.com
    current_user_name: Backup Agent
    company_name: DataSecure Inc.
    timezone: UTC-5
    business_hours: 8:00-18:00
  system_info:
    backup_software_version: '2.5'
    available_libraries:
    - os
    - shutil
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true