name: to_do_list_manager
display_name: To-Do List Manager
description: The To-Do List Manager agent collects, categorizes, and prioritizes daily tasks to help users manage their time effectively. It allows users to add, edit, and remove tasks, set deadlines, and categorize tasks by priority or project.
category: productivity
complexity_level: 2
estimated_duration: 20
required_permissions:
- task_management_access
dependencies: []
generation_weight: 1.2
sample_actions:
- add_task
- edit_task
- remove_task
- set_priority
metadata:
  selection_way: random
  selection_num: 3
tags:
- productivity
- task_management
- organization
context:
  available_tools:
  - name: add_task
    display_name: Add Task
    description: Add a new task to the to-do list
    category: task_management
    parameters:
    - name: task_name
      type: string
      description: Name of the task
      required: true
    - name: due_date
      type: string
      description: Due date for the task
      required: false
    - name: priority
      type: string
      description: Priority level of the task
      required: false
      allowed_values:
      - low
      - medium
      - high
    example_usage:
    - add_task(task_name='Finish report', due_date='2023-10-15', priority='high')
    - add_task(task_name='Buy groceries')
    common_errors:
    - Missing task name
    - Invalid date format
  - name: edit_task
    display_name: Edit Task
    description: Modify an existing task in the to-do list
    category: task_management
    parameters:
    - name: task_id
      type: integer
      description: Unique identifier of the task
      required: true
    - name: new_name
      type: string
      description: New name for the task
      required: false
    - name: new_due_date
      type: string
      description: New due date for the task
      required: false
    - name: new_priority
      type: string
      description: New priority level for the task
      required: false
    example_usage:
    - edit_task(task_id=1, new_name='Complete report', new_due_date='2023-10-16')
  environment:
    name: task_management_system
    description: A system designed to manage and organize tasks efficiently
    variables:
    - name: MAX_TASKS
      value: 100
      description: Maximum number of tasks allowed
      type: integer
    - name: DEFAULT_PRIORITY
      value: medium
      description: Default priority level for new tasks
      type: string
    settings:
      notifications_enabled: true
      reminders_enabled: true
    max_memory_mb: 256
    max_execution_time: 120
    network_access: false
  predefined_variables:
    current_user_name: Task Manager User
    timezone: UTC
    business_hours: 8:00-18:00
  system_info:
    task_management_version: '1.0'
    available_libraries:
    - datetime
    - json
  security_policy:
    data_classification_required: false
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true