name: travel_planner
display_name: Travel Planner
description: The Travel Planner agent suggests travel destinations, builds detailed itineraries, and finds activities for travelers. It aims to provide personalized travel experiences by considering user preferences, budget, and travel constraints.
category: travel
complexity_level: 4
estimated_duration: 45
required_permissions:
- internet_access
- location_access
dependencies: []
generation_weight: 1.8
sample_actions:
- suggest_destination
- build_itinerary
- find_activities
- check_weather
metadata:
  selection_way: random
  selection_num: 3
tags:
- travel
- itinerary
- activities
- planning
context:
  available_tools:
  - name: suggest_destination
    display_name: Suggest Destination
    description: Provide travel destination suggestions based on user preferences
    category: travel
    parameters:
    - name: preferences
      type: list
      description: List of user preferences such as climate, activities, etc.
      required: true
    - name: budget
      type: integer
      description: User's budget for the trip
      required: true
    example_usage:
    - suggest_destination(preferences=['beach', 'warm'], budget=1500)
  - name: build_itinerary
    display_name: Build Itinerary
    description: Create a detailed travel itinerary including flights, accommodations, and activities
    category: travel
    parameters:
    - name: destination
      type: string
      description: Travel destination
      required: true
    - name: start_date
      type: string
      description: Trip start date
      required: true
    - name: end_date
      type: string
      description: Trip end date
      required: true
    example_usage:
    - build_itinerary(destination='Hawaii', start_date='2023-12-01', end_date='2023-12-10')
  - name: find_activities
    display_name: Find Activities
    description: Search for activities and events at a given destination
    category: travel
    parameters:
    - name: destination
      type: string
      description: Destination to find activities
      required: true
    - name: date
      type: string
      description: Date for the activities
      required: false
    example_usage:
    - find_activities(destination='Paris', date='2023-06-15')
  environment:
    name: travel_planning_env
    description: Environment configured for travel planning with access to travel APIs and weather services
    variables:
    - name: API_KEY_TRAVEL
      value: your_api_key_here
      description: API key for accessing travel services
      type: string
    - name: MAX_ITINERARY_ITEMS
      value: 20
      description: Maximum number of items in an itinerary
      type: integer
    settings:
      max_memory_mb: 1024
      max_execution_time: 600
      network_access: true
      allowed_domains:
      - '*.travelapi.com'
      - '*.weatherapi.com'
      blocked_domains:
      - '*.untrusted-source.com'
  predefined_variables:
    current_user_location: 'New York, USA'
    preferred_language: 'English'
    currency: 'USD'
  system_info:
    travel_api_version: '2.1'
    available_libraries:
    - requests
    - json
  security_policy:
    data_classification_required: true
    external_sharing_approval: false
    encryption_at_rest: true
    audit_logging: true