externalAPI_models:
  - api_url: "https://api.deepinfra.com/v1/openai/chat/completions"
    api_key_type: "deepinfra_api_key"
    model: "Qwen/Qwen2.5-72B-Instruct"
    temperature: 1.0
    max_tokens: 4096
  - api_url: "https://api.deepinfra.com/v1/openai/chat/completions"
    api_key_type: "deepinfra_api_key"
    model: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8"
    temperature: 1.0
    max_tokens: 4096
  - api_url: "https://api.deepinfra.com/v1/openai/chat/completions"
    api_key_type: "deepinfra_api_key"
    model: "Qwen/Qwen3-32B"
    temperature: 1.0
    max_tokens: 4096
  - api_url: "https://api.deepinfra.com/v1/openai/chat/completions"
    api_key_type: "deepinfra_api_key"
    model: "deepseek-ai/DeepSeek-V3-0324"
    temperature: 1.0
    max_tokens: 4096